CREATE TABLE IF NOT EXISTS `battle_pet_wild_pool` (
  `zone` INT UNSIGNED NOT NULL DEFAULT 0,
  `species` SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  `entry` INT UNSIGNED NOT NULL DEFAULT 0,
  `max` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `minLevel` TINYINT UNSIGNED NOT NULL DEFAULT 1,
  `maxLevel` TINYINT UNSIGNED NOT NULL DEFAULT 1,
  PRIMARY KEY (`zone`, `species`, `entry`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='Wild battle pet replacement pools';
