-- Reconcile RBAC command permissions with the registered command handlers.

-- Permission 325 is no longer defined by RBAC.h or used by any command handler.
DELETE FROM `rbac_account_permissions` WHERE `permissionId` = 325;
DELETE FROM `rbac_default_permissions` WHERE `permissionId` = 325;
DELETE FROM `rbac_linked_permissions` WHERE `id` = 325 OR `linkedId` = 325;
DELETE FROM `rbac_permissions` WHERE `id` = 325;

INSERT INTO `rbac_permissions` (`id`, `name`) VALUES
(278, 'Command: character deleted delete'),
(281, 'Command: character deleted old'),
(282, 'Command: character erase'),
(313, 'Command: debug Mod32Value'),
(316, 'Command: debug play cinematic'),
(400, 'Command: debug transport'),
(524, 'Command: save'),
(525, 'Command: saveall'),
(576, 'Command: npc delete'),
(577, 'Command: npc delete item'),
(578, 'Command: npc follow'),
(579, 'Command: npc follow stop'),
(631, 'Command: reload creature_ai_scripts'),
(632, 'Command: reload creature_ai_texts'),
(633, 'Command: reload creature_linked_respawn'),
(634, 'Command: reload creature_loot_template'),
(635, 'Command: reload creature_onkill_reputation'),
(636, 'Command: reload creature_questender'),
(637, 'Command: reload creature_queststarter'),
(638, 'Command: reload creature_summon_groups'),
(639, 'Command: reload creature_template'),
(640, 'Command: reload creature_text'),
(646, 'Command: reload gameobject_questender'),
(647, 'Command: reload gameobject_loot_template'),
(648, 'Command: reload gameobject_queststarter'),
(649, 'Command: reload game_tele'),
(661, 'Command: reload gossip_menu_option_locale'),
(682, 'Command: reload reputation_reward_rate'),
(683, 'Command: reload reserved_name'),
(684, 'Command: reload skill_discovery_template'),
(685, 'Command: reload skill_extra_item_template'),
(686, 'Command: reload skill_fishing_base_level'),
(687, 'Command: reload skinning_loot_template'),
(688, 'Command: reload smart_scripts'),
(689, 'Command: reload spell_area'),
(690, 'Command: reload spell_bonus_data'),
(691, 'Command: reload spell_group'),
(692, 'Command: reload spell_group_stack_rules'),
(693, 'Command: reload spell_learn_spell'),
(694, 'Command: reload spell_linked_spell'),
(696, 'Command: reload spell_pet_auras'),
(697, 'Command: reload spell_proc'),
(699, 'Command: reload spell_required'),
(703, 'Command: reload reputation_spillover_template'),
(704, 'Command: reload skyfire_string'),
(705, 'Command: reload vehicle_accessory'),
(706, 'Command: reload vehicle_template_accessory'),
(707, 'Command: reload warden_action'),
(708, 'Command: reload waypoint_data'),
(709, 'Command: reload waypoint_scripts'),
(776, 'Command: server uptime'),
(777, 'Command: ticket bug'),
(778, 'Command: ticket bug assign'),
(779, 'Command: ticket bug close'),
(780, 'Command: ticket bug closedlist'),
(781, 'Command: ticket bug comment'),
(782, 'Command: ticket bug delete'),
(783, 'Command: ticket bug list'),
(784, 'Command: ticket bug unassign'),
(785, 'Command: ticket bug view'),
(786, 'Command: ticket bug reset'),
(787, 'Command: ticket suggest'),
(788, 'Command: ticket suggest assign'),
(789, 'Command: ticket suggest close'),
(790, 'Command: ticket suggest closedlist'),
(791, 'Command: ticket suggest comment'),
(792, 'Command: ticket suggest delete'),
(793, 'Command: ticket suggest list'),
(794, 'Command: ticket suggest unassign'),
(795, 'Command: ticket suggest view'),
(796, 'Command: ticket suggest reset'),
(800, 'Command: reload quest_objective'),
(801, 'Command: reload quest_objective_effects'),
(802, 'Command: reload locales_quest_objective'),
(803, 'Command: reload bmauctions'),
(804, 'Command: reload blackmarket_template'),
(805, 'Command: account boost'),
(806, 'Command: account boost add'),
(807, 'Command: account boost delete')
ON DUPLICATE KEY UPDATE `name` = VALUES(`name`);

DELETE FROM `rbac_linked_permissions`
WHERE (`id` = 198 AND `linkedId` = 524)
   OR (`id` = 199 AND `linkedId` = 525);

INSERT IGNORE INTO `rbac_linked_permissions` (`id`, `linkedId`) VALUES
(196, 278),
(196, 281),
(196, 282),
(196, 776),
(198, 525),
(199, 524);
