DELETE FROM `npc_trainer` WHERE `entry`= 63335;
DELETE FROM `npc_trainer` WHERE `entry`= 63332;
DELETE FROM `npc_trainer` WHERE `entry`= 63331;
DELETE FROM `npc_trainer` WHERE `entry`= 63327;
DELETE FROM `npc_trainer` WHERE `entry`= 63310;
DELETE FROM `npc_trainer` WHERE `entry`= 63296;
DELETE FROM `npc_trainer` WHERE `entry`= 63285;
DELETE FROM `npc_trainer` WHERE `entry`= 63272;
DELETE FROM `npc_trainer` WHERE `entry`= 63258;
DELETE FROM `npc_trainer` WHERE `entry`= 63238;
DELETE FROM `npc_trainer` WHERE `entry`= 62321;
DELETE FROM `npc_trainer` WHERE `entry`= 52319;
DELETE FROM `npc_trainer` WHERE `entry`= 52292;
DELETE FROM `npc_trainer` WHERE `entry`= 51998;
DELETE FROM `npc_trainer` WHERE `entry`= 51640;
DELETE FROM `npc_trainer` WHERE `entry`= 51639;
DELETE FROM `npc_trainer` WHERE `entry`= 51637;
DELETE FROM `npc_trainer` WHERE `entry`= 50690;
DELETE FROM `npc_trainer` WHERE `entry`= 49749;
DELETE FROM `npc_trainer` WHERE `entry`= 47246;
DELETE FROM `npc_trainer` WHERE `entry`= 47233;
DELETE FROM `npc_trainer` WHERE `entry`= 45347;
DELETE FROM `npc_trainer` WHERE `entry`= 45339;
DELETE FROM `npc_trainer` WHERE `entry`= 45337;
DELETE FROM `npc_trainer` WHERE `entry`= 45306;
DELETE FROM `npc_trainer` WHERE `entry`= 45137;
DELETE FROM `npc_trainer` WHERE `entry`= 44978;
DELETE FROM `npc_trainer` WHERE `entry`= 44735;
DELETE FROM `npc_trainer` WHERE `entry`= 44726;
DELETE FROM `npc_trainer` WHERE `entry`= 44725;
DELETE FROM `npc_trainer` WHERE `entry`= 44469;
DELETE FROM `npc_trainer` WHERE `entry`= 44468;
DELETE FROM `npc_trainer` WHERE `entry`= 44465;
DELETE FROM `npc_trainer` WHERE `entry`= 44464;
DELETE FROM `npc_trainer` WHERE `entry`= 44461;
DELETE FROM `npc_trainer` WHERE `entry`= 44459;
DELETE FROM `npc_trainer` WHERE `entry`= 44455;
DELETE FROM `npc_trainer` WHERE `entry`= 44395;
DELETE FROM `npc_trainer` WHERE `entry`= 44247;
DELETE FROM `npc_trainer` WHERE `entry`= 43870;
DELETE FROM `npc_trainer` WHERE `entry`= 43795;
DELETE FROM `npc_trainer` WHERE `entry`= 43455;
DELETE FROM `npc_trainer` WHERE `entry`= 43278;
DELETE FROM `npc_trainer` WHERE `entry`= 43010;
DELETE FROM `npc_trainer` WHERE `entry`= 43009;
DELETE FROM `npc_trainer` WHERE `entry`= 43006;
DELETE FROM `npc_trainer` WHERE `entry`= 42618;
DELETE FROM `npc_trainer` WHERE `entry`= 42366;
DELETE FROM `npc_trainer` WHERE `entry`= 42331;
DELETE FROM `npc_trainer` WHERE `entry`= 42324;
DELETE FROM `npc_trainer` WHERE `entry`= 42323;
DELETE FROM `npc_trainer` WHERE `entry`= 39214;
DELETE FROM `npc_trainer` WHERE `entry`= 39206;
DELETE FROM `npc_trainer` WHERE `entry`= 39116;
DELETE FROM `npc_trainer` WHERE `entry`= 39100;
DELETE FROM `npc_trainer` WHERE `entry`= 38911;
DELETE FROM `npc_trainer` WHERE `entry`= 38799;
DELETE FROM `npc_trainer` WHERE `entry`= 38798;
DELETE FROM `npc_trainer` WHERE `entry`= 38797;
DELETE FROM `npc_trainer` WHERE `entry`= 38796;
DELETE FROM `npc_trainer` WHERE `entry`= 38795;
DELETE FROM `npc_trainer` WHERE `entry`= 38793;
DELETE FROM `npc_trainer` WHERE `entry`= 38517;
DELETE FROM `npc_trainer` WHERE `entry`= 38467;
DELETE FROM `npc_trainer` WHERE `entry`= 38466;
DELETE FROM `npc_trainer` WHERE `entry`= 38247;
DELETE FROM `npc_trainer` WHERE `entry`= 38246;
DELETE FROM `npc_trainer` WHERE `entry`= 38245;
DELETE FROM `npc_trainer` WHERE `entry`= 38244;
DELETE FROM `npc_trainer` WHERE `entry`= 38243;
DELETE FROM `npc_trainer` WHERE `entry`= 38122;
DELETE FROM `npc_trainer` WHERE `entry`= 38037;
DELETE FROM `npc_trainer` WHERE `entry`= 37737;
DELETE FROM `npc_trainer` WHERE `entry`= 37724;
DELETE FROM `npc_trainer` WHERE `entry`= 37121;
DELETE FROM `npc_trainer` WHERE `entry`= 37115;
DELETE FROM `npc_trainer` WHERE `entry`= 36652;
DELETE FROM `npc_trainer` WHERE `entry`= 36651;
DELETE FROM `npc_trainer` WHERE `entry`= 36632;
DELETE FROM `npc_trainer` WHERE `entry`= 36630;
DELETE FROM `npc_trainer` WHERE `entry`= 36629;
DELETE FROM `npc_trainer` WHERE `entry`= 36628;
DELETE FROM `npc_trainer` WHERE `entry`= 36521;
DELETE FROM `npc_trainer` WHERE `entry`= 35874;
DELETE FROM `npc_trainer` WHERE `entry`= 35873;
DELETE FROM `npc_trainer` WHERE `entry`= 35872;
DELETE FROM `npc_trainer` WHERE `entry`= 35871;
DELETE FROM `npc_trainer` WHERE `entry`= 35870;
DELETE FROM `npc_trainer` WHERE `entry`= 35869;
DELETE FROM `npc_trainer` WHERE `entry`= 35839;
DELETE FROM `npc_trainer` WHERE `entry`= 35786;
DELETE FROM `npc_trainer` WHERE `entry`= 35758;
DELETE FROM `npc_trainer` WHERE `entry`= 35281;
DELETE FROM `npc_trainer` WHERE `entry`= 34697;
DELETE FROM `npc_trainer` WHERE `entry`= 34696;
DELETE FROM `npc_trainer` WHERE `entry`= 34695;
DELETE FROM `npc_trainer` WHERE `entry`= 34693;
DELETE FROM `npc_trainer` WHERE `entry`= 34692;
DELETE FROM `npc_trainer` WHERE `entry`= 34689;
DELETE FROM `npc_trainer` WHERE `entry`= 34673;
DELETE FROM `npc_trainer` WHERE `entry`= 31084;
DELETE FROM `npc_trainer` WHERE `entry`= 29156;
DELETE FROM `npc_trainer` WHERE `entry`= 28474;
DELETE FROM `npc_trainer` WHERE `entry`= 28472;
DELETE FROM `npc_trainer` WHERE `entry`= 28471;
DELETE FROM `npc_trainer` WHERE `entry`= 23566;
DELETE FROM `npc_trainer` WHERE `entry`= 23128;
DELETE FROM `npc_trainer` WHERE `entry`= 23127;
DELETE FROM `npc_trainer` WHERE `entry`= 20407;
DELETE FROM `npc_trainer` WHERE `entry`= 20406;
DELETE FROM `npc_trainer` WHERE `entry`= 17844;
DELETE FROM `npc_trainer` WHERE `entry`= 17520;
DELETE FROM `npc_trainer` WHERE `entry`= 17519;
DELETE FROM `npc_trainer` WHERE `entry`= 17514;
DELETE FROM `npc_trainer` WHERE `entry`= 17513;
DELETE FROM `npc_trainer` WHERE `entry`= 17511;
DELETE FROM `npc_trainer` WHERE `entry`= 17509;
DELETE FROM `npc_trainer` WHERE `entry`= 17505;
DELETE FROM `npc_trainer` WHERE `entry`= 17483;
DELETE FROM `npc_trainer` WHERE `entry`= 17482;
DELETE FROM `npc_trainer` WHERE `entry`= 17481;
DELETE FROM `npc_trainer` WHERE `entry`= 17480;
DELETE FROM `npc_trainer` WHERE `entry`= 17219;
DELETE FROM `npc_trainer` WHERE `entry`= 17212;
DELETE FROM `npc_trainer` WHERE `entry`= 17204;
DELETE FROM `npc_trainer` WHERE `entry`= 17122;
DELETE FROM `npc_trainer` WHERE `entry`= 17120;
DELETE FROM `npc_trainer` WHERE `entry`= 17110;
DELETE FROM `npc_trainer` WHERE `entry`= 17089;
DELETE FROM `npc_trainer` WHERE `entry`= 16771;
DELETE FROM `npc_trainer` WHERE `entry`= 16761;
DELETE FROM `npc_trainer` WHERE `entry`= 16756;
DELETE FROM `npc_trainer` WHERE `entry`= 16749;
DELETE FROM `npc_trainer` WHERE `entry`= 16738;
DELETE FROM `npc_trainer` WHERE `entry`= 16721;
DELETE FROM `npc_trainer` WHERE `entry`= 16685;
DELETE FROM `npc_trainer` WHERE `entry`= 16684;
DELETE FROM `npc_trainer` WHERE `entry`= 16681;
DELETE FROM `npc_trainer` WHERE `entry`= 16674;
DELETE FROM `npc_trainer` WHERE `entry`= 16673;
DELETE FROM `npc_trainer` WHERE `entry`= 16672;
DELETE FROM `npc_trainer` WHERE `entry`= 16661;
DELETE FROM `npc_trainer` WHERE `entry`= 16659;
DELETE FROM `npc_trainer` WHERE `entry`= 16658;
DELETE FROM `npc_trainer` WHERE `entry`= 16655;
DELETE FROM `npc_trainer` WHERE `entry`= 16653;
DELETE FROM `npc_trainer` WHERE `entry`= 16652;
DELETE FROM `npc_trainer` WHERE `entry`= 16651;
DELETE FROM `npc_trainer` WHERE `entry`= 16648;
DELETE FROM `npc_trainer` WHERE `entry`= 16647;
DELETE FROM `npc_trainer` WHERE `entry`= 16646;
DELETE FROM `npc_trainer` WHERE `entry`= 16503;
DELETE FROM `npc_trainer` WHERE `entry`= 16502;
DELETE FROM `npc_trainer` WHERE `entry`= 16501;
DELETE FROM `npc_trainer` WHERE `entry`= 16500;
DELETE FROM `npc_trainer` WHERE `entry`= 16499;
DELETE FROM `npc_trainer` WHERE `entry`= 16276;
DELETE FROM `npc_trainer` WHERE `entry`= 16275;
DELETE FROM `npc_trainer` WHERE `entry`= 15513;
DELETE FROM `npc_trainer` WHERE `entry`= 15285;
DELETE FROM `npc_trainer` WHERE `entry`= 15284;
DELETE FROM `npc_trainer` WHERE `entry`= 15283;
DELETE FROM `npc_trainer` WHERE `entry`= 15280;
DELETE FROM `npc_trainer` WHERE `entry`= 15279;
DELETE FROM `npc_trainer` WHERE `entry`= 13417;
DELETE FROM `npc_trainer` WHERE `entry`= 13283;
DELETE FROM `npc_trainer` WHERE `entry`= 12042;
DELETE FROM `npc_trainer` WHERE `entry`= 11406;
DELETE FROM `npc_trainer` WHERE `entry`= 11401;
DELETE FROM `npc_trainer` WHERE `entry`= 11397;
DELETE FROM `npc_trainer` WHERE `entry`= 9465;
DELETE FROM `npc_trainer` WHERE `entry`= 8664;
DELETE FROM `npc_trainer` WHERE `entry`= 8142;
DELETE FROM `npc_trainer` WHERE `entry`= 7315;
DELETE FROM `npc_trainer` WHERE `entry`= 7312;
DELETE FROM `npc_trainer` WHERE `entry`= 7311;
DELETE FROM `npc_trainer` WHERE `entry`= 6251;
DELETE FROM `npc_trainer` WHERE `entry`= 6018;
DELETE FROM `npc_trainer` WHERE `entry`= 6014;
DELETE FROM `npc_trainer` WHERE `entry`= 5994;
DELETE FROM `npc_trainer` WHERE `entry`= 5958;
DELETE FROM `npc_trainer` WHERE `entry`= 5885;
DELETE FROM `npc_trainer` WHERE `entry`= 5884;
DELETE FROM `npc_trainer` WHERE `entry`= 5883;
DELETE FROM `npc_trainer` WHERE `entry`= 5882;
DELETE FROM `npc_trainer` WHERE `entry`= 5880;
DELETE FROM `npc_trainer` WHERE `entry`= 5517;
DELETE FROM `npc_trainer` WHERE `entry`= 5516;
DELETE FROM `npc_trainer` WHERE `entry`= 5515;
DELETE FROM `npc_trainer` WHERE `entry`= 5505;
DELETE FROM `npc_trainer` WHERE `entry`= 5504;
DELETE FROM `npc_trainer` WHERE `entry`= 5498;
DELETE FROM `npc_trainer` WHERE `entry`= 5497;
DELETE FROM `npc_trainer` WHERE `entry`= 5489;
DELETE FROM `npc_trainer` WHERE `entry`= 5480;
DELETE FROM `npc_trainer` WHERE `entry`= 5479;
DELETE FROM `npc_trainer` WHERE `entry`= 5173;
DELETE FROM `npc_trainer` WHERE `entry`= 5172;
DELETE FROM `npc_trainer` WHERE `entry`= 5167;
DELETE FROM `npc_trainer` WHERE `entry`= 5165;
DELETE FROM `npc_trainer` WHERE `entry`= 5149;
DELETE FROM `npc_trainer` WHERE `entry`= 5147;
DELETE FROM `npc_trainer` WHERE `entry`= 5146;
DELETE FROM `npc_trainer` WHERE `entry`= 5145;
DELETE FROM `npc_trainer` WHERE `entry`= 5144;
DELETE FROM `npc_trainer` WHERE `entry`= 5116;
DELETE FROM `npc_trainer` WHERE `entry`= 5115;
DELETE FROM `npc_trainer` WHERE `entry`= 5113;
DELETE FROM `npc_trainer` WHERE `entry`= 4606;
DELETE FROM `npc_trainer` WHERE `entry`= 4595;
DELETE FROM `npc_trainer` WHERE `entry`= 4593;
DELETE FROM `npc_trainer` WHERE `entry`= 4584;
DELETE FROM `npc_trainer` WHERE `entry`= 4583;
DELETE FROM `npc_trainer` WHERE `entry`= 4568;
DELETE FROM `npc_trainer` WHERE `entry`= 4567;
DELETE FROM `npc_trainer` WHERE `entry`= 4566;
DELETE FROM `npc_trainer` WHERE `entry`= 4563;
DELETE FROM `npc_trainer` WHERE `entry`= 4218;
DELETE FROM `npc_trainer` WHERE `entry`= 4214;
DELETE FROM `npc_trainer` WHERE `entry`= 4205;
DELETE FROM `npc_trainer` WHERE `entry`= 4163;
DELETE FROM `npc_trainer` WHERE `entry`= 4146;
DELETE FROM `npc_trainer` WHERE `entry`= 4138;
DELETE FROM `npc_trainer` WHERE `entry`= 4090;
DELETE FROM `npc_trainer` WHERE `entry`= 4087;
DELETE FROM `npc_trainer` WHERE `entry`= 3707;
DELETE FROM `npc_trainer` WHERE `entry`= 3706;
DELETE FROM `npc_trainer` WHERE `entry`= 3602;
DELETE FROM `npc_trainer` WHERE `entry`= 3601;
DELETE FROM `npc_trainer` WHERE `entry`= 3600;
DELETE FROM `npc_trainer` WHERE `entry`= 3599;
DELETE FROM `npc_trainer` WHERE `entry`= 3598;
DELETE FROM `npc_trainer` WHERE `entry`= 3597;
DELETE FROM `npc_trainer` WHERE `entry`= 3596;
DELETE FROM `npc_trainer` WHERE `entry`= 3595;
DELETE FROM `npc_trainer` WHERE `entry`= 3594;
DELETE FROM `npc_trainer` WHERE `entry`= 3593;
DELETE FROM `npc_trainer` WHERE `entry`= 3408;
DELETE FROM `npc_trainer` WHERE `entry`= 3407;
DELETE FROM `npc_trainer` WHERE `entry`= 3406;
DELETE FROM `npc_trainer` WHERE `entry`= 3401;
DELETE FROM `npc_trainer` WHERE `entry`= 3354;
DELETE FROM `npc_trainer` WHERE `entry`= 3353;
DELETE FROM `npc_trainer` WHERE `entry`= 3352;
DELETE FROM `npc_trainer` WHERE `entry`= 3344;
DELETE FROM `npc_trainer` WHERE `entry`= 3328;
DELETE FROM `npc_trainer` WHERE `entry`= 3326;
DELETE FROM `npc_trainer` WHERE `entry`= 3173;
DELETE FROM `npc_trainer` WHERE `entry`= 3171;
DELETE FROM `npc_trainer` WHERE `entry`= 3170;
DELETE FROM `npc_trainer` WHERE `entry`= 3169;
DELETE FROM `npc_trainer` WHERE `entry`= 3157;
DELETE FROM `npc_trainer` WHERE `entry`= 3156;
DELETE FROM `npc_trainer` WHERE `entry`= 3155;
DELETE FROM `npc_trainer` WHERE `entry`= 3154;
DELETE FROM `npc_trainer` WHERE `entry`= 3153;
DELETE FROM `npc_trainer` WHERE `entry`= 3066;
DELETE FROM `npc_trainer` WHERE `entry`= 3065;
DELETE FROM `npc_trainer` WHERE `entry`= 3064;
DELETE FROM `npc_trainer` WHERE `entry`= 3063;
DELETE FROM `npc_trainer` WHERE `entry`= 3062;
DELETE FROM `npc_trainer` WHERE `entry`= 3061;
DELETE FROM `npc_trainer` WHERE `entry`= 3060;
DELETE FROM `npc_trainer` WHERE `entry`= 3059;
DELETE FROM `npc_trainer` WHERE `entry`= 3049;
DELETE FROM `npc_trainer` WHERE `entry`= 3048;
DELETE FROM `npc_trainer` WHERE `entry`= 3047;
DELETE FROM `npc_trainer` WHERE `entry`= 3045;
DELETE FROM `npc_trainer` WHERE `entry`= 3042;
DELETE FROM `npc_trainer` WHERE `entry`= 3041;
DELETE FROM `npc_trainer` WHERE `entry`= 3039;
DELETE FROM `npc_trainer` WHERE `entry`= 3038;
DELETE FROM `npc_trainer` WHERE `entry`= 3034;
DELETE FROM `npc_trainer` WHERE `entry`= 3033;
DELETE FROM `npc_trainer` WHERE `entry`= 3032;
DELETE FROM `npc_trainer` WHERE `entry`= 3031;
DELETE FROM `npc_trainer` WHERE `entry`= 3030;
DELETE FROM `npc_trainer` WHERE `entry`= 2131;
DELETE FROM `npc_trainer` WHERE `entry`= 2130;
DELETE FROM `npc_trainer` WHERE `entry`= 2129;
DELETE FROM `npc_trainer` WHERE `entry`= 2128;
DELETE FROM `npc_trainer` WHERE `entry`= 2126;
DELETE FROM `npc_trainer` WHERE `entry`= 2124;
DELETE FROM `npc_trainer` WHERE `entry`= 2123;
DELETE FROM `npc_trainer` WHERE `entry`= 2122;
DELETE FROM `npc_trainer` WHERE `entry`= 2119;
DELETE FROM `npc_trainer` WHERE `entry`= 1234;
DELETE FROM `npc_trainer` WHERE `entry`= 1232;
DELETE FROM `npc_trainer` WHERE `entry`= 1231;
DELETE FROM `npc_trainer` WHERE `entry`= 1229;
DELETE FROM `npc_trainer` WHERE `entry`= 1228;
DELETE FROM `npc_trainer` WHERE `entry`= 1226;
DELETE FROM `npc_trainer` WHERE `entry`= 986;
DELETE FROM `npc_trainer` WHERE `entry`= 944;
DELETE FROM `npc_trainer` WHERE `entry`= 928;
DELETE FROM `npc_trainer` WHERE `entry`= 927;
DELETE FROM `npc_trainer` WHERE `entry`= 926;
DELETE FROM `npc_trainer` WHERE `entry`= 925;
DELETE FROM `npc_trainer` WHERE `entry`= 918;
DELETE FROM `npc_trainer` WHERE `entry`= 917;
DELETE FROM `npc_trainer` WHERE `entry`= 916;
DELETE FROM `npc_trainer` WHERE `entry`= 915;
DELETE FROM `npc_trainer` WHERE `entry`= 914;
DELETE FROM `npc_trainer` WHERE `entry`= 913;
DELETE FROM `npc_trainer` WHERE `entry`= 912;
DELETE FROM `npc_trainer` WHERE `entry`= 911;
DELETE FROM `npc_trainer` WHERE `entry`= 895;
DELETE FROM `npc_trainer` WHERE `entry`= 837;
DELETE FROM `npc_trainer` WHERE `entry`= 461;
DELETE FROM `npc_trainer` WHERE `entry`= 460;
DELETE FROM `npc_trainer` WHERE `entry`= 459;
DELETE FROM `npc_trainer` WHERE `entry`= 377;
DELETE FROM `npc_trainer` WHERE `entry`= 376;
DELETE FROM `npc_trainer` WHERE `entry`= 375;
DELETE FROM `npc_trainer` WHERE `entry`= 331;
DELETE FROM `npc_trainer` WHERE `entry`= 328;
DELETE FROM `npc_trainer` WHERE `entry`= 198;

UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 63335;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 63332;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 63331;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 63327;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 63310;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 63296;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 63285;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 63272;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 63258;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 63238;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 62321;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 52319;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 52292;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 51998;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 51640;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 51639;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 51637;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 50690;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 49749;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 47246;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 47233;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 45347;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 45339;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 45337;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 45306;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 45137;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 44978;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 44735;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 44726;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 44725;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 44469;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 44468;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 44465;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 44464;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 44461;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 44459;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 44455;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 44395;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 44247;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 43870;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 43795;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 43455;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 43278;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 43010;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 43009;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 43006;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 42618;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 42366;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 42331;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 42324;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 42323;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 39214;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 39206;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 39116;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 39100;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 38911;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 38799;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 38798;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 38797;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 38796;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 38795;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 38793;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 38517;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 38467;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 38466;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 38247;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 38246;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 38245;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 38244;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 38243;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 38122;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 38037;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 37737;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 37724;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 37121;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 37115;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 36652;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 36651;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 36632;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 36630;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 36629;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 36628;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 36521;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 35874;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 35873;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 35872;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 35871;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 35870;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 35869;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 35839;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 35786;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 35758;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 35281;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 34697;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 34696;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 34695;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 34693;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 34692;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 34689;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 34673;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 31084;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 29156;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 28474;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 28472;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 28471;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 23566;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 23128;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 23127;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 20407;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 20406;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 17844;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 17520;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 17519;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 17514;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 17513;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 17511;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 17509;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 17505;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 17483;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 17482;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 17481;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 17480;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 17219;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 17212;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 17204;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 17122;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 17120;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 17110;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 17089;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 16771;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 16761;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 16756;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 16749;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 16738;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 16721;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 16685;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 16684;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 16681;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 16674;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 16673;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 16672;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 16661;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 16659;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 16658;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 16655;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 16653;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 16652;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 16651;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 16648;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 16647;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 16646;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 16503;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 16502;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 16501;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 16500;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 16499;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 16276;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 16275;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 15513;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 15285;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 15284;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 15283;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 15280;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 15279;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 13417;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 13283;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 12042;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 11406;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 11401;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 11397;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 9465;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 8664;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 8142;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 7315;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 7312;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 7311;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 6251;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 6018;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 6014;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 5994;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 5958;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 5885;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 5884;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 5883;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 5882;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 5880;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 5517;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 5516;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 5515;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 5505;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 5504;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 5498;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 5497;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 5489;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 5480;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 5479;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 5173;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 5172;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 5167;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 5165;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 5149;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 5147;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 5146;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 5145;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 5144;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 5116;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 5115;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 5113;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 4606;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 4595;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 4593;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 4584;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 4583;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 4568;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 4567;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 4566;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 4563;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 4218;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 4214;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 4205;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 4163;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 4146;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 4138;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 4090;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 4087;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 3707;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 3706;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 3602;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 3601;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 3600;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 3599;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 3598;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 3597;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 3596;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 3595;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 3594;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 3593;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 3408;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 3407;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 3406;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 3401;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 3354;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 3353;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 3352;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 3344;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 3328;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 3326;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 3173;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 3171;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 3170;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 3169;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 3157;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 3156;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 3155;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 3154;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 3153;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 3066;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 3065;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 3064;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 3063;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 3062;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 3061;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 3060;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 3059;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 3049;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 3048;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 3047;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 3045;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 3042;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 3041;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 3039;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 3038;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 3034;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 3033;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 3032;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 3031;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 3030;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 2131;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 2130;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 2129;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 2128;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 2126;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 2124;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 2123;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 2122;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 2119;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 1234;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 1232;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 1231;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 1229;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 1228;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 1226;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 986;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 944;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 928;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 927;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 926;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 925;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 918;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 917;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 916;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 915;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 914;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 913;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 912;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 911;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 895;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 837;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 461;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 460;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 459;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 377;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 376;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 375;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 331;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 328;
UPDATE `creature_template` SET `npcflag`= 3 WHERE `entry`= 198;
