-- Min/Max Damage Floors
UPDATE creature_template SET mindmg=49693, maxdmg=84480 WHERE minlevel=95;
UPDATE creature_template SET mindmg=38931, maxdmg=66185 WHERE minlevel=94;
UPDATE creature_template SET mindmg=30500, maxdmg=51852 WHERE minlevel=93;
UPDATE creature_template SET mindmg=23895, maxdmg=40623 WHERE minlevel=92;
UPDATE creature_template SET mindmg=18720, maxdmg=31825 WHERE minlevel=91;
UPDATE creature_template SET mindmg=14666, maxdmg=24933 WHERE minlevel=90;
UPDATE creature_template SET mindmg=11490, maxdmg=19534 WHERE minlevel=89;
UPDATE creature_template SET mindmg=9001, maxdmg=15302 WHERE minlevel=88;
UPDATE creature_template SET mindmg=7052, maxdmg=11989 WHERE minlevel=87;
UPDATE creature_template SET mindmg=5525, maxdmg=9393 WHERE minlevel=86;
UPDATE creature_template SET mindmg=4328, maxdmg=7359 WHERE minlevel=85;
UPDATE creature_template SET mindmg=3097, maxdmg=5266 WHERE minlevel=84;
UPDATE creature_template SET mindmg=2216, maxdmg=3768 WHERE minlevel=83;
UPDATE creature_template SET mindmg=1586, maxdmg=2697 WHERE minlevel=82;
UPDATE creature_template SET mindmg=1134, maxdmg=1930 WHERE minlevel=81;
UPDATE creature_template SET mindmg=812, maxdmg=1381 WHERE minlevel=80;
UPDATE creature_template SET mindmg=764, maxdmg=1300 WHERE minlevel=79;
UPDATE creature_template SET mindmg=719, maxdmg=1224 WHERE minlevel=78;
UPDATE creature_template SET mindmg=677, maxdmg=1153 WHERE minlevel=77;
UPDATE creature_template SET mindmg=638, maxdmg=1085 WHERE minlevel=76;
UPDATE creature_template SET mindmg=600, maxdmg=1022 WHERE minlevel=75;
UPDATE creature_template SET mindmg=565, maxdmg=962 WHERE minlevel=74;
UPDATE creature_template SET mindmg=532, maxdmg=906 WHERE minlevel=73;
UPDATE creature_template SET mindmg=501, maxdmg=853 WHERE minlevel=72;
UPDATE creature_template SET mindmg=472, maxdmg=803 WHERE minlevel=71;
UPDATE creature_template SET mindmg=444, maxdmg=756 WHERE minlevel=70;
UPDATE creature_template SET mindmg=438, maxdmg=745 WHERE minlevel=69;
UPDATE creature_template SET mindmg=431, maxdmg=734 WHERE minlevel=68;
UPDATE creature_template SET mindmg=425, maxdmg=724 WHERE minlevel=67;
UPDATE creature_template SET mindmg=418, maxdmg=713 WHERE minlevel=66;
UPDATE creature_template SET mindmg=412, maxdmg=702 WHERE minlevel=65;
UPDATE creature_template SET mindmg=406, maxdmg=691 WHERE minlevel=64;
UPDATE creature_template SET mindmg=399, maxdmg=680 WHERE minlevel=63;
UPDATE creature_template SET mindmg=393, maxdmg=669 WHERE minlevel=62;
UPDATE creature_template SET mindmg=387, maxdmg=659 WHERE minlevel=61;
UPDATE creature_template SET mindmg=380, maxdmg=648 WHERE minlevel=60;
UPDATE creature_template SET mindmg=374, maxdmg=637 WHERE minlevel=59;
UPDATE creature_template SET mindmg=368, maxdmg=626 WHERE minlevel=58;
UPDATE creature_template SET mindmg=361, maxdmg=615 WHERE minlevel=57;
UPDATE creature_template SET mindmg=346, maxdmg=589 WHERE minlevel=56;
UPDATE creature_template SET mindmg=330, maxdmg=563 WHERE minlevel=55;
UPDATE creature_template SET mindmg=316, maxdmg=538 WHERE minlevel=54;
UPDATE creature_template SET mindmg=302, maxdmg=514 WHERE minlevel=53;
UPDATE creature_template SET mindmg=288, maxdmg=491 WHERE minlevel=52;
UPDATE creature_template SET mindmg=275, maxdmg=467 WHERE minlevel=51;
UPDATE creature_template SET mindmg=262, maxdmg=447 WHERE minlevel=50;
UPDATE creature_template SET mindmg=250, maxdmg=427 WHERE minlevel=49;
UPDATE creature_template SET mindmg=242, maxdmg=412 WHERE minlevel=48;
UPDATE creature_template SET mindmg=232, maxdmg=396 WHERE minlevel=47;
UPDATE creature_template SET mindmg=223, maxdmg=380 WHERE minlevel=46;
UPDATE creature_template SET mindmg=213, maxdmg=364 WHERE minlevel=45;
UPDATE creature_template SET mindmg=204, maxdmg=349 WHERE minlevel=44;
UPDATE creature_template SET mindmg=196, maxdmg=334 WHERE minlevel=43;
UPDATE creature_template SET mindmg=187, maxdmg=319 WHERE minlevel=42;
UPDATE creature_template SET mindmg=179, maxdmg=305 WHERE minlevel=41;
UPDATE creature_template SET mindmg=171, maxdmg=292 WHERE minlevel=40;
UPDATE creature_template SET mindmg=163, maxdmg=278 WHERE minlevel=39;
UPDATE creature_template SET mindmg=155, maxdmg=265 WHERE minlevel=38;
UPDATE creature_template SET mindmg=148, maxdmg=253 WHERE minlevel=37;
UPDATE creature_template SET mindmg=141, maxdmg=241 WHERE minlevel=36;
UPDATE creature_template SET mindmg=134, maxdmg=229 WHERE minlevel=35;
UPDATE creature_template SET mindmg=128, maxdmg=218 WHERE minlevel=34;
UPDATE creature_template SET mindmg=121, maxdmg=208 WHERE minlevel=33;
UPDATE creature_template SET mindmg=115, maxdmg=197 WHERE minlevel=32;
UPDATE creature_template SET mindmg=109, maxdmg=187 WHERE minlevel=31;
UPDATE creature_template SET mindmg=104, maxdmg=178 WHERE minlevel=30;
UPDATE creature_template SET mindmg=96, maxdmg=165 WHERE minlevel=29;
UPDATE creature_template SET mindmg=92, maxdmg=157 WHERE minlevel=28;
UPDATE creature_template SET mindmg=87, maxdmg=150 WHERE minlevel=27;
UPDATE creature_template SET mindmg=81, maxdmg=140 WHERE minlevel=26;
UPDATE creature_template SET mindmg=77, maxdmg=132 WHERE minlevel=25;
UPDATE creature_template SET mindmg=73, maxdmg=126 WHERE minlevel=24;
UPDATE creature_template SET mindmg=71, maxdmg=121 WHERE minlevel=23;
UPDATE creature_template SET mindmg=67, maxdmg=115 WHERE minlevel=22;
UPDATE creature_template SET mindmg=66, maxdmg=113 WHERE minlevel=21;
UPDATE creature_template SET mindmg=62, maxdmg=107 WHERE minlevel=20;
UPDATE creature_template SET mindmg=58, maxdmg=101 WHERE minlevel=19;
UPDATE creature_template SET mindmg=57, maxdmg=99 WHERE minlevel=18;
UPDATE creature_template SET mindmg=54, maxdmg=92 WHERE minlevel=17;
UPDATE creature_template SET mindmg=50, maxdmg=86 WHERE minlevel=16;
UPDATE creature_template SET mindmg=49, maxdmg=84 WHERE minlevel=15;
UPDATE creature_template SET mindmg=45, maxdmg=78 WHERE minlevel=14;
UPDATE creature_template SET mindmg=41, maxdmg=72 WHERE minlevel=13;
UPDATE creature_template SET mindmg=40, maxdmg=70 WHERE minlevel=12;
UPDATE creature_template SET mindmg=37, maxdmg=63 WHERE minlevel=11;
UPDATE creature_template SET mindmg=33, maxdmg=57 WHERE minlevel=10;
UPDATE creature_template SET mindmg=32, maxdmg=55 WHERE minlevel=9;
UPDATE creature_template SET mindmg=28, maxdmg=49 WHERE minlevel=8;
UPDATE creature_template SET mindmg=24, maxdmg=43 WHERE minlevel=7;
UPDATE creature_template SET mindmg=23, maxdmg=41 WHERE minlevel=6;
UPDATE creature_template SET mindmg=20, maxdmg=34 WHERE minlevel=5;
UPDATE creature_template SET mindmg=16, maxdmg=28 WHERE minlevel=4;
UPDATE creature_template SET mindmg=14, maxdmg=24 WHERE minlevel=3;
UPDATE creature_template SET mindmg=11, maxdmg=20 WHERE minlevel=2;
UPDATE creature_template SET mindmg=8, maxdmg=15 WHERE minlevel=1;

-- Max Damage Ceiling
UPDATE creature_template SET maxdmg=84480 WHERE maxlevel=95;
UPDATE creature_template SET maxdmg=66185 WHERE maxlevel=94;
UPDATE creature_template SET maxdmg=51852 WHERE maxlevel=93;
UPDATE creature_template SET maxdmg=40623 WHERE maxlevel=92;
UPDATE creature_template SET maxdmg=31825 WHERE maxlevel=91;
UPDATE creature_template SET maxdmg=24933 WHERE maxlevel=90;
UPDATE creature_template SET maxdmg=19534 WHERE maxlevel=89;
UPDATE creature_template SET maxdmg=15302 WHERE maxlevel=88;
UPDATE creature_template SET maxdmg=11989 WHERE maxlevel=87;
UPDATE creature_template SET maxdmg=9393 WHERE maxlevel=86;
UPDATE creature_template SET maxdmg=7359 WHERE maxlevel=85;
UPDATE creature_template SET maxdmg=5266 WHERE maxlevel=84;
UPDATE creature_template SET maxdmg=3768 WHERE maxlevel=83;
UPDATE creature_template SET maxdmg=2697 WHERE maxlevel=82;
UPDATE creature_template SET maxdmg=1930 WHERE maxlevel=81;
UPDATE creature_template SET maxdmg=1381 WHERE maxlevel=80;
UPDATE creature_template SET maxdmg=1300 WHERE maxlevel=79;
UPDATE creature_template SET maxdmg=1224 WHERE maxlevel=78;
UPDATE creature_template SET maxdmg=1153 WHERE maxlevel=77;
UPDATE creature_template SET maxdmg=1085 WHERE maxlevel=76;
UPDATE creature_template SET maxdmg=1022 WHERE maxlevel=75;
UPDATE creature_template SET maxdmg=962 WHERE maxlevel=74;
UPDATE creature_template SET maxdmg=906 WHERE maxlevel=73;
UPDATE creature_template SET maxdmg=853 WHERE maxlevel=72;
UPDATE creature_template SET maxdmg=803 WHERE maxlevel=71;
UPDATE creature_template SET maxdmg=756 WHERE maxlevel=70;
UPDATE creature_template SET maxdmg=745 WHERE maxlevel=69;
UPDATE creature_template SET maxdmg=734 WHERE maxlevel=68;
UPDATE creature_template SET maxdmg=724 WHERE maxlevel=67;
UPDATE creature_template SET maxdmg=713 WHERE maxlevel=66;
UPDATE creature_template SET maxdmg=702 WHERE maxlevel=65;
UPDATE creature_template SET maxdmg=691 WHERE maxlevel=64;
UPDATE creature_template SET maxdmg=680 WHERE maxlevel=63;
UPDATE creature_template SET maxdmg=669 WHERE maxlevel=62;
UPDATE creature_template SET maxdmg=659 WHERE maxlevel=61;
UPDATE creature_template SET maxdmg=648 WHERE maxlevel=60;
UPDATE creature_template SET maxdmg=637 WHERE maxlevel=59;
UPDATE creature_template SET maxdmg=626 WHERE maxlevel=58;
UPDATE creature_template SET maxdmg=615 WHERE maxlevel=57;
UPDATE creature_template SET maxdmg=589 WHERE maxlevel=56;
UPDATE creature_template SET maxdmg=563 WHERE maxlevel=55;
UPDATE creature_template SET maxdmg=538 WHERE maxlevel=54;
UPDATE creature_template SET maxdmg=514 WHERE maxlevel=53;
UPDATE creature_template SET maxdmg=491 WHERE maxlevel=52;
UPDATE creature_template SET maxdmg=467 WHERE maxlevel=51;
UPDATE creature_template SET maxdmg=447 WHERE maxlevel=50;
UPDATE creature_template SET maxdmg=427 WHERE maxlevel=49;
UPDATE creature_template SET maxdmg=412 WHERE maxlevel=48;
UPDATE creature_template SET maxdmg=396 WHERE maxlevel=47;
UPDATE creature_template SET maxdmg=380 WHERE maxlevel=46;
UPDATE creature_template SET maxdmg=364 WHERE maxlevel=45;
UPDATE creature_template SET maxdmg=349 WHERE maxlevel=44;
UPDATE creature_template SET maxdmg=334 WHERE maxlevel=43;
UPDATE creature_template SET maxdmg=319 WHERE maxlevel=42;
UPDATE creature_template SET maxdmg=305 WHERE maxlevel=41;
UPDATE creature_template SET maxdmg=292 WHERE maxlevel=40;
UPDATE creature_template SET maxdmg=278 WHERE maxlevel=39;
UPDATE creature_template SET maxdmg=265 WHERE maxlevel=38;
UPDATE creature_template SET maxdmg=253 WHERE maxlevel=37;
UPDATE creature_template SET maxdmg=241 WHERE maxlevel=36;
UPDATE creature_template SET maxdmg=229 WHERE maxlevel=35;
UPDATE creature_template SET maxdmg=218 WHERE maxlevel=34;
UPDATE creature_template SET maxdmg=208 WHERE maxlevel=33;
UPDATE creature_template SET maxdmg=197 WHERE maxlevel=32;
UPDATE creature_template SET maxdmg=187 WHERE maxlevel=31;
UPDATE creature_template SET maxdmg=178 WHERE maxlevel=30;
UPDATE creature_template SET maxdmg=165 WHERE maxlevel=29;
UPDATE creature_template SET maxdmg=157 WHERE maxlevel=28;
UPDATE creature_template SET maxdmg=150 WHERE maxlevel=27;
UPDATE creature_template SET maxdmg=140 WHERE maxlevel=26;
UPDATE creature_template SET maxdmg=132 WHERE maxlevel=25;
UPDATE creature_template SET maxdmg=126 WHERE maxlevel=24;
UPDATE creature_template SET maxdmg=121 WHERE maxlevel=23;
UPDATE creature_template SET maxdmg=115 WHERE maxlevel=22;
UPDATE creature_template SET maxdmg=113 WHERE maxlevel=21;
UPDATE creature_template SET maxdmg=107 WHERE maxlevel=20;
UPDATE creature_template SET maxdmg=101 WHERE maxlevel=19;
UPDATE creature_template SET maxdmg=99 WHERE maxlevel=18;
UPDATE creature_template SET maxdmg=92 WHERE maxlevel=17;
UPDATE creature_template SET maxdmg=86 WHERE maxlevel=16;
UPDATE creature_template SET maxdmg=84 WHERE maxlevel=15;
UPDATE creature_template SET maxdmg=78 WHERE maxlevel=14;
UPDATE creature_template SET maxdmg=72 WHERE maxlevel=13;
UPDATE creature_template SET maxdmg=70 WHERE maxlevel=12;
UPDATE creature_template SET maxdmg=63 WHERE maxlevel=11;
UPDATE creature_template SET maxdmg=57 WHERE maxlevel=10;
UPDATE creature_template SET maxdmg=55 WHERE maxlevel=9;
UPDATE creature_template SET maxdmg=49 WHERE maxlevel=8;
UPDATE creature_template SET maxdmg=43 WHERE maxlevel=7;
UPDATE creature_template SET maxdmg=41 WHERE maxlevel=6;
UPDATE creature_template SET maxdmg=34 WHERE maxlevel=5;
UPDATE creature_template SET maxdmg=28 WHERE maxlevel=4;
UPDATE creature_template SET maxdmg=24 WHERE maxlevel=3;
UPDATE creature_template SET maxdmg=20 WHERE maxlevel=2;
UPDATE creature_template SET maxdmg=15 WHERE maxlevel=1;