UPDATE `gameobject_template` SET `name`='Sniper Rifle' WHERE `entry`=209621;
UPDATE `gameobject_template` SET `name`='Firework Launcher' WHERE `entry`=209672;
UPDATE `gameobject_template` SET `name`='Northeast Oubliette Shackle' WHERE `entry`=210527;
UPDATE `gameobject_template` SET `name`='Northwest Oubliette Shackle' WHERE `entry`=210533;
UPDATE `gameobject_template` SET `name`='Southwest Oubliette Shackle' WHERE `entry`=210535;
UPDATE `gameobject_template` SET `name`='Hozen in the Mist' WHERE `entry`=211415;
UPDATE `gameobject_template` SET `name`='Alchemy Scroll' WHERE `entry`=211424;
UPDATE `gameobject_template` SET `name`='Hozen in the Mist' WHERE `entry`=212527;
UPDATE `gameobject_template` SET `name`='Fish Tales' WHERE `entry`=212528;
UPDATE `gameobject_template` SET `name`='The Dark Heart of the Mogu' WHERE `entry`=212529;
UPDATE `gameobject_template` SET `name`='What Is Worth Fighting For' WHERE `entry`=212531;
UPDATE `gameobject_template` SET `name`='The Song of the Yaungol' WHERE `entry`=212534;
UPDATE `gameobject_template` SET `name`='Pheromone Mine' WHERE `entry`=214341;
UPDATE `gameobject_template` SET `name`='Deactivate First Spirit Wall' WHERE `entry`=214474;
UPDATE `gameobject_template` SET `name`='Deactivate Second Spirit Wall' WHERE `entry`=214476;
UPDATE `gameobject_template` SET `name`='Deactivate Final Spirit Wall' WHERE `entry`=214477;
UPDATE `gameobject_template` SET `name`='Sprinkler' WHERE `entry`=215135;
UPDATE `gameobject_template` SET `name`='Pest Repeller' WHERE `entry`=215162;
UPDATE `gameobject_template` SET `name`='Halberd of the Unscathed' WHERE `entry`=215872;
UPDATE `gameobject_template` SET `name`='Candy Bucket' WHERE `entry`=215874;
UPDATE `gameobject_template` SET `name`='Candy Bucket' WHERE `entry`=215875;
UPDATE `gameobject_template` SET `name`='Candy Bucket' WHERE `entry`=215876;
UPDATE `gameobject_template` SET `name`='Candy Bucket' WHERE `entry`=215877;
UPDATE `gameobject_template` SET `name`='Candy Bucket' WHERE `entry`=215879;
UPDATE `gameobject_template` SET `name`='Candy Bucket' WHERE `entry`=215880;
UPDATE `gameobject_template` SET `name`='Candy Bucket' WHERE `entry`=215881;
UPDATE `gameobject_template` SET `name`='Candy Bucket' WHERE `entry`=215884;
UPDATE `gameobject_template` SET `name`='Candy Bucket' WHERE `entry`=215886;
UPDATE `gameobject_template` SET `name`='Candy Bucket' WHERE `entry`=215889;
UPDATE `gameobject_template` SET `name`='Candy Bucket' WHERE `entry`=215891;
UPDATE `gameobject_template` SET `name`='Candy Bucket' WHERE `entry`=215892;
UPDATE `gameobject_template` SET `name`='Candy Bucket' WHERE `entry`=215894;
UPDATE `gameobject_template` SET `name`='Candy Bucket' WHERE `entry`=215895;
UPDATE `gameobject_template` SET `name`='Candy Bucket' WHERE `entry`=215897;
UPDATE `gameobject_template` SET `name`='Candy Bucket' WHERE `entry`=215898;
UPDATE `gameobject_template` SET `name`='Candy Bucket' WHERE `entry`=215899;
UPDATE `gameobject_template` SET `name`='Candy Bucket' WHERE `entry`=215900;
UPDATE `gameobject_template` SET `name`='Candy Bucket' WHERE `entry`=215902;
UPDATE `gameobject_template` SET `name`='Candy Bucket' WHERE `entry`=215903;
UPDATE `gameobject_template` SET `name`='Candy Bucket' WHERE `entry`=215904;
UPDATE `gameobject_template` SET `name`='Candy Bucket' WHERE `entry`=215905;
UPDATE `gameobject_template` SET `name`='Candy Bucket' WHERE `entry`=215906;
UPDATE `gameobject_template` SET `name`='Candy Bucket' WHERE `entry`=215907;
UPDATE `gameobject_template` SET `name`='Candy Bucket' WHERE `entry`=215908;
UPDATE `gameobject_template` SET `name`='Candy Bucket' WHERE `entry`=215914;
UPDATE `gameobject_template` SET `name`='Candy Bucket' WHERE `entry`=215915;
UPDATE `gameobject_template` SET `name`='Powder Magazine' WHERE `entry`=216231;
UPDATE `gameobject_template` SET `name`='Untamed Amber' WHERE `entry`=216360;
UPDATE `gameobject_template` SET `name`='A Keg of Metal Brew' WHERE `entry`=216362;
UPDATE `gameobject_template` SET `name`='Mallet Head' WHERE `entry`=216421;
UPDATE `gameobject_template` SET `name`='Midsummer Bonfire' WHERE `entry`=217845;
UPDATE `gameobject_template` SET `name`='Midsummer Bonfire' WHERE `entry`=217846;
UPDATE `gameobject_template` SET `name`='Midsummer Bonfire' WHERE `entry`=217847;
UPDATE `gameobject_template` SET `name`='Midsummer Bonfire' WHERE `entry`=217848;
UPDATE `gameobject_template` SET `name`='Midsummer Bonfire' WHERE `entry`=217849;
UPDATE `gameobject_template` SET `name`='Midsummer Bonfire' WHERE `entry`=217850;
UPDATE `gameobject_template` SET `name`='Alliance Bonfire' WHERE `entry`=217851;
UPDATE `gameobject_template` SET `name`='Horde Bonfire' WHERE `entry`=217852;
UPDATE `gameobject_template` SET `name`='Head of the Chamberlain' WHERE `entry`=218072;
UPDATE `gameobject_template` SET `name`='Base of the Chamberlain' WHERE `entry`=218077;
UPDATE `gameobject_template` SET `name`='The Zandalari Prophecy' WHERE `entry`=218572;
UPDATE `gameobject_template` SET `name`='Rumbles of Thunder' WHERE `entry`=218573;
UPDATE `gameobject_template` SET `name`='Gods and Monsters' WHERE `entry`=218574;
UPDATE `gameobject_template` SET `name`='Cache of the Broodmother' WHERE `entry`=208044;
UPDATE `gameobject_template` SET `name`='Cache of the Broodmother' WHERE `entry`=208045;
UPDATE `gameobject_template` SET `name`='Hard Tearwood Reed' WHERE `entry`=209507;
UPDATE `gameobject_template` SET `name`='Scroll of Sorrow' WHERE `entry`=209582;
UPDATE `gameobject_template` SET `name`='Ancient Clam' WHERE `entry`=209584;
UPDATE `gameobject_template` SET `name`='Uprooted Turnip' WHERE `entry`=209639;
UPDATE `gameobject_template` SET `name`='Uprooted Turnip' WHERE `entry`=209640;
UPDATE `gameobject_template` SET `name`='Stolen Carrot' WHERE `entry`=209641;
UPDATE `gameobject_template` SET `name`='Pilfered Pumpkin' WHERE `entry`=209642;
UPDATE `gameobject_template` SET `name`='Pilfered Pumpkin' WHERE `entry`=209643;
UPDATE `gameobject_template` SET `name`='Pilfered Pumpkin' WHERE `entry`=209644;
UPDATE `gameobject_template` SET `name`='Pilfered Pumpkin' WHERE `entry`=209645;
UPDATE `gameobject_template` SET `name`='Discarded Wood Planks' WHERE `entry`=209646;
UPDATE `gameobject_template` SET `name`='Abandoned Stone Blocks' WHERE `entry`=209665;
UPDATE `gameobject_template` SET `name`='Stolen Fireworks' WHERE `entry`=209669;
UPDATE `gameobject_template` SET `name`='Kun-pai Ritual Charm' WHERE `entry`=209671;
UPDATE `gameobject_template` SET `name`='Kun-pai Ritual Charm' WHERE `entry`=209774;
UPDATE `gameobject_template` SET `name`='Explosive Bundle' WHERE `entry`=209792;
UPDATE `gameobject_template` SET `name`='Alliance Medical Crate' WHERE `entry`=209793;
UPDATE `gameobject_template` SET `name`='Gold Coins' WHERE `entry`=210894;
UPDATE `gameobject_template` SET `name`='Boat Planks' WHERE `entry`=210961;
UPDATE `gameobject_template` SET `name`='Striped Melon' WHERE `entry`=210979;
UPDATE `gameobject_template` SET `name`='Striped Melon' WHERE `entry`=210980;
UPDATE `gameobject_template` SET `name`='Revelite Crystal' WHERE `entry`=211306;
UPDATE `gameobject_template` SET `name`='Broken Bamboo Stalk' WHERE `entry`=211394;
UPDATE `gameobject_template` SET `name`='Battle Axe of the Thunder King' WHERE `entry`=211396;
UPDATE `gameobject_template` SET `name`='Broken Bamboo Stalk' WHERE `entry`=211397;
UPDATE `gameobject_template` SET `name`='Broken Bamboo Stalk' WHERE `entry`=211398;
UPDATE `gameobject_template` SET `name`='Broken Bamboo Stalk' WHERE `entry`=211399;
UPDATE `gameobject_template` SET `name`='Broken Bamboo Stalk' WHERE `entry`=211400;
UPDATE `gameobject_template` SET `name`='Broken Bamboo Stalk' WHERE `entry`=211401;
UPDATE `gameobject_template` SET `name`='Yaungol Oil Barrel' WHERE `entry`=212003;
UPDATE `gameobject_template` SET `name`='Fresh Dirt' WHERE `entry`=212742;
UPDATE `gameobject_template` SET `name`='Whitepetal Reeds' WHERE `entry`=212744;
UPDATE `gameobject_template` SET `name`='Ancient Tome' WHERE `entry`=212968;
UPDATE `gameobject_template` SET `name`='Box of Fancy Stuff' WHERE `entry`=213075;
UPDATE `gameobject_template` SET `name`='Box of Fancy Stuff' WHERE `entry`=213076;
UPDATE `gameobject_template` SET `name`='Treasure Urn' WHERE `entry`=213290;
UPDATE `gameobject_template` SET `name`='Amber Pot' WHERE `entry`=213319;
UPDATE `gameobject_template` SET `name`='Stolen Mistfall Keg' WHERE `entry`=213365;
UPDATE `gameobject_template` SET `name`='Mistfall Water Bucket' WHERE `entry`=213463;
UPDATE `gameobject_template` SET `name`='Tablet of Ren Yun' WHERE `entry`=213765;
UPDATE `gameobject_template` SET `name`='Hozen Warrior Spear' WHERE `entry`=213768;
UPDATE `gameobject_template` SET `name`='Hozen Treasure Cache' WHERE `entry`=213769;
UPDATE `gameobject_template` SET `name`='Yaungol Fire Carrier' WHERE `entry`=213960;
UPDATE `gameobject_template` SET `name`='Amber Encased Necklace' WHERE `entry`=213966;
UPDATE `gameobject_template` SET `name`='Blade of the Prime' WHERE `entry`=213967;
UPDATE `gameobject_template` SET `name`='Bloodsoaked Chitin Fragment' WHERE `entry`=213970;
UPDATE `gameobject_template` SET `name`='Bag of Wu Kao Supplies' WHERE `entry`=214175;
UPDATE `gameobject_template` SET `name`='Blade of the Anointed' WHERE `entry`=214284;
UPDATE `gameobject_template` SET `name`='Blade of the Anointed' WHERE `entry`=214296;
UPDATE `gameobject_template` SET `name`='Cache of Pure Energy' WHERE `entry`=214383;
UPDATE `gameobject_template` SET `name`='Dai-Lo Recess Mallet' WHERE `entry`=214406;
UPDATE `gameobject_template` SET `name`='Barrel of Banana Infused Rum' WHERE `entry`=214439;
UPDATE `gameobject_template` SET `name`='Legacy of the Clan Leaders' WHERE `entry`=214520;
UPDATE `gameobject_template` SET `name`='Legacy of the Clan Leaders' WHERE `entry`=214521;
UPDATE `gameobject_template` SET `name`='Ancient Mogu Treasure' WHERE `entry`=214795;
UPDATE `gameobject_template` SET `name`='Ancient Mogu Chest' WHERE `entry`=214824;
UPDATE `gameobject_template` SET `name`='Hatchling Poop' WHERE `entry`=214862;
UPDATE `gameobject_template` SET `name`='Hatchling Poop' WHERE `entry`=214863;
UPDATE `gameobject_template` SET `name`='Requisitioned Firework Launcher' WHERE `entry`=214962;
UPDATE `gameobject_template` SET `name`='Gold Coins' WHERE `entry`=214985;
UPDATE `gameobject_template` SET `name`='Chunk of Stone' WHERE `entry`=216160;
UPDATE `gameobject_template` SET `name`='Krasari Iron' WHERE `entry`=216610;
UPDATE `gameobject_template` SET `name`='Jungle Hops' WHERE `entry`=216620;
UPDATE `gameobject_template` SET `name`='Weathered Journal' WHERE `entry`=216664;
UPDATE `gameobject_template` SET `name`='Energized Iron Ore Chunk' WHERE `entry`=216716;
UPDATE `gameobject_template` SET `name`='Rusty Valve' WHERE `entry`=216751;
UPDATE `gameobject_template` SET `name`='Ritual Artifact' WHERE `entry`=218049;
UPDATE `gameobject_template` SET `name`='Ritual Artifact' WHERE `entry`=218050;
UPDATE `gameobject_template` SET `name`='Ritual Artifact' WHERE `entry`=218052;
UPDATE `gameobject_template` SET `name`='Ritual Artifact' WHERE `entry`=218053;
UPDATE `gameobject_template` SET `name`='Loa-Infused Blade' WHERE `entry`=218055;
UPDATE `gameobject_template` SET `name`='Loa-Infused Blade' WHERE `entry`=218056;
UPDATE `gameobject_template` SET `name`='Shoulder of the Chamberlain' WHERE `entry`=218073;
UPDATE `gameobject_template` SET `name`='Staff of the Chamberlain' WHERE `entry`=218074;
UPDATE `gameobject_template` SET `name`='Hair of the Chamberlain' WHERE `entry`=218075;
UPDATE `gameobject_template` SET `name`='Torso of the Chamberlain' WHERE `entry`=218076;
UPDATE `gameobject_template` SET `name`='Heavy Explosives' WHERE `entry`=218197;
UPDATE `gameobject_template` SET `name`='Treasure Urn' WHERE `entry`=220196;
UPDATE `gameobject_template` SET `name`='Spirit Chest' WHERE `entry`=220819;
UPDATE `gameobject_template` SET `name`='Tears of the Vale' WHERE `entry`=221776;
UPDATE `gameobject_template` SET `name`='Golden Lotus' WHERE `entry`=221545;
