-- REFERENCE_LOOT_TEMPLATE
SET @REF_WORLD1     := 34380; -- Main World Reference 1 Entry
SET @REF_WORLD2     := 34381; -- Main World Reference 2 Entry

-- Grey High Entrys
SET @REF_SC         := 34382; -- Scruffy Cloth Reference Entry
SET @REF_SL         := 34383; -- Shabby Leather Reference Entry
SET @REF_IM         := 34384; -- Inferior Mail Reference Entry
SET @REF_DP         := 34385; -- Dingy Plate Reference Entry
SET @REF_GREY2      := 34386; -- Higher Grey Reference Entry
-- Green High Entrys
SET @REF_BREWC      := 34387; -- Brewer's Cloth Reference Entry
SET @REF_SWAML      := 34388; -- Swamp Leather Reference Entry
SET @REF_WILLM      := 34389; -- Snake Mail Reference Entry
SET @REF_SNOWP      := 34390; -- Miner Plate Reference Entry
SET @REF_GREEN2     := 34391; -- Higher Green Reference Entry
-- Grey Low Entrys
SET @REF_VC         := 34392; -- Vermin-Gnawed Cloth Reference Entry
SET @REF_ML         := 34393; -- Mudsoaked Leather Reference Entry
SET @REF_MM         := 34394; -- Moist Mail Reference Entry
SET @REF_SP         := 34395; -- Slipshod Plate Reference Entry

-- Vermin-Gnawed Cloth ItemIDs
SET @VC_HEAD      := 90774; -- Vermin-Gnawed Hat
SET @VC_WAIST     := 90777; -- Vermin-Gnawed Cloth Belt
SET @VC_HANDS     := 90783; -- Vermin-Gnawed Cloth Gloves
SET @VC_LEGS      := 90784; -- Vermin-Gnawed Cloth Pants
SET @VC_SHOULDERS := 90785; -- Vermin-Gnawed Cloth Shoulderpads
SET @VC_CHEST     := 90786; -- Vermin-Gnawed Cloth Vest
SET @VC_FEETS     := 90792; -- Vermin-Gnawed Cloth Boots
SET @VC_WRISTS    := 90793; -- Vermin-Gnawed Cloth Bracers

-- Mudsoaked Leather ItemIDs
SET @ML_HEAD      := 90775; -- Mudsoaked Leather Helmet
SET @ML_CHEST     := 90796; -- Mudsoaked Armor
SET @ML_SHOULDERS := 90798; -- Mudsoaked Shoulderpads
SET @ML_FEETS      := 90789; -- Mudsoaked Boots
SET @ML_WRIST     := 90790; -- Mudsoaked Bracers
SET @ML_LEGS      := 90795; -- Mudsoaked Pants
SET @ML_HANDS     := 90791; -- Mudsoaked Gloves
SET @ML_WAIST     := 90788; -- Mudsoaked Belt

-- Moist Mail ItemIDs
SET @MM_LEGS := 90778; -- Moist Mail Pants
SET @MM_WAIST := 90781; -- Moist Mail Belt
SET @MM_CHEST := 90780; -- Moist Mail Armor
SET @MM_HEAD := 90776; -- Moist Mail Circlet
SET @MM_SHOULDERS := 90779; -- Moist Mail Shoulderpads
SET @MM_FEETS := 90794; -- Moist Mail Boots
SET @MM_WRIST := 90803; -- Moist Mail Bracers
SET @MM_HANDS := 90804; -- Moist Mail Gloves

-- Slipshod Plate ItemIDs
SET @SP_HEAD := 90773; -- Slipshod Plate Helmet
SET @SP_SHOULDERS := 90802; -- Slipshod Plate Shoulderpads
SET @SP_FEETS := 90797; -- Slipshod Plate Boots
SET @SP_LEGS := 90801; -- Slipshod Plate Pants
SET @SP_WAIST := 90787; -- Slipshod Plate Belt
SET @SP_WRIST := 90782; -- Slipshod Plate Bracers
SET @SP_CHEST := 90799; -- Slipshod Plate Chestpiece
SET @SP_HANDS := 90800; -- Slipshod Plate Gloves

-- Scruffy Cloth ItemIDs
SET @SC_HEAD      := 90744; -- Scruffy Cloth Hat
SET @SC_WAIST     := 90757; -- Scruffy Cloth Belt
SET @SC_FEETS     := 90758; -- Scruffy Cloth Boots
SET @SC_WRISTS    := 90759; -- Scruffy Cloth Bracers
SET @SC_HANDS     := 90760; -- Scruffy Cloth Gloves
SET @SC_LEGS      := 90761; -- Scruffy Cloth Pants
SET @SC_SHOULDERS := 90767; -- Scruffy Cloth Shoulderpads
SET @SC_CHEST     := 90768; -- Scruffy Cloth Vest

-- Shabby Leather ItemIDs
SET @SL_HEAD      := 90742; -- Shabby Leather Helmet
SET @SL_WAIST     := 90770; -- Shabby Belt
SET @SL_FEETS     := 90762; -- Shabby Boots
SET @SL_WRISTS    := 90763; -- Shabby Bracers
SET @SL_HANDS     := 90764; -- Shabby Gloves
SET @SL_LEGS      := 90765; -- Shabby Pants
SET @SL_SHOULDERS := 90766; -- Shabby Shoulderpads
SET @SL_CHEST     := 90769; -- Shabby Armor

-- Inferior Mail ItemIDs
SET @IM_HEAD      := 90741; -- Inferior Mail Circlet
SET @IM_CHEST     := 90745; -- Inferior Mail Armor
SET @IM_WAIST     := 90746; -- Inferior Mail Belt
SET @IM_FEETS     := 90752; -- Inferior Mail Boots
SET @IM_WRISTS    := 90753; -- Inferior Mail Bracers
SET @IM_HANDS     := 90754; -- Inferior Mail Gloves
SET @IM_LEGS      := 90755; -- Inferior Mail Pants
SET @IM_SHOULDERS := 90756; -- Inferior Mail Shoulderpads

-- Dingy Plate ItemIDs
SET @DP_HEAD      := 90743; -- Dingy Plate Helmet
SET @DP_CHEST     := 90751; -- Dingy Plate Chestpiece
SET @DP_WAIST     := 90747; -- Dingy Plate Belt
SET @DP_FEETS     := 90748; -- Dingy Plate Boots
SET @DP_WRISTS    := 90749; -- Dingy Plate Bracers
SET @DP_HANDS     := 90771; -- Dingy Plate Gloves
SET @DP_LEGS      := 90772; -- Dingy Plate Pants
SET @DP_SHOULDERS := 90750; -- Dingy Plate Shoulderpads

-- Brewer's Cloth ItemIDs 403
SET @BREWC_HEAD      := 82140; -- Brewer's Cowl
SET @BREWC_WAIST     := 82139; -- Brewer's Cord
SET @BREWC_FEETS     := 82144; -- Brewer's Sandals
SET @BREWC_WRISTS    := 82146; -- Brewer's Wristwraps
SET @BREWC_HANDS     := 82141; -- Brewer's Handwraps
SET @BREWC_LEGS      := 82142; -- Brewer's Leggings
SET @BREWC_SHOULDERS := 82145; -- Brewer's Shoulderpads
SET @BREWC_CHEST     := 82143; -- Brewer's Robe

-- Swamp Leather ItemIDs 403
SET @SWAML_HEAD      := 82151; -- Swamp Hood
SET @SWAML_WAIST     := 82154; -- Swamp Waistband
SET @SWAML_FEETS     := 82148; -- Swamp Boots
SET @SWAML_WRISTS    := 82147; -- Swamp Bindings
SET @SWAML_HANDS     := 82150; -- Swamp Gloves
SET @SWAML_LEGS      := 82149; -- Swamp Britches
SET @SWAML_SHOULDERS := 82153; -- Swamp Shoulders
SET @SWAML_CHEST     := 82152; -- Swamp Jerkin

-- Willow Mail ItemIDs 403
SET @WILLM_HEAD      := 82135; -- Willow Helm
SET @WILLM_CHEST     := 82138; -- Willow Vest
SET @WILLM_WAIST     := 82131; -- Willow Belt
SET @WILLM_FEETS     := 82134; -- Willow Greaves
SET @WILLM_WRISTS    := 82132; -- Willow Bracers
SET @WILLM_HANDS     := 82133; -- Willow Gauntlets
SET @WILLM_LEGS      := 82136; -- Willow Legguards
SET @WILLM_SHOULDERS := 82137; -- Willow Spaulders

-- Snowy Plate ItemIDs 403
SET @SNOWP_HEAD      := 82180; -- Snowy Helm
SET @SNOWP_CHEST     := 82177; -- Snowy Breastplate
SET @SNOWP_WAIST     := 82179; -- Snowy Girdle
SET @SNOWP_FEETS     := 82183; -- Snowy Sabatons
SET @SNOWP_WRISTS    := 82185; -- Snowy Vambraces
SET @SNOWP_HANDS     := 82178; -- Snowy Gauntlets
SET @SNOWP_LEGS      := 82181; -- Snowy Legplates
SET @SNOWP_SHOULDERS := 82182; -- Snowy Pauldrons

DELETE FROM `reference_loot_template` WHERE `entry` IN (@REF_WORLD1, @REF_GREY1, @REF_GREEN1, @REF_VC, @REF_ML, @REF_MM, @REF_SP);
INSERT INTO `reference_loot_template` (`entry`, `item`, `ChanceOrQuestChance`, `lootmode`, `groupid`, `mincountOrRef`, `maxcount`) VALUES
(@REF_WORLD1, 1, 40, 1, 0, -@REF_GREY1, 1),
--(@REF_WORLD1, 2, 20, 1, 0, -@REF_GREEN1, 1);

INSERT INTO `reference_loot_template` (`entry`, `item`, `ChanceOrQuestChance`, `lootmode`, `groupid`, `mincountOrRef`, `maxcount`) VALUES
(@REF_GREY1, 1, 25, 1, 0, -@REF_VC, 1),
(@REF_GREY1, 1, 25, 1, 0, -@REF_ML, 1),
(@REF_GREY1, 1, 25, 1, 0, -@REF_MM, 1),
(@REF_GREY1, 1, 25, 1, 0, -@REF_SP, 1);

INSERT INTO `reference_loot_template` (`entry`, `item`, `ChanceOrQuestChance`, `lootmode`, `groupid`, `mincountOrRef`, `maxcount`) VALUES
(@REF_GREEN1, 1, 25, 1, 0, -@, 1),

INSERT INTO `reference_loot_template` (`entry`, `item`, `ChanceOrQuestChance`, `lootmode`, `groupid`, `mincountOrRef`, `maxcount`) VALUES
(@REF_VC, @VC_HEAD, 0, 1, 1, 1, 1),
(@REF_VC, @VC_CHEST, 0, 1, 1, 1, 1),
(@REF_VC, @VC_WAIST, 0, 1, 1, 1, 1),
(@REF_VC, @VC_FEETS, 0, 1, 1, 1, 1),
(@REF_VC, @VC_WRISTS, 0, 1, 1, 1, 1),
(@REF_VC, @VC_HANDS, 0, 1, 1, 1, 1),
(@REF_VC, @VC_LEGS, 0, 1, 1, 1, 1),
(@REF_VC, @VC_SHOULDERS, 0, 1, 1, 1, 1);

INSERT INTO `reference_loot_template` (`entry`, `item`, `ChanceOrQuestChance`, `lootmode`, `groupid`, `mincountOrRef`, `maxcount`) VALUES
(@REF_ML, @ML_HEAD, 0, 1, 1, 1, 1),
(@REF_ML, @ML_CHEST, 0, 1, 1, 1, 1),
(@REF_ML, @ML_WAIST, 0, 1, 1, 1, 1),
(@REF_ML, @ML_FEETS, 0, 1, 1, 1, 1),
(@REF_ML, @ML_WRISTS, 0, 1, 1, 1, 1),
(@REF_ML, @ML_HANDS, 0, 1, 1, 1, 1),
(@REF_ML, @ML_LEGS, 0, 1, 1, 1, 1),
(@REF_ML, @ML_SHOULDERS, 0, 1, 1, 1, 1);

INSERT INTO `reference_loot_template` (`entry`, `item`, `ChanceOrQuestChance`, `lootmode`, `groupid`, `mincountOrRef`, `maxcount`) VALUES
(@REF_MM, @MM_HEAD, 0, 1, 1, 1, 1),
(@REF_MM, @MM_CHEST, 0, 1, 1, 1, 1),
(@REF_MM, @MM_WAIST, 0, 1, 1, 1, 1),
(@REF_MM, @MM_FEETS, 0, 1, 1, 1, 1),
(@REF_MM, @MM_WRISTS, 0, 1, 1, 1, 1),
(@REF_MM, @MM_HANDS, 0, 1, 1, 1, 1),
(@REF_MM, @MM_LEGS, 0, 1, 1, 1, 1),
(@REF_MM, @MM_SHOULDERS, 0, 1, 1, 1, 1);

INSERT INTO `reference_loot_template` (`entry`, `item`, `ChanceOrQuestChance`, `lootmode`, `groupid`, `mincountOrRef`, `maxcount`) VALUES
(@REF_SP, @SP_HEAD, 0, 1, 1, 1, 1),
(@REF_SP, @SP_CHEST, 0, 1, 1, 1, 1),
(@REF_SP, @SP_WAIST, 0, 1, 1, 1, 1),
(@REF_SP, @SP_FEETS, 0, 1, 1, 1, 1),
(@REF_SP, @SP_WRISTS, 0, 1, 1, 1, 1),
(@REF_SP, @SP_HANDS, 0, 1, 1, 1, 1),
(@REF_SP, @SP_LEGS, 0, 1, 1, 1, 1),
(@REF_SP, @SP_SHOULDERS, 0, 1, 1, 1, 1);

DELETE FROM `reference_loot_template` WHERE `entry` IN (@REF_WORLD2, @REF_GREY2, /*@REF_GREEN2,*/ @REF_SC, @REF_SL, @REF_IM, @REF_DP, @REF_BREWC, @REF_SWAML, @REF_WILLM, @REF_SNOWP);
INSERT INTO `reference_loot_template` (`entry`, `item`, `ChanceOrQuestChance`, `lootmode`, `groupid`, `mincountOrRef`, `maxcount`) VALUES
(@REF_WORLD2, 1, 40, 1, 0, -@REF_GREY2, 1),
--(@REF_WORLD2, 2, 20, 1, 0, -@REF_GREEN2, 1); -- NYA

INSERT INTO `reference_loot_template` (`entry`, `item`, `ChanceOrQuestChance`, `lootmode`, `groupid`, `mincountOrRef`, `maxcount`) VALUES
(@REF_GREY2, 1, 25, 1, 0, -@REF_SC, 1),
(@REF_GREY2, 2, 25, 1, 0, -@REF_SL, 1),
(@REF_GREY2, 3, 25, 1, 0, -@REF_IM, 1),
(@REF_GREY2, 4, 25, 1, 0, -@REF_DP, 1);

INSERT INTO `reference_loot_template` (`entry`, `item`, `ChanceOrQuestChance`, `lootmode`, `groupid`, `mincountOrRef`, `maxcount`) VALUES
(@REF_SC, @SC_HEAD, 0, 1, 1, 1, 1),
(@REF_SC, @SC_CHEST, 0, 1, 1, 1, 1),
(@REF_SC, @SC_WAIST, 0, 1, 1, 1, 1),
(@REF_SC, @SC_FEETS, 0, 1, 1, 1, 1),
(@REF_SC, @SC_WRISTS, 0, 1, 1, 1, 1),
(@REF_SC, @SC_HANDS, 0, 1, 1, 1, 1),
(@REF_SC, @SC_LEGS, 0, 1, 1, 1, 1),
(@REF_SC, @SC_SHOULDERS, 0, 1, 1, 1, 1);

INSERT INTO `reference_loot_template` (`entry`, `item`, `ChanceOrQuestChance`, `lootmode`, `groupid`, `mincountOrRef`, `maxcount`) VALUES
(@REF_SL, @SL_HEAD, 0, 1, 1, 1, 1),
(@REF_SL, @SL_CHEST, 0, 1, 1, 1, 1),
(@REF_SL, @SL_WAIST, 0, 1, 1, 1, 1),
(@REF_SL, @SL_FEETS, 0, 1, 1, 1, 1),
(@REF_SL, @SL_WRISTS, 0, 1, 1, 1, 1),
(@REF_SL, @SL_HANDS, 0, 1, 1, 1, 1),
(@REF_SL, @SL_LEGS, 0, 1, 1, 1, 1),
(@REF_SL, @SL_SHOULDERS, 0, 1, 1, 1, 1);

INSERT INTO `reference_loot_template` (`entry`, `item`, `ChanceOrQuestChance`, `lootmode`, `groupid`, `mincountOrRef`, `maxcount`) VALUES
(@REF_IM, @IM_HEAD, 0, 1, 1, 1, 1),
(@REF_IM, @IM_CHEST, 0, 1, 1, 1, 1),
(@REF_IM, @IM_WAIST, 0, 1, 1, 1, 1),
(@REF_IM, @IM_FEETS, 0, 1, 1, 1, 1),
(@REF_IM, @IM_WRISTS, 0, 1, 1, 1, 1),
(@REF_IM, @IM_HANDS, 0, 1, 1, 1, 1),
(@REF_IM, @IM_LEGS, 0, 1, 1, 1, 1),
(@REF_IM, @IM_SHOULDERS, 0, 1, 1, 1, 1);

INSERT INTO `reference_loot_template` (`entry`, `item`, `ChanceOrQuestChance`, `lootmode`, `groupid`, `mincountOrRef`, `maxcount`) VALUES
(@REF_IM, @DP_HEAD, 0, 1, 1, 1, 1),
(@REF_IM, @DP_CHEST, 0, 1, 1, 1, 1),
(@REF_IM, @DP_WAIST, 0, 1, 1, 1, 1),
(@REF_IM, @DP_FEETS, 0, 1, 1, 1, 1),
(@REF_IM, @DP_WRISTS, 0, 1, 1, 1, 1),
(@REF_IM, @DP_HANDS, 0, 1, 1, 1, 1),
(@REF_IM, @DP_LEGS, 0, 1, 1, 1, 1),
(@REF_IM, @DP_SHOULDERS, 0, 1, 1, 1, 1);

INSERT INTO `reference_loot_template` (`entry`, `item`, `ChanceOrQuestChance`, `lootmode`, `groupid`, `mincountOrRef`, `maxcount`) VALUES
(@REF_GREEN2, 1, 25, 1, 0, -@REF_BREWC, 1),
(@REF_GREEN2, 2, 25, 1, 0, -@REF_SWAML, 1),
(@REF_GREEN2, 3, 25, 1, 0, -@REF_WILLM, 1),
(@REF_GREEN2, 4, 25, 1, 0, -@REF_SNOWP, 1);

INSERT INTO `reference_loot_template` (`entry`, `item`, `ChanceOrQuestChance`, `lootmode`, `groupid`, `mincountOrRef`, `maxcount`) VALUES
(@REF_BREWC, @BREWC_HEAD, 0, 1, 1, 1, 1),
(@REF_BREWC, @BREWC_CHEST, 0, 1, 1, 1, 1),
(@REF_BREWC, @BREWC_WAIST, 0, 1, 1, 1, 1),
(@REF_BREWC, @BREWC_FEETS, 0, 1, 1, 1, 1),
(@REF_BREWC, @BREWC_WRISTS, 0, 1, 1, 1, 1),
(@REF_BREWC, @BREWC_HANDS, 0, 1, 1, 1, 1),
(@REF_BREWC, @BREWC_LEGS, 0, 1, 1, 1, 1),
(@REF_BREWC, @BREWC_SHOULDERS, 0, 1, 1, 1, 1);

INSERT INTO `reference_loot_template` (`entry`, `item`, `ChanceOrQuestChance`, `lootmode`, `groupid`, `mincountOrRef`, `maxcount`) VALUES
(@REF_SWAML, @SWAML_HEAD, 0, 1, 1, 1, 1),
(@REF_SWAML, @SWAML_CHEST, 0, 1, 1, 1, 1),
(@REF_SWAML, @SWAML_WAIST, 0, 1, 1, 1, 1),
(@REF_SWAML, @SWAML_FEETS, 0, 1, 1, 1, 1),
(@REF_SWAML, @SWAML_WRISTS, 0, 1, 1, 1, 1),
(@REF_SWAML, @SWAML_HANDS, 0, 1, 1, 1, 1),
(@REF_SWAML, @SWAML_LEGS, 0, 1, 1, 1, 1),
(@REF_SWAML, @SWAML_SHOULDERS, 0, 1, 1, 1, 1);

INSERT INTO `reference_loot_template` (`entry`, `item`, `ChanceOrQuestChance`, `lootmode`, `groupid`, `mincountOrRef`, `maxcount`) VALUES
(@REF_WILLM, @WILLM_HEAD, 0, 1, 1, 1, 1),
(@REF_WILLM, @WILLM_CHEST, 0, 1, 1, 1, 1),
(@REF_WILLM, @WILLM_WAIST, 0, 1, 1, 1, 1),
(@REF_WILLM, @WILLM_FEETS, 0, 1, 1, 1, 1),
(@REF_WILLM, @WILLM_WRISTS, 0, 1, 1, 1, 1),
(@REF_WILLM, @WILLM_HANDS, 0, 1, 1, 1, 1),
(@REF_WILLM, @WILLM_LEGS, 0, 1, 1, 1, 1),
(@REF_WILLM, @WILLM_SHOULDERS, 0, 1, 1, 1, 1);

INSERT INTO `reference_loot_template` (`entry`, `item`, `ChanceOrQuestChance`, `lootmode`, `groupid`, `mincountOrRef`, `maxcount`) VALUES
(@REF_SNOWP, @SNOWP_HEAD, 0, 1, 1, 1, 1),
(@REF_SNOWP, @SNOWP_CHEST, 0, 1, 1, 1, 1),
(@REF_SNOWP, @SNOWP_WAIST, 0, 1, 1, 1, 1),
(@REF_SNOWP, @SNOWP_FEETS, 0, 1, 1, 1, 1),
(@REF_SNOWP, @SNOWP_WRISTS, 0, 1, 1, 1, 1),
(@REF_SNOWP, @SNOWP_HANDS, 0, 1, 1, 1, 1),
(@REF_SNOWP, @SNOWP_LEGS, 0, 1, 1, 1, 1),
(@REF_SNOWP, @SNOWP_SHOULDERS, 0, 1, 1, 1, 1);

SET @ZANDALARIBLOODGUARD := 69294; -- Zandalari Bloodguard
SET @SILVERCOVENANTASSASIN := 68045; -- Silver Covenant Assassin
SET @ZEBTULABEASTCALLER := 69657; -- Zeb'tula Beastcaller
SET @SKUMBLADESLASHER := 70347; -- Skumblade Slasher
SET @SHANZEGRAVEKEEPER := 69235; -- Shan'ze Gravekeeper
SET @SHANZEANIMATOR := 70069; -- Shan'ze Animator
SET @SHANZEELECTROCUTIONER2 := 69216; -- Shan'ze Electrocutioner
SET @ZANDALARIJAGUARWARRIOR := 69171; -- Zandalari Jaguar Warrior
SET @ZANDALARISTONESHIELD2 := 69223; -- Zandalari Stoneshield
SET @ZANDALARIBEASTCALLER := 69065; -- Zandalari Beastcaller
SET @SHANZETHUNDERCALLER := 69264; -- Shan'ze Thundercaller
SET @ZANDALARIACOLYTE := 69295; -- Zandalari Acolyte
SET @ZANDALARIBEASTHANDLER := 69312; -- Zandalari Beast Handler
SET @ZANDALARISTONESHIELD3 := 69865; -- Zandalari Stoneshield
SET @SHANZESLAVER := 67466; -- Shan'ze Slaver
SET @SHANZEBLOODSEEKER := 69431; -- Shan'ze Bloodseeker
SET @ZANDALARICOMMONER := 69170; -- Zandalari Commoner
SET @SHANZESOULRIPPER := 69236; -- Shan'ze Soulripper
SET @ZANDALARIBEASTCALLER2 := 69379; -- Zandalari Beastcaller
SET @ITOKA := 69461; -- Itoka <Master of the Forge>
SET @THANESTONEHEARTH := 67636; -- Thane Stonehearth <Mountain King>
SET @SKUMBLADESAURPRIEST := 69229; -- Skumblade Saur-Priest
SET @NURKALA := 69663; -- Nurkala <The Hunt Master>
SET @MASTERCALLER := 69286; -- Master Caller
SET @ZANDALARIHARUSPEX := 69297; -- Zandalari Haruspex
SET @BLOODHILTGRUNT := 67814; -- Bloodhilt Grunt
SET @ZANDALARIARCWEAVER2 := 69224; -- Zandalari Arcweaver
SET @IRONFORGECABALIST := 67762; -- Ironforge Cabalist
SET @KORKRONPARATROOPER := 67708; -- Kor'kron Paratrooper
SET @SHANBU := 69534; -- Shan Bu
SET @KORKRONGRUNT := 72412; -- Kor'kron Grunt
SET @BEASTMASTERHORAKI := 69559; -- Beastmaster Horaki
SET @ZANDALARICONSCRIPT := 69198; -- Zandalari Conscript
SET @ZANDALARISOULTWISTER := 69296; -- Zandalari Soultwister
SET @METALLORDMONOHAN := 69326; -- Metal Lord Mono-Han
SET @SHAOLMARABEASTCALLER := 70286; -- Shaol'mara Beastcaller
SET @KORUNEWARDEN := 67587; -- Korune Warden
SET @ZANDALARIPROSPECT := 69269; -- Zandalari Prospect
SET @ZANDALARIBEASTLORD := 69144; -- Zandalari Beastlord
SET @SKUMBLADESHORTFANG := 69348; -- Skumblade Shortfang
SET @ANIMATEDWARRIOR := 67473; -- Animated Warrior
SET @SHAOLMARASPEARANGER := 70290; -- Shaol'mara Spearanger
SET @SKUMBLADESCROUNGER := 67760; -- Skumblade Scrounger
SET @SUNREAVERAEGIS := 68051; -- Sunreaver Aegis
SET @SKUMBLADEFLESHRIPPER := 69210; -- Skumblade Fleshripper
SET @SHANZEBRUTALIZER := 70588; -- Shan'ze Brutalizer
SET @SILVERMOONSPELLBREAKER := 67991; -- Silvermoon Spellbreaker
SET @ZANDALARIARCANITAL := 69281; -- Zandalari Arcanital <Harbinger of the Loa>
SET @SHANZEELECTROCUTIONER := 69525; -- Shan'ze Electrocutioner
SET @ZEBTULASTONESHIELD := 69517; -- Zeb'tula Stoneshield
SET @ZANDALARISTONESHIELD := 69527; -- Zandalari Stoneshield
SET @SKUMBLADEFILTHMONGER := 69228; -- Skumblade Filthmonger
SET @SUNRAVERDUELIST := 68647; -- Sunreaver Duelist
SET @SKUMBLADEBRUTE := 69338; -- Skumblade Brute
SET @KORKRONSUBJUGATOR := 68044; -- Kor'kron Subjugator
SET @ZANDALARIARCWEAVER := 70401; -- Zandalari Arcweaver
SET @ANKI := 69531; -- Anki
SET @SUNREAVERMAGE := 68050; -- Sunreaver Mage
SET @SKUMBLADESCAVENGER := 69227; -- Skumblade Scavenger
SET @SKUMBLADESEADRAGON := 69226; -- Skumblade Seadragon
SET @ZANDALARISPIRITBINDER := 69225; -- Zandalari Spiritbinder
SET @PYRESTARDEMOLISHER := 67933; -- Pyrestar Demolisher
SET @KORKRONREAVER := 68940; -- Kor'kron Reaver
SET @ENLISTEDCANNONEER := 67633; -- Enlisted Cannoneer
SET @KORUNEMUTILATOR := 68401; -- Korune Mutilator
SET @SHANZEWARRIOR := 69833; -- Shan'ze Warrior
SET @SHAOTIENSOULRENDER := 65978; -- Shao-Tien Soul-Render
SET @SHAOTIENSURVEYOR := 59379; -- Shao-Tien Surveyor
SET @SHAOTIENPRECURSOR := 59914; -- Shao-Tien Precursor
SET @SHAOTIENPILLAGER := 63948; -- Shao-Tien Pillager
SET @SLATESKINTROUBLEMAKER := 58673; -- Slateskin Troublemaker
SET @OSULSHARPHORN := 60647; -- Osul Sharphorn
SET @KORTHIKFLEETWING := 62128; -- Kor'thik Fleetwing
SET @KRIKTHIKSCENTLAYER := 61373; -- Krik'thik Scentlayer
SET @KRIKTHIKLOCUSGUARD := 61365; -- Krik'thik Locust-Guard
SET @DRAKKARIFROSTWEAVER := 66707; -- Drakkari Frostweaver <Zandalari Invaders>
SET @OOKINSHAMAN := 59435; -- Ookin Shaman
SET @KRIKTHIKDEEPSCOUT := 61374; -- Krik'thik Deep-Scout
SET @SILKTHIKVENOMSPITTER := 62575; -- Sik'thik Venomspitter
SET @SPITEFULSPIRIT := 63839; -- Spiteful Spirit
SET @GLINTROKORACLE := 61239; -- Glintrok Oracle
SET @GLINTROKSKULKER := 61240; -- Glintrok Skulker
SET @GLINTROKHEXXER := 61216; -- Glintrok Hexxer
SET @KRIKTHIKBONESLICER := 61376; -- Kri'thik Boneslicer
SET @SHANZESTONEBENDER := 66315; -- Shan'ze Stonebender
SET @KRIKTHIKWINDSHAPER := 59801; -- Krik'thik Wind Shaper
SET @SIKTHIKBLADEDANCER := 61436; -- Sik'thik Bladedancer
SET @SIKTHIKBUILDER := 62633; -- Sik'thik Builder
SET @SIKTHIKVANGUARD := 61434; -- Sik'thik Vanguard
SET @KRIKTHIKRAGER := 59800; -- Krik'thik Rager
SET @SIKTHIKENGINEER := 62632; -- Sik'thik Engineer
SET @KRIKTHIKSAPPER := 56876; -- Krik'thik Sapper
SET @PALEBLADEFLESHEATER := 59378; -- Paleblade Flesheater
SET @SHAOTIENCONQUEROR := 65132; -- Shao-Tien Conqueror
SET @SHEKZEERCLUTCHKEEPER := 64559; -- Shek'zeer Clutch-Keeper
SET @GAICHOYAUNGOL := 62552; -- Gai-Cho Yaungol
SET @SRATHIKREGENERATOR := 63681; -- Sra'thik Regenerator
SET @KORTHIKHAVOC := 62757; -- Kor'thik Havoc
SET @SHAOTIENFIST := 65134; -- Shao-Tien Fist
SET @SHAOTIENDOMINATOR := 63610; -- Shao-Tien Dominator
SET @SHAOTIENANTIQUATOR := 58928; -- Shao-Tien Antiquator
SET @KUNZENRITUALIST := 59123; -- Kunzen Ritualist
SET @VORTHIKDREADWORN := 62813; -- Vor'thik Dreadsworn
SET @IKTHIKGENEMANCER := 63257; -- Ik'thik Genemancer
SET @KUNZENSOUPMASTER := 59125; -- Kunzen Soupmaster
SET @DARKWOODSCHARMER := 62457; -- Darkwoods Charmer
SET @KORTHIKRESONATOR := 62755; -- Kor'thik Resonator
SET @KRIKTHIKNEEDLER := 63976; -- Krik'thik Needler
SET @SHAOTIENSORCERER := 65133; -- Shao-Tien Sorcerer
SET @MISTBLADERIPPER := 61970; -- Mistblade Ripper
SET @SHAOTIENSOULCALLER := 63611; -- Shao-Tien Soul-Caller
SET @IKTHIKHARVESTER := 63206; -- Ik'thik Harvester
SET @SLITHERSCALERIPPER := 58212; -- Slitherscale Ripper
SET @GAICHOEARTHTALKER := 62553; -- Gai-Cho Earthtalker
SET @GAICHOPITCHTHROWER := 62608; -- Gai-Cho Pitchthrower
SET @MUCKSCALERIPPER := 63993; -- Muckscale Ripper
SET @MUCKSCALESHAMAN := 64008; -- Muckscale Shaman
SET @MUCKSCALESKINFLAYER := 63339; -- Muckscale Skinflayer
SET @YONGQILOOTER := 60479; -- Yongqi Looter
SET @MUCKSCALESLAYER := 63999; -- Muckscale Slayer
SET @WILLYWOODLING := 61155; -- Wily Woodling
SET @SUNREAVERMAGUS := 67661; -- Sunreaver Magus
SET @KUNZENHUNTER := 59121; -- Kunzen Hunter
SET @SLITHERSCALEEGGDRINKER := 63532; -- Slitherscale Eggdrinker
SET @SHANZESERPENTBINDER := 62293; -- Shan'ze Serpentbinder
SET @SHAOTIENPAINWEAVER := 65131; -- Shao-Tien Painweaver
SET @SRATHIKMUTILATOR := 63678; -- Sra'thik Mutilator
SET @SHEKZEERMANIPULATOR := 64720; -- Shek'zeer Manipulator
SET @IKTHIKWARRIOR := 65573; -- Ik'thik Warrior
SET @BATAARIYAUNGOL := 63527; -- Bataari Yaungol
SET @SRATHIKCACOPHYTE := 63680; -- Sra'thik Cacophyte
SET @OONAGOON := 65621; -- Oona Goon
SET @SILVERCOVENANTSPELLBLADE := 67970; -- Silver Covenant Spellblade
SET @KORTHIKWARCALLER := 62754; -- Kor'thik Warcaller
SET @SIKTHIKBATTLEMENDER := 67093; -- Sik'thik Battle-Mender
SET @ADJUNCTKREEZOT := 62301; -- Adjunct Kree'zot <Hand of Shek'zeer>
SET @SRATHIKDEATHMIXER := 63688; -- Sra'thik Deathmixer
SET @ZANDALARIDINOMANCER := 69925; -- Zandalari Dinomancer
SET @JUNGLESHREDER := 67285; -- Jungle Shredder
SET @SHANZEILLUSIONIST := 62440; -- Shan'ze Illusionist
SET @SHIELDWALLMECHAPOUNDER := 67967; -- Shieldwall Mecha-Pounder
SET @DAMPSHAMBLER := 72771; -- Damp Shambler
SET @DEATHADDER := 72841; -- Death Adder
SET @PRIMALSTALKER := 72805; -- Primal Stalker
SET @ERODEDCLIFFWELLER := 72809; -- Eroded Cliffdweller
SET @ELDERFREATTURTLE := 72765; -- Elder Great Turtle

DELETE FROM `creature_loot_template` WHERE item=1 AND `entry` IN (
@SHANZEWARRIOR, @SHAOTIENSOULRENDER, @SHAOTIENSURVEYOR, @SHAOTIENPRECURSOR, @SHAOTIENPILLAGER, @SLATESKINTROUBLEMAKER,
@KORUNEMUTILATOR,@OSULSHARPHORN, @KORTHIKFLEETWING, @KRIKTHIKSCENTLAYER, @KRIKTHIKLOCUSGUARD, @DRAKKARIFROSTWEAVER, @OOKINSHAMAN,
@KRIKTHIKDEEPSCOUT, @SILKTHIKVENOMSPITTER, @SPITEFULSPIRIT, @GLINTROKORACLE, @GLINTROKSKULKER, @GLINTROKHEXXER, @KRIKTHIKBONESLICER,
@SHANZESTONEBENDER, @KRIKTHIKWINDSHAPER, @SIKTHIKBLADEDANCER, @SIKTHIKBUILDER, @SIKTHIKVANGUARD, @KRIKTHIKRAGER, @SIKTHIKENGINEER,
@KRIKTHIKSAPPER, @ENLISTEDCANNONEER, @KORKRONREAVER, @SUNRAVERDUELIST, @SKUMBLADEBRUTE, @KORKRONSUBJUGATOR, @ZANDALARIARCWEAVER, @ANKI,
@SUNREAVERMAGE, @SKUMBLADESCAVENGER, @SKUMBLADESEADRAGON, @ZANDALARISPIRITBINDER, @PYRESTARDEMOLISHER, @SHAOLMARASPEARANGER,
@PALEBLADEFLESHEATER, @SKUMBLADESCROUNGER, @SUNREAVERAEGIS, @SKUMBLADEFLESHRIPPER, @SHANZEBRUTALIZER, @SILVERMOONSPELLBREAKER,
@ZANDALARIARCANITAL, @SHANZEELECTROCUTIONER, @ZEBTULASTONESHIELD, @ZANDALARISTONESHIELD, @SKUMBLADEFILTHMONGER, @ZANDALARICONSCRIPT,
@ZANDALARISOULTWISTER, @METALLORDMONOHAN, @SHAOLMARABEASTCALLER, @KORUNEWARDEN, @ZANDALARIPROSPECT, @ZANDALARIBEASTLORD,
@SKUMBLADESHORTFANG, @ANIMATEDWARRIOR, @SHAOTIENCONQUEROR, @ZANDALARIBLOODGUARD, @SHEKZEERCLUTCHKEEPER, @GAICHOYAUNGOL,
@SRATHIKREGENERATOR, @KORTHIKHAVOC, @SILVERCOVENANTASSASIN, @ZEBTULABEASTCALLER, @SKUMBLADESLASHER, @SHAOTIENFIST, @SHAOTIENDOMINATOR,
@SHANZEGRAVEKEEPER, @SHANZEANIMATOR, @SHANZEELECTROCUTIONER2, @SHAOTIENANTIQUATOR, @ZANDALARIJAGUARWARRIOR, @ZANDALARISTONESHIELD2,
@KUNZENRITUALIST, @VORTHIKDREADWORN, @ZANDALARIBEASTCALLER, @SHANZETHUNDERCALLER, @IKTHIKGENEMANCER, @ZANDALARIACOLYTE,
@KUNZENSOUPMASTER, @DARKWOODSCHARMER, @ZANDALARISTONESHIELD3, @KORTHIKRESONATOR, @KRIKTHIKNEEDLER, @ZANDALARIBEASTHANDLER,
@SHAOTIENSORCERER, @MISTBLADERIPPER, @SHAOTIENSOULCALLER, @IKTHIKHARVESTER, @SLITHERSCALERIPPER, @SHANZESLAVER, @GAICHOEARTHTALKER,
@SHANZEBLOODSEEKER, @GAICHOPITCHTHROWER, @ZANDALARICOMMONER, @MUCKSCALERIPPER, @SHANZESOULRIPPER, @MUCKSCALESHAMAN, @MUCKSCALESKINFLAYER,
@YONGQILOOTER, @ZANDALARIBEASTCALLER2, @MUCKSCALESLAYER, @WILLYWOODLING, @SUNREAVERMAGUS, @ITOKA, @THANESTONEHEARTH, @SKUMBLADESAURPRIEST,
@NURKALA, @KUNZENHUNTER, @SLITHERSCALEEGGDRINKER, @SHANZESERPENTBINDER, @SHAOTIENPAINWEAVER, @SRATHIKMUTILATOR, @SHEKZEERMANIPULATOR,
@IKTHIKWARRIOR, @BATAARIYAUNGOL, @SRATHIKCACOPHYTE, @MASTERCALLER, @ZANDALARIHARUSPEX, @BLOODHILTGRUNT, @OONAGOON, 
@SILVERCOVENANTSPELLBLADE, @ZANDALARIARCWEAVER2, @KORTHIKWARCALLER, @IRONFORGECABALIST, @SHANBU, @KORKRONGRUNT, @SIKTHIKBATTLEMENDER,
@ADJUNCTKREEZOT, @SRATHIKDEATHMIXER, @KORKRONPARATROOPER, @ZANDALARIDINOMANCER, @JUNGLESHREDER, @BEASTMASTERHORAKI,
@SHANZEILLUSIONIST, @SHIELDWALLMECHAPOUNDER, @DAMPSHAMBLER, @DEATHADDER, @PRIMALSTALKER, @ERODEDCLIFFWELLER, @ELDERFREATTURTLE);

INSERT INTO `creature_loot_template` (`entry`, `item`, `ChanceOrQuestChance`, `lootmode`, `groupid`, `mincountOrRef`, `maxcount`) VALUES
(@SHANZEWARRIOR, 1, 100, 1, 0, -@REF_WORLD2, 1),
(@SHAOTIENSOULRENDER, 1, 100, 1, 0, -@REF_WORLD2, 1),
(@SHAOTIENSURVEYOR, 1, 100, 1, 0, -@REF_WORLD2, 1),
(@SHAOTIENPRECURSOR, 1, 100, 1, 0, -@REF_WORLD2, 1),
(@SHAOTIENPILLAGER, 1, 100, 1, 0, -@REF_WORLD2, 1),
(@SLATESKINTROUBLEMAKER, 1, 100, 1, 0, -@REF_WORLD2, 1),
(@KORUNEMUTILATOR, 1, 100, 1, 0, -@REF_WORLD2, 1),
(@OSULSHARPHORN, 1, 100, 1, 0, -@REF_WORLD2, 1),
(@KORTHIKFLEETWING, 1, 100, 1, 0, -@REF_WORLD2, 1),
(@KRIKTHIKSCENTLAYER, 1, 100, 1, 0, -@REF_WORLD2, 1),
(@KRIKTHIKLOCUSGUARD, 1, 100, 1, 0, -@REF_WORLD2, 1),
(@DRAKKARIFROSTWEAVER, 1, 100, 1, 0, -@REF_WORLD2, 1),
(@OOKINSHAMAN, 1, 100, 1, 0, -@REF_WORLD2, 1),
(@KRIKTHIKDEEPSCOUT, 1, 100, 1, 0, -@REF_WORLD2, 1),
(@SILKTHIKVENOMSPITTER, 1, 100, 1, 0, -@REF_WORLD2, 1),
(@SPITEFULSPIRIT, 1, 100, 1, 0, -@REF_WORLD2, 1),
(@GLINTROKORACLE, 1, 100, 1, 0, -@REF_WORLD2, 1),
(@GLINTROKSKULKER, 1, 100, 1, 0, -@REF_WORLD2, 1),
(@GLINTROKHEXXER, 1, 100, 1, 0, -@REF_WORLD2, 1),
(@KRIKTHIKBONESLICER, 1, 100, 1, 0, -@REF_WORLD2, 1),
(@SHANZESTONEBENDER, 1, 100, 1, 0, -@REF_WORLD2, 1),
(@KRIKTHIKWINDSHAPER, 1, 100, 1, 0, -@REF_WORLD2, 1),
(@SIKTHIKBLADEDANCER, 1, 100, 1, 0, -@REF_WORLD2, 1),
(@SIKTHIKBUILDER, 1, 100, 1, 0, -@REF_WORLD2, 1),
(@SIKTHIKVANGUARD, 1, 100, 1, 0, -@REF_WORLD2, 1),
(@KRIKTHIKRAGER, 1, 100, 1, 0, -@REF_WORLD2, 1),
(@SIKTHIKENGINEER, 1, 100, 1, 0, -@REF_WORLD2, 1),
(@KRIKTHIKSAPPER, 1, 100, 1, 0, -@REF_WORLD2, 1),
(@ENLISTEDCANNONEER, 1, 100, 1, 0, -@REF_WORLD2, 1),
(@KORKRONREAVER, 1, 100, 1, 0, -@REF_WORLD2, 1),
(@SUNRAVERDUELIST, 1, 100, 1, 0, -@REF_WORLD2, 1),
(@SKUMBLADEBRUTE, 1, 100, 1, 0, -@REF_WORLD2, 1),
(@KORKRONSUBJUGATOR, 1, 100, 1, 0, -@REF_WORLD2, 1),
(@ZANDALARIARCWEAVER, 1, 100, 1, 0, -@REF_WORLD2, 1),
(@ANKI, 1, 100, 1, 0, -@REF_WORLD2, 1),
(@SUNREAVERMAGE, 1, 100, 1, 0, -@REF_WORLD2, 1),
(@SKUMBLADESCAVENGER, 1, 100, 1, 0, -@REF_WORLD2, 1),
(@SKUMBLADESEADRAGON, 1, 100, 1, 0, -@REF_WORLD2, 1),
(@ZANDALARISPIRITBINDER, 1, 100, 1, 0, -@REF_WORLD2, 1),
(@PYRESTARDEMOLISHER, 1, 100, 1, 0, -@REF_WORLD2, 1),
(@SHAOLMARASPEARANGER, 1, 100, 1, 0, -@REF_WORLD2, 1),
(@PALEBLADEFLESHEATER, 1, 100, 1, 0, -@REF_WORLD2, 1),
(@SKUMBLADESCROUNGER, 1, 100, 1, 0, -@REF_WORLD2, 1),
(@SUNREAVERAEGIS, 1, 100, 1, 0, -@REF_WORLD2, 1),
(@SKUMBLADEFLESHRIPPER, 1, 100, 1, 0, -@REF_WORLD2, 1),
(@SHANZEBRUTALIZER, 1, 100, 1, 0, -@REF_WORLD2, 1),
(@SILVERMOONSPELLBREAKER, 1, 100, 1, 0, -@REF_WORLD2, 1),
(@ZANDALARIARCANITAL, 1, 100, 1, 0, -@REF_WORLD2, 1),
(@SHANZEELECTROCUTIONER, 1, 100, 1, 0, -@REF_WORLD2, 1),
(@ZEBTULASTONESHIELD, 1, 100, 1, 0, -@REF_WORLD2, 1),
(@ZANDALARISTONESHIELD, 1, 100, 1, 0, -@REF_WORLD2, 1),
(@SKUMBLADEFILTHMONGER, 1, 100, 1, 0, -@REF_WORLD2, 1),
(@ZANDALARICONSCRIPT, 1, 100, 1, 0, -@REF_WORLD2, 1),
(@ZANDALARISOULTWISTER, 1, 100, 1, 0, -@REF_WORLD2, 1),
(@METALLORDMONOHAN, 1, 100, 1, 0, -@REF_WORLD2, 1),
(@SHAOLMARABEASTCALLER, 1, 100, 1, 0, -@REF_WORLD2, 1),
(@KORUNEWARDEN, 1, 100, 1, 0, -@REF_WORLD2, 1),
(@ZANDALARIPROSPECT, 1, 100, 1, 0, -@REF_WORLD2, 1),
(@ZANDALARIBEASTLORD, 1, 100, 1, 0, -@REF_WORLD2, 1),
(@SKUMBLADESHORTFANG, 1, 100, 1, 0, -@REF_WORLD2, 1),
(@ANIMATEDWARRIOR, 1, 100, 1, 0, -@REF_WORLD2, 1),
(@SHAOTIENCONQUEROR, 1, 100, 1, 0, -@REF_WORLD2, 1),
(@ZANDALARIBLOODGUARD, 1, 100, 1, 0, -@REF_WORLD2, 1),
(@SHEKZEERCLUTCHKEEPER, 1, 100, 1, 0, -@REF_WORLD2, 1),
(@GAICHOYAUNGOL, 1, 100, 1, 0, -@REF_WORLD2, 1),
(@SRATHIKREGENERATOR, 1, 100, 1, 0, -@REF_WORLD2, 1),
(@KORTHIKHAVOC, 1, 100, 1, 0, -@REF_WORLD2, 1),
(@SILVERCOVENANTASSASIN, 1, 100, 1, 0, -@REF_WORLD2, 1),
(@ZEBTULABEASTCALLER, 1, 100, 1, 0, -@REF_WORLD2, 1),
(@SKUMBLADESLASHER, 1, 100, 1, 0, -@REF_WORLD2, 1),
(@SHAOTIENFIST, 1, 100, 1, 0, -@REF_WORLD2, 1),
(@SHAOTIENDOMINATOR, 1, 100, 1, 0, -@REF_WORLD2, 1),
(@SHANZEGRAVEKEEPER, 1, 100, 1, 0, -@REF_WORLD2, 1),
(@SHANZEANIMATOR, 1, 100, 1, 0, -@REF_WORLD2, 1),
(@SHANZEELECTROCUTIONER2, 1, 100, 1, 0, -@REF_WORLD2, 1),
(@SHAOTIENANTIQUATOR, 1, 100, 1, 0, -@REF_WORLD2, 1),
(@ZANDALARIJAGUARWARRIOR, 1, 100, 1, 0, -@REF_WORLD2, 1),
(@ZANDALARISTONESHIELD2, 1, 100, 1, 0, -@REF_WORLD2, 1),
(@KUNZENRITUALIST, 1, 100, 1, 0, -@REF_WORLD2, 1),
(@VORTHIKDREADWORN, 1, 100, 1, 0, -@REF_WORLD2, 1),
(@ZANDALARIBEASTCALLER, 1, 100, 1, 0, -@REF_WORLD2, 1),
(@SHANZETHUNDERCALLER, 1, 100, 1, 0, -@REF_WORLD2, 1),
(@IKTHIKGENEMANCER, 1, 100, 1, 0, -@REF_WORLD2, 1),
(@ZANDALARIACOLYTE, 1, 100, 1, 0, -@REF_WORLD2, 1),
(@KUNZENSOUPMASTER, 1, 100, 1, 0, -@REF_WORLD2, 1),
(@DARKWOODSCHARMER, 1, 100, 1, 0, -@REF_WORLD2, 1),
(@ZANDALARISTONESHIELD3, 1, 100, 1, 0, -@REF_WORLD2, 1),
(@KORTHIKRESONATOR, 1, 100, 1, 0, -@REF_WORLD2, 1),
(@KRIKTHIKNEEDLER, 1, 100, 1, 0, -@REF_WORLD2, 1),
(@ZANDALARIBEASTHANDLER, 1, 100, 1, 0, -@REF_WORLD2, 1),
(@SHAOTIENSORCERER, 1, 100, 1, 0, -@REF_WORLD2, 1),
(@MISTBLADERIPPER, 1, 100, 1, 0, -@REF_WORLD2, 1),
(@SHAOTIENSOULCALLER, 1, 100, 1, 0, -@REF_WORLD2, 1),
(@IKTHIKHARVESTER, 1, 100, 1, 0, -@REF_WORLD2, 1),
(@SLITHERSCALERIPPER, 1, 100, 1, 0, -@REF_WORLD2, 1),
(@SHANZESLAVER, 1, 100, 1, 0, -@REF_WORLD2, 1),
(@GAICHOEARTHTALKER, 1, 100, 1, 0, -@REF_WORLD2, 1),
(@SHANZEBLOODSEEKER, 1, 100, 1, 0, -@REF_WORLD2, 1),
(@GAICHOPITCHTHROWER, 1, 100, 1, 0, -@REF_WORLD2, 1),
(@ZANDALARICOMMONER, 1, 100, 1, 0, -@REF_WORLD2, 1),
(@MUCKSCALERIPPER, 1, 100, 1, 0, -@REF_WORLD2, 1),
(@SHANZESOULRIPPER, 1, 100, 1, 0, -@REF_WORLD2, 1),
(@MUCKSCALESHAMAN, 1, 100, 1, 0, -@REF_WORLD2, 1),
(@MUCKSCALESKINFLAYER, 1, 100, 1, 0, -@REF_WORLD2, 1),
(@YONGQILOOTER, 1, 100, 1, 0, -@REF_WORLD2, 1),
(@ZANDALARIBEASTCALLER2, 1, 100, 1, 0, -@REF_WORLD2, 1),
(@MUCKSCALESLAYER, 1, 100, 1, 0, -@REF_WORLD2, 1),
(@WILLYWOODLING, 1, 100, 1, 0, -@REF_WORLD2, 1),
(@SUNREAVERMAGUS, 1, 100, 1, 0, -@REF_WORLD2, 1),
(@ITOKA, 1, 100, 1, 0, -@REF_WORLD2, 1),
(@THANESTONEHEARTH, 1, 100, 1, 0, -@REF_WORLD2, 1),
(@SKUMBLADESAURPRIEST, 1, 100, 1, 0, -@REF_WORLD2, 1),
(@NURKALA, 1, 100, 1, 0, -@REF_WORLD2, 1),
(@KUNZENHUNTER, 1, 100, 1, 0, -@REF_WORLD2, 1),
(@SLITHERSCALEEGGDRINKER, 1, 100, 1, 0, -@REF_WORLD2, 1),
(@SHANZESERPENTBINDER, 1, 100, 1, 0, -@REF_WORLD2, 1),
(@SHAOTIENPAINWEAVER, 1, 100, 1, 0, -@REF_WORLD2, 1),
(@SRATHIKMUTILATOR, 1, 100, 1, 0, -@REF_WORLD2, 1),
(@SHEKZEERMANIPULATOR, 1, 100, 1, 0, -@REF_WORLD2, 1),
(@IKTHIKWARRIOR, 1, 100, 1, 0, -@REF_WORLD2, 1),
(@BATAARIYAUNGOL, 1, 100, 1, 0, -@REF_WORLD2, 1),
(@SRATHIKCACOPHYTE, 1, 100, 1, 0, -@REF_WORLD2, 1),
(@MASTERCALLER, 1, 100, 1, 0, -@REF_WORLD2, 1),
(@ZANDALARIHARUSPEX, 1, 100, 1, 0, -@REF_WORLD2, 1),
(@BLOODHILTGRUNT, 1, 100, 1, 0, -@REF_WORLD2, 1),
(@OONAGOON, 1, 100, 1, 0, -@REF_WORLD2, 1),
(@SILVERCOVENANTSPELLBLADE, 1, 100, 1, 0, -@REF_WORLD2, 1),
(@ZANDALARIARCWEAVER2, 1, 100, 1, 0, -@REF_WORLD2, 1),
(@KORTHIKWARCALLER, 1, 100, 1, 0, -@REF_WORLD2, 1),
(@IRONFORGECABALIST, 1, 100, 1, 0, -@REF_WORLD2, 1),
(@SHANBU, 1, 100, 1, 0, -@REF_WORLD2, 1),
(@KORKRONGRUNT, 1, 100, 1, 0, -@REF_WORLD2, 1),
(@SIKTHIKBATTLEMENDER, 1, 100, 1, 0, -@REF_WORLD2, 1),
(@ADJUNCTKREEZOT, 1, 100, 1, 0, -@REF_WORLD2, 1),
(@SRATHIKDEATHMIXER, 1, 100, 1, 0, -@REF_WORLD2, 1),
(@KORKRONPARATROOPER, 1, 100, 1, 0, -@REF_WORLD2, 1),
(@ZANDALARIDINOMANCER, 1, 100, 1, 0, -@REF_WORLD2, 1),
(@JUNGLESHREDER, 1, 100, 1, 0, -@REF_WORLD2, 1),
(@BEASTMASTERHORAKI, 1, 100, 1, 0, -@REF_WORLD2, 1),
(@SHANZEILLUSIONIST, 1, 100, 1, 0, -@REF_WORLD2, 1),
(@SHIELDWALLMECHAPOUNDER, 1, 100, 1, 0, -@REF_WORLD2, 1),
(@DAMPSHAMBLER, 1, 100, 1, 0, -@REF_WORLD2, 1),
(@DEATHADDER, 1, 100, 1, 0, -@REF_WORLD2, 1),
(@PRIMALSTALKER, 1, 100, 1, 0, -@REF_WORLD2, 1),
(@ERODEDCLIFFWELLER, 1, 100, 1, 0, -@REF_WORLD2, 1),
(@ELDERFREATTURTLE, 1, 100, 1, 0, -@REF_WORLD2, 1);

-- CREATURE_TEMPLATE EXISTS
UPDATE `creature_template` SET `lootid`=`entry` WHERE `entry` IN (
@SHANZEWARRIOR, @SHAOTIENSOULRENDER, @SHAOTIENSURVEYOR, @SHAOTIENPRECURSOR, @SHAOTIENPILLAGER, @SLATESKINTROUBLEMAKER,
@KORUNEMUTILATOR,@OSULSHARPHORN, @KORTHIKFLEETWING, @KRIKTHIKSCENTLAYER, @KRIKTHIKLOCUSGUARD, @DRAKKARIFROSTWEAVER, @OOKINSHAMAN,
@KRIKTHIKDEEPSCOUT, @SILKTHIKVENOMSPITTER, @SPITEFULSPIRIT, @GLINTROKORACLE, @GLINTROKSKULKER, @GLINTROKHEXXER, @KRIKTHIKBONESLICER,
@SHANZESTONEBENDER, @KRIKTHIKWINDSHAPER, @SIKTHIKBLADEDANCER, @SIKTHIKBUILDER, @SIKTHIKVANGUARD, @KRIKTHIKRAGER, @SIKTHIKENGINEER,
@KRIKTHIKSAPPER, @ENLISTEDCANNONEER, @KORKRONREAVER, @SUNRAVERDUELIST, @SKUMBLADEBRUTE, @KORKRONSUBJUGATOR, @ZANDALARIARCWEAVER, @ANKI,
@SUNREAVERMAGE, @SKUMBLADESCAVENGER, @SKUMBLADESEADRAGON, @ZANDALARISPIRITBINDER, @PYRESTARDEMOLISHER, @SHAOLMARASPEARANGER,
@PALEBLADEFLESHEATER, @SKUMBLADESCROUNGER, @SUNREAVERAEGIS, @SKUMBLADEFLESHRIPPER, @SHANZEBRUTALIZER, @SILVERMOONSPELLBREAKER,
@ZANDALARIARCANITAL, @SHANZEELECTROCUTIONER, @ZEBTULASTONESHIELD, @ZANDALARISTONESHIELD, @SKUMBLADEFILTHMONGER, @ZANDALARICONSCRIPT,
@ZANDALARISOULTWISTER, @METALLORDMONOHAN, @SHAOLMARABEASTCALLER, @KORUNEWARDEN, @ZANDALARIPROSPECT, @ZANDALARIBEASTLORD,
@SKUMBLADESHORTFANG, @ANIMATEDWARRIOR, @SHAOTIENCONQUEROR, @ZANDALARIBLOODGUARD, @SHEKZEERCLUTCHKEEPER, @GAICHOYAUNGOL,
@SRATHIKREGENERATOR, @KORTHIKHAVOC, @SILVERCOVENANTASSASIN, @ZEBTULABEASTCALLER, @SKUMBLADESLASHER, @SHAOTIENFIST, @SHAOTIENDOMINATOR,
@SHANZEGRAVEKEEPER, @SHANZEANIMATOR, @SHANZEELECTROCUTIONER2, @SHAOTIENANTIQUATOR, @ZANDALARIJAGUARWARRIOR, @ZANDALARISTONESHIELD2,
@KUNZENRITUALIST, @VORTHIKDREADWORN, @ZANDALARIBEASTCALLER, @SHANZETHUNDERCALLER, @IKTHIKGENEMANCER, @ZANDALARIACOLYTE,
@KUNZENSOUPMASTER, @DARKWOODSCHARMER, @ZANDALARISTONESHIELD3, @KORTHIKRESONATOR, @KRIKTHIKNEEDLER, @ZANDALARIBEASTHANDLER,
@SHAOTIENSORCERER, @MISTBLADERIPPER, @SHAOTIENSOULCALLER, @IKTHIKHARVESTER, @SLITHERSCALERIPPER, @SHANZESLAVER, @GAICHOEARTHTALKER,
@SHANZEBLOODSEEKER, @GAICHOPITCHTHROWER, @ZANDALARICOMMONER, @MUCKSCALERIPPER, @SHANZESOULRIPPER, @MUCKSCALESHAMAN, @MUCKSCALESKINFLAYER,
@YONGQILOOTER, @ZANDALARIBEASTCALLER2, @MUCKSCALESLAYER, @WILLYWOODLING, @SUNREAVERMAGUS, @ITOKA, @THANESTONEHEARTH, @SKUMBLADESAURPRIEST,
@NURKALA, @KUNZENHUNTER, @SLITHERSCALEEGGDRINKER, @SHANZESERPENTBINDER, @SHAOTIENPAINWEAVER, @SRATHIKMUTILATOR, @SHEKZEERMANIPULATOR,
@IKTHIKWARRIOR, @BATAARIYAUNGOL, @SRATHIKCACOPHYTE, @MASTERCALLER, @ZANDALARIHARUSPEX, @BLOODHILTGRUNT, @OONAGOON, 
@SILVERCOVENANTSPELLBLADE, @ZANDALARIARCWEAVER2, @KORTHIKWARCALLER, @IRONFORGECABALIST, @SHANBU, @KORKRONGRUNT, @SIKTHIKBATTLEMENDER,
@ADJUNCTKREEZOT, @SRATHIKDEATHMIXER, @KORKRONPARATROOPER, @ZANDALARIDINOMANCER, @JUNGLESHREDER, @BEASTMASTERHORAKI,
@SHANZEILLUSIONIST, @SHIELDWALLMECHAPOUNDER, @DAMPSHAMBLER, @DEATHADDER, @PRIMALSTALKER, @ERODEDCLIFFWELLER, @ELDERFREATTURTLE);
