/*
Navicat MySQL Data Transfer

Source Server         : LocalHost
Source Server Version : 50635
Source Host           : localhost:3306
Source Database       : sf_world

Target Server Type    : MYSQL
Target Server Version : 50635
File Encoding         : 65001

Date: 2017-02-19 19:46:13
*/

SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- Table structure for `command`
-- ----------------------------
DROP TABLE IF EXISTS `command`;
CREATE TABLE `command` (
  `name` varchar(50) NOT NULL DEFAULT '',
  `permission` smallint(5) unsigned NOT NULL DEFAULT '0',
  `help` longtext,
  PRIMARY KEY (`name`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 ROW_FORMAT=FIXED COMMENT='Chat System';

-- ----------------------------
-- Records of command
-- ----------------------------
INSERT INTO `command` VALUES ('account create', '219', 'Syntax: .account create $account $password\r\n\r\nCreate account and set password to it.');
INSERT INTO `command` VALUES ('account delete', '220', 'Syntax: .account delete $account\r\n\r\nDelete account with all characters.');
INSERT INTO `command` VALUES ('account lock ip', '223', 'Syntax: .account lock ip [on|off]\nAllow login from account only from current used IP or remove this requirement.');
INSERT INTO `command` VALUES ('account onlinelist', '224', 'Syntax: .account onlinelist\r\n\r\nShow list of online accounts.');
INSERT INTO `command` VALUES ('account password', '225', 'Syntax: .account password $old_password $new_password $new_password\r\n\r\nChange your account password.');
INSERT INTO `command` VALUES ('account set addon', '227', 'Syntax: .account set addon [$account] #addon\n\nSet user (possible targeted) expansion addon level allowed. Addon values: 0 - normal, 1 - tbc, 2 - wotlk, 3 - cata.');
INSERT INTO `command` VALUES ('account set gmlevel', '228', 'Syntax: .account set gmlevel [$account] #level [#realmid]\r\n\r\nSet the security level for targeted player (can\'t be used at self) or for account $name to a level of #level on the realm #realmID.\r\n\r\n#level may range from 0 to 3.\r\n\r\n#reamID may be -1 for all realms.');
INSERT INTO `command` VALUES ('account set password', '229', 'Syntax: .account set password $account $password $password\r\n\r\nSet password for account.');
INSERT INTO `command` VALUES ('account set', '226', 'Syntax: .account set $subcommand\nType .account set to see the list of possible subcommands or .help account set $subcommand to see info on subcommands');
INSERT INTO `command` VALUES ('account', '217', 'Syntax: .account\r\n\r\nDisplay the access level of your account.');
INSERT INTO `command` VALUES ('additem', '488', 'Syntax: .additem #itemid/[#itemname]/#shift-click-item-link #itemcount\r\n\r\nAdds the specified number of items of id #itemid (or exact (!) name $itemname in brackets, or link created by shift-click at item in inventory or recipe) to your or selected character inventory. If #itemcount is omitted, only one item will be added.\r\n.');
INSERT INTO `command` VALUES ('additemset', '489', 'Syntax: .additemset #itemsetid\r\n\r\nAdd items from itemset of id #itemsetid to your or selected character inventory. Will add by one example each item from itemset.');
INSERT INTO `command` VALUES ('announce', '462', 'Syntax: .announce $MessageToBroadcast\r\n\r\nSend a global message to all players online in chat log.');
INSERT INTO `command` VALUES ('aura', '491', 'Syntax: .aura #spellid\r\n\r\nAdd the aura from spell #spellid to the selected Unit.');
INSERT INTO `command` VALUES ('ban account', '240', 'Syntax: .ban account $Name $bantime $reason\r\nBan account kick player.\r\n$bantime: negative value leads to permban, otherwise use a timestring like \"4d20h3s\".');
INSERT INTO `command` VALUES ('ban character', '241', 'Syntax: .ban character $Name $bantime $reason\nBan character and kick player.\n$bantime: negative value leads to permban, otherwise use a timestring like \"4d20h3s\".');
INSERT INTO `command` VALUES ('ban ip', '242', 'Syntax: .ban ip $Ip $bantime $reason\r\nBan IP.\r\n$bantime: negative value leads to permban, otherwise use a timestring like \"4d20h3s\".');
INSERT INTO `command` VALUES ('ban', '239', 'Syntax: .ban $subcommand\nType .ban to see the list of possible subcommands or .help ban $subcommand to see info on subcommands');
INSERT INTO `command` VALUES ('baninfo account', '245', 'Syntax: .baninfo account $accountid\r\nWatch full information about a specific ban.');
INSERT INTO `command` VALUES ('baninfo character', '246', 'Syntax: .baninfo character $charactername \r\nWatch full information about a specific ban.');
INSERT INTO `command` VALUES ('baninfo ip', '247', 'Syntax: .baninfo ip $ip\r\nWatch full information about a specific ban.');
INSERT INTO `command` VALUES ('baninfo', '244', 'Syntax: .baninfo $subcommand\nType .baninfo to see the list of possible subcommands or .help baninfo $subcommand to see info on subcommands');
INSERT INTO `command` VALUES ('bank', '492', 'Syntax: .bank\r\n\r\nShow your bank inventory.');
INSERT INTO `command` VALUES ('banlist account', '249', 'Syntax: .banlist account [$Name]\r\nSearches the banlist for a account name pattern or show full list account bans.');
INSERT INTO `command` VALUES ('banlist character', '250', 'Syntax: .banlist character $Name\r\nSearches the banlist for a character name pattern. Pattern required.');
INSERT INTO `command` VALUES ('banlist ip', '251', 'Syntax: .banlist ip [$Ip]\r\nSearches the banlist for a IP pattern or show full list of IP bans.');
INSERT INTO `command` VALUES ('banlist', '248', 'Syntax: .banlist $subcommand\nType .banlist to see the list of possible subcommands or .help banlist $subcommand to see info on subcommands');
INSERT INTO `command` VALUES ('bindsight', '493', 'Syntax: .bindsight\r\n\r\nBinds vision to the selected unit indefinitely. Cannot be used while currently possessing a target.');
INSERT INTO `command` VALUES ('cast back', '268', 'Syntax: .cast back #spellid [triggered]\r\n  Selected target will cast #spellid to your character. If \'trigered\' or part provided then spell casted with triggered flag.');
INSERT INTO `command` VALUES ('cast dist', '269', 'Syntax: .cast dist #spellid [#dist [triggered]]\r\n  You will cast spell to pint at distance #dist. If \'trigered\' or part provided then spell casted with triggered flag. Not all spells can be casted as area spells.');
INSERT INTO `command` VALUES ('cast self', '270', 'Syntax: .cast self #spellid [triggered]\r\nCast #spellid by target at target itself. If \'trigered\' or part provided then spell casted with triggered flag.');
INSERT INTO `command` VALUES ('cast target', '271', 'Syntax: .cast target #spellid [triggered]\r\n  Selected target will cast #spellid to his victim. If \'trigered\' or part provided then spell casted with triggered flag.');
INSERT INTO `command` VALUES ('cast', '267', 'Syntax: .cast #spellid [triggered]\r\n  Cast #spellid to selected target. If no target selected cast to self. If \'trigered\' or part provided then spell casted with triggered flag.');
INSERT INTO `command` VALUES ('character customize', '274', 'Syntax: .character customize [$name]\r\n\r\nMark selected in game or by $name in command character for customize at next login.');
INSERT INTO `command` VALUES ('character erase', '282', 'Syntax: .character erase $name\r\n\r\nDelete character $name. Character finally deleted in case any deleting options.');
INSERT INTO `command` VALUES ('character level', '283', 'Syntax: .character level [$playername] [#level]\r\n\r\nSet the level of character with $playername (or the selected if not name provided) by #numberoflevels Or +1 if no #numberoflevels provided). If #numberoflevels is omitted, the level will be increase by 1. If #numberoflevels is 0, the same level will be restarted. If no character is selected and name not provided, increase your level. Command can be used for offline character. All stats and dependent values recalculated. At level decrease talents can be reset if need. Also at level decrease equipped items with greater level requirement can be lost.');
INSERT INTO `command` VALUES ('character rename', '284', 'Syntax: .character rename [$name] [$newName] \n\nMark selected in game or by $name in command character for rename at next login.\n\nIf $newName then the player will be forced rename.');
INSERT INTO `command` VALUES ('character reputation', '285', 'Syntax: .character reputation [$player_name]\r\n\r\nShow reputation information for selected player or player find by $player_name.');
INSERT INTO `command` VALUES ('combatstop', '494', 'Syntax: .combatstop [$playername]\r\nStop combat for selected character. If selected non-player then command applied to self. If $playername provided then attempt applied to online player $playername.');
INSERT INTO `command` VALUES ('cometome', '495', 'SYntax: .cometome $parameter\nMake selected creature come to your current location (new position not saved to DB).');
INSERT INTO `command` VALUES ('commands', '496', 'Syntax: .commands\r\n\r\nDisplay a list of available commands for your account level.');
INSERT INTO `command` VALUES ('cooldown', '497', 'Syntax: .cooldown [#spell_id]\r\n\r\nRemove all (if spell_id not provided) or #spel_id spell cooldown from selected character or you (if no selection).');
INSERT INTO `command` VALUES ('damage', '498', 'Syntax: .damage $damage_amount [$school [$spellid]]\r\n\r\nApply $damage to target. If not $school and $spellid provided then this flat clean melee damage without any modifiers. If $school provided then damage modified by armor reduction (if school physical), and target absorbing modifiers and result applied as melee damage to target. If spell provided then damage modified and applied as spell damage. $spellid can be shift-link.');
INSERT INTO `command` VALUES ('debug arena', '303', 'Syntax: .debug arena\r\n\r\nToggle debug mode for arenas. In debug mode GM can start arena with single player.');
INSERT INTO `command` VALUES ('debug bg', '304', 'Syntax: .debug bg\r\n\r\nToggle debug mode for battlegrounds. In debug mode GM can start battleground with single player.');
INSERT INTO `command` VALUES ('debug Mod32Value', '313', 'Syntax: .debug Mod32Value #field #value\r\n\r\nAdd #value to field #field of your character.');
INSERT INTO `command` VALUES ('debug play cinematic', '316', 'Syntax: .debug play cinematic #cinematicid\r\n\r\nPlay cinematic #cinematicid for you. You stay at place while your mind fly.\r\n');
INSERT INTO `command` VALUES ('debug play movie', '317', 'Syntax: .debug play movie #movieid\r\n\r\nPlay movie #movieid for you.');
INSERT INTO `command` VALUES ('debug play sound', '318', 'Syntax: .debug play sound #soundid\r\n\r\nPlay sound with #soundid.\r\nSound will be play only for you. Other players do not hear this.\r\nWarning: client may have more 5000 sounds...');
INSERT INTO `command` VALUES ('debug', '300', 'Syntax: .debug $subcommand\nType .debug to see the list of possible subcommands or .help debug $subcommand to see info on subcommands');
INSERT INTO `command` VALUES ('demorph', '543', 'Syntax: .demorph\r\n\r\nDemorph the selected player.');
INSERT INTO `command` VALUES ('die', '500', 'Syntax: .die\r\n\r\nKill the selected player. If no player is selected, it will kill you.');
INSERT INTO `command` VALUES ('dismount', '501', 'Syntax: .dismount\r\n\r\nDismount you, if you are mounted.');
INSERT INTO `command` VALUES ('distance', '502', 'Syntax: .distance\r\n\r\nDisplay the distance from your character to the selected creature.');
INSERT INTO `command` VALUES ('event activelist', '368', 'Syntax: .event activelist\r\nShow list of currently active events.');
INSERT INTO `command` VALUES ('event start', '369', 'Syntax: .event start #event_id\r\nStart event #event_id. Set start time for event to current moment (change not saved in DB).');
INSERT INTO `command` VALUES ('event stop', '370', 'Syntax: .event stop #event_id\r\nStop event #event_id. Set start time for event to time in past that make current moment is event stop time (change not saved in DB).');
INSERT INTO `command` VALUES ('event', '367', 'Syntax: .event #event_id\r\nShow details about event with #event_id.');
INSERT INTO `command` VALUES ('cheat cooldown', '293', 'Syntax: .cheat cooldown [on/off]\r\nEnables or disables your character\'s spell cooldowns.');
INSERT INTO `command` VALUES ('cheat power', '296', 'Syntax: .cheat power [on/off]\r\nEnables or disables your character\'s spell cost (e.g mana).');
INSERT INTO `command` VALUES ('freeze', '504', 'Syntax: .freeze (#player)\r\n\"Freezes\" #player and disables his chat. When using this without #name it will freeze your target.');
INSERT INTO `command` VALUES ('gm chat', '372', 'Syntax: .gm chat [on/off]\r\n\r\nEnable or disable chat GM MODE (show gm badge in messages) or show current state of on/off not provided.');
INSERT INTO `command` VALUES ('gm fly', '373', 'Syntax: .gm fly [on/off]\r\nEnable/disable gm fly mode.');
INSERT INTO `command` VALUES ('gm ingame', '374', 'Syntax: .gm ingame\r\n\r\nDisplay a list of available in game Game Masters.');
INSERT INTO `command` VALUES ('gm list', '375', 'Syntax: .gm list\r\n\r\nDisplay a list of all Game Masters accounts and security levels.');
INSERT INTO `command` VALUES ('gm visible', '376', 'Syntax: .gm visible on/off\r\n\r\nOutput current visibility state or make GM visible(on) and invisible(off) for other players.');
INSERT INTO `command` VALUES ('gm', '371', 'Syntax: .gm [on/off]\r\n\r\nEnable or Disable in game GM MODE or show current state of on/off not provided.');
INSERT INTO `command` VALUES ('gmannounce', '466', 'Syntax: .gmannounce $announcement\r\nSend an announcement to online Gamemasters.');
INSERT INTO `command` VALUES ('gmnameannounce', '467', 'Syntax: .gmnameannounce $announcement.\r\nSend an announcement to all online GM\'s, displaying the name of the sender.');
INSERT INTO `command` VALUES ('gmnotify', '468', 'Syntax: .gmnotify $notification\r\nDisplays a notification on the screen of all online GM\'s.');
INSERT INTO `command` VALUES ('go creature', '378', 'Syntax: .go creature #creature_guid\r\nTeleport your character to creature with guid #creature_guid.\r\n.gocreature #creature_name\r\nTeleport your character to creature with this name.\r\n.gocreature id #creature_id\r\nTeleport your character to a creature that was spawned from the template with this entry.\r\n*If* more than one creature is found, then you are teleported to the first that is found inside the database.');
INSERT INTO `command` VALUES ('go graveyard', '379', 'Syntax: .go graveyard #graveyardId\r\n Teleport to graveyard with the graveyardId specified.');
INSERT INTO `command` VALUES ('go grid', '380', 'Syntax: .go grid #gridX #gridY [#mapId]\r\n\r\nTeleport the gm to center of grid with provided indexes at map #mapId (or current map if it not provided).');
INSERT INTO `command` VALUES ('go object', '381', 'Syntax: .go object #object_guid\r\nTeleport your character to gameobject with guid #object_guid');
INSERT INTO `command` VALUES ('go taxinode', '382', 'Syntax: .go taxinode #taxinode\r\n\r\nTeleport player to taxinode coordinates. You can look up zone using .lookup taxinode $namepart');
INSERT INTO `command` VALUES ('go ticket', '383', 'Syntax: .go ticket #ticketid\r\nTeleports the user to the location where $ticketid was created.');
INSERT INTO `command` VALUES ('go trigger', '384', 'Syntax: .go trigger #trigger_id\r\n\r\nTeleport your character to areatrigger with id #trigger_id. Character will be teleported to trigger target if selected areatrigger is telporting trigger.');
INSERT INTO `command` VALUES ('go xyz', '385', 'Syntax: .go xyz #x #y [#z [#mapid [#orientation]]]\r\n\r\nTeleport player to point with (#x,#y,#z) coordinates at map #mapid with orientation #orientation. If z is not provided, ground/water level will be used. If mapid is not provided, the current map will be used. If #orientation is not provided, the current orientation will be used.');
INSERT INTO `command` VALUES ('go zonexy', '386', 'Syntax: .go zonexy #x #y [#zone]\r\n\r\nTeleport player to point with (#x,#y) client coordinates at ground(water) level in zone #zoneid or current zone if #zoneid not provided. You can look up zone using .lookup area $namepart');
INSERT INTO `command` VALUES ('go', '377', 'Syntax: .go $subcommand\nType .go to see the list of possible subcommands or .help go $subcommand to see info on subcommands');
INSERT INTO `command` VALUES ('gobject activate', '388', 'Syntax: .gobject activate #guid\r\n\r\nActivates an object like a door or a button.');
INSERT INTO `command` VALUES ('gobject add', '389', 'Syntax: .gobject add #id <spawntimeSecs>\r\n\r\nAdd a game object from game object templates to the world at your current location using the #id.\r\nspawntimesecs sets the spawntime, it is optional.\r\n\r\nNote: this is a copy of .gameobject.');
INSERT INTO `command` VALUES ('gobject delete', '391', 'Syntax: .gobject delete #go_guid\r\nDelete gameobject with guid #go_guid.');
INSERT INTO `command` VALUES ('gobject move', '393', 'Syntax: .gobject move #goguid [#x #y #z]\r\n\r\nMove gameobject #goguid to character coordinates (or to (#x,#y,#z) coordinates if its provide).');
INSERT INTO `command` VALUES ('gobject near', '394', 'Syntax: .gobject near  [#distance]\r\n\r\nOutput gameobjects at distance #distance from player. Output gameobject guids and coordinates sorted by distance from character. If #distance not provided use 10 as default value.');
INSERT INTO `command` VALUES ('gobject add temp', '390', 'Adds a temporary gameobject that is not saved to DB.');
INSERT INTO `command` VALUES ('gobject target', '398', 'Syntax: .gobject target [#go_id|#go_name_part]\r\n\r\nLocate and show position nearest gameobject. If #go_id or #go_name_part provide then locate and show position of nearest gameobject with gameobject template id #go_id or name included #go_name_part as part.');
INSERT INTO `command` VALUES ('gobject set phase', '396', 'Syntax: .gobject set phase #guid #phasemask\r\n\r\nGameobject with DB guid #guid phasemask changed to #phasemask with related world vision update for players. Gameobject state saved to DB and persistent.');
INSERT INTO `command` VALUES ('gobject turn', '399', 'Syntax: .gobject turn #goguid \r\n\r\nSet for gameobject #goguid orientation same as current character orientation.');
INSERT INTO `command` VALUES ('gobject', '387', 'Syntax: .gobject $subcommand\nType .gobject to see the list of possible subcommands or .help gobject $subcommand to see info on subcommands');
INSERT INTO `command` VALUES ('summon', '528', 'Syntax: .summon [$charactername]\r\n\r\nTeleport the given character to you. Character can be offline.');
INSERT INTO `command` VALUES ('gps', '505', 'Syntax: .gps [$name|$shift-link]\r\n\r\nDisplay the position information for a selected character or creature (also if player name $name provided then for named player, or if creature/gameobject shift-link provided then pointed creature/gameobject if it loaded). Position information includes X, Y, Z, and orientation, map Id and zone Id');
INSERT INTO `command` VALUES ('group summon', '255', 'Syntax: .group summon [$charactername]\r\n\r\nTeleport the given character and his group to you. Teleported only online characters but original selected group member can be offline.');
INSERT INTO `command` VALUES ('guid', '506', 'Syntax: .guid\r\n\r\nDisplay the GUID for the selected character.');
INSERT INTO `command` VALUES ('guild create', '402', 'Syntax: .guild create [$GuildLeaderName] \"$GuildName\"\r\n\r\nCreate a guild named $GuildName with the player $GuildLeaderName (or selected) as leader.  Guild name must in quotes.');
INSERT INTO `command` VALUES ('guild delete', '403', 'Syntax: .guild delete \"$GuildName\"\r\n\r\nDelete guild $GuildName. Guild name must in quotes.');
INSERT INTO `command` VALUES ('guild invite', '404', 'Syntax: .guild invite [$CharacterName] \"$GuildName\"\r\n\r\nAdd player $CharacterName (or selected) into a guild $GuildName. Guild name must in quotes.');
INSERT INTO `command` VALUES ('guild rank', '406', 'Syntax: .guild rank [$CharacterName] #Rank\r\n\r\nSet for player $CharacterName (or selected) rank #Rank in a guild.');
INSERT INTO `command` VALUES ('guild uninvite', '405', 'Syntax: .guild uninvite [$CharacterName]\r\n\r\nRemove player $CharacterName (or selected) from a guild.');
INSERT INTO `command` VALUES ('guild', '401', 'Syntax: .guild $subcommand\nType .guild to see the list of possible subcommands or .help guild $subcommand to see info on subcommands');
INSERT INTO `command` VALUES ('help', '507', 'Syntax: .help [$command]\r\n\r\nDisplay usage instructions for the given $command. If no $command provided show list available commands.');
INSERT INTO `command` VALUES ('hidearea', '508', 'Syntax: .hidearea #areaid\r\n\r\nHide the area of #areaid to the selected character. If no character is selected, hide this area to you.');
INSERT INTO `command` VALUES ('honor add', '409', 'Syntax: .honor add $amount\r\n\r\nAdd a certain amount of honor (gained today) to the selected player.');
INSERT INTO `command` VALUES ('honor add kill', '410', 'Syntax: .honor add kill\r\n\r\nAdd the targeted unit as one of your pvp kills today (you only get honor if it\'s a racial leader or a player)');
INSERT INTO `command` VALUES ('honor update', '411', 'Syntax: .honor update\r\n\r\nForce the yesterday\'s honor fields to be updated with today\'s data, which will get reset for the selected player.');
INSERT INTO `command` VALUES ('honor', '408', 'Syntax: .honor $subcommand\nType .honor to see the list of possible subcommands or .help honor $subcommand to see info on subcommands');
INSERT INTO `command` VALUES ('instance listbinds', '413', 'Syntax: .instance listbinds\r\n  Lists the binds of the selected player.');
INSERT INTO `command` VALUES ('instance savedata', '416', 'Syntax: .instance savedata\r\n  Save the InstanceData for the current player\'s map to the DB.');
INSERT INTO `command` VALUES ('instance stats', '415', 'Syntax: .instance stats\r\n  Shows statistics about instances.');
INSERT INTO `command` VALUES ('instance unbind', '414', 'Syntax: .instance unbind <mapid|all> [difficulty]\r\n  Clear all/some of player\'s binds');
INSERT INTO `command` VALUES ('instance', '412', 'Syntax: .instance $subcommand\nType .instance to see the list of possible subcommands or .help instance $subcommand to see info on subcommands');
INSERT INTO `command` VALUES ('itemmove', '509', 'Syntax: .itemmove #sourceslotid #destinationslotid\r\n\r\nMove an item from slots #sourceslotid to #destinationslotid in your inventory\r\n\r\nNot yet implemented');
INSERT INTO `command` VALUES ('kick', '510', 'Syntax: .kick [$charactername] [$reason]\r\n\r\nKick the given character name from the world with or without reason. If no character name is provided then the selected player (except for yourself) will be kicked. If no reason is provided, default is \"No Reason\".');
INSERT INTO `command` VALUES ('learn all my talents', '423', 'Syntax: .learn all my talents\r\n\r\nLearn all talents (and spells with first rank learned as talent) available for his class.');
INSERT INTO `command` VALUES ('learn all my spells', '422', 'Syntax: .learn all my spells\r\n\r\nLearn all spells (except talents and spells with first rank learned as talent) available for his class.');
INSERT INTO `command` VALUES ('learn all my pettalents', '421', 'Syntax: .learn all my pettalents\r\n\r\nLearn all talents for your pet available for his creature type (only for hunter pets).');
INSERT INTO `command` VALUES ('learn all my class', '420', 'Syntax: .learn all my class\r\n\r\nLearn all spells and talents available for his class.');
INSERT INTO `command` VALUES ('learn all gm', '424', 'Syntax: .learn all gm\r\n\r\nLearn all default spells for Game Masters.');
INSERT INTO `command` VALUES ('learn all lang', '427', 'Syntax: .learn all lang\r\n\r\nLearn all languages');
INSERT INTO `command` VALUES ('learn all default', '426', 'Syntax: .learn all default [$playername]\r\n\r\nLearn for selected/$playername player all default spells for his race/class and spells rewarded by completed quests.');
INSERT INTO `command` VALUES ('learn', '417', 'Syntax: .learn #spell [all]\r\n\r\nSelected character learn a spell of id #spell. If \'all\' provided then all ranks learned.');
INSERT INTO `command` VALUES ('modify scale', '560', '.modify scale #scale\nModify size of the selected player or creature to \"normal scale\"*rate. If no player or creature is selected, modify your size.\n#rate may range from 0.1 to 10.');
INSERT INTO `command` VALUES ('learn all crafts', '425', 'Syntax: .learn crafts\r\n\r\nLearn all professions and recipes.');
INSERT INTO `command` VALUES ('levelup', '287', 'Syntax: .levelup [$playername] [#numberoflevels]\r\n\r\nIncrease/decrease the level of character with $playername (or the selected if not name provided) by #numberoflevels Or +1 if no #numberoflevels provided). If #numberoflevels is omitted, the level will be increase by 1. If #numberoflevels is 0, the same level will be restarted. If no character is selected and name not provided, increase your level. Command can be used for offline character. All stats and dependent values recalculated. At level decrease talents can be reset if need. Also at level decrease equipped items with greater level requirement can be lost.');
INSERT INTO `command` VALUES ('linkgrave', '511', 'Syntax: .linkgrave #graveyard_id [alliance|horde]\r\n\r\nLink current zone to graveyard for any (or alliance/horde faction ghosts). This let character ghost from zone teleport to graveyard after die if graveyard is nearest from linked to zone and accept ghost of this faction. Add only single graveyard at another map and only if no graveyards linked (or planned linked at same map).');
INSERT INTO `command` VALUES ('list auras', '440', 'Syntax: .list auras\nList auras (passive and active) of selected creature or player. If no creature or player is selected, list your own auras.');
INSERT INTO `command` VALUES ('list creature', '437', 'Syntax: .list creature #creature_id [#max_count]\r\n\r\nOutput creatures with creature id #creature_id found in world. Output creature guids and coordinates sorted by distance from character. Will be output maximum #max_count creatures. If #max_count not provided use 10 as default value.');
INSERT INTO `command` VALUES ('list item', '438', 'Syntax: .list item #item_id [#max_count]\r\n\r\nOutput items with item id #item_id found in all character inventories, mails, auctions, and guild banks. Output item guids, item owner guid, owner account and owner name (guild name and guid in case guild bank). Will be output maximum #max_count items. If #max_count not provided use 10 as default value.');
INSERT INTO `command` VALUES ('list object', '439', 'Syntax: .list object #gameobject_id [#max_count]\r\n\r\nOutput gameobjects with gameobject id #gameobject_id found in world. Output gameobject guids and coordinates sorted by distance from character. Will be output maximum #max_count gameobject. If #max_count not provided use 10 as default value.');
INSERT INTO `command` VALUES ('list', '436', 'Syntax: .list $subcommand\nType .list to see the list of possible subcommands or .help list $subcommand to see info on subcommands');
INSERT INTO `command` VALUES ('listfreeze', '512', 'Syntax: .listfreeze\r\n\r\nSearch and output all frozen players.');
INSERT INTO `command` VALUES ('wp reload', '773', 'Syntax: .wp reload $pathid\nLoad path changes ingame - IMPORTANT: must be applied first for new paths before .wp load #pathid ');
INSERT INTO `command` VALUES ('reload spell_group', '693', 'Syntax: .reload spell_group\nReload spell_group table.');
INSERT INTO `command` VALUES ('lookup area', '443', 'Syntax: .lookup area $namepart\r\n\r\nLooks up an area by $namepart, and returns all matches with their area ID\'s.');
INSERT INTO `command` VALUES ('lookup creature', '444', 'Syntax: .lookup creature $namepart\r\n\r\nLooks up a creature by $namepart, and returns all matches with their creature ID\'s.');
INSERT INTO `command` VALUES ('lookup event', '445', 'Syntax: .lookup event $name\r\nAttempts to find the ID of the event with the provided $name.');
INSERT INTO `command` VALUES ('lookup faction', '446', 'Syntax: .lookup faction $name\r\nAttempts to find the ID of the faction with the provided $name.');
INSERT INTO `command` VALUES ('lookup item', '447', 'Syntax: .lookup item $itemname\r\n\r\nLooks up an item by $itemname, and returns all matches with their Item ID\'s.');
INSERT INTO `command` VALUES ('lookup itemset', '448', 'Syntax: .lookup itemset $itemname\r\n\r\nLooks up an item set by $itemname, and returns all matches with their Item set ID\'s.');
INSERT INTO `command` VALUES ('lookup map', '461', 'Syntax: .lookup map $namepart\r\n\r\nLooks up a map by $namepart, and returns all matches with their map ID\'s.');
INSERT INTO `command` VALUES ('lookup object', '449', 'Syntax: .lookup object $objname\r\n\r\nLooks up an gameobject by $objname, and returns all matches with their Gameobject ID\'s.');
INSERT INTO `command` VALUES ('lookup player account', '453', 'Syntax: .lookup player account $account ($limit) \r\n\r\n Searchs players, which account username is $account with optional parametr $limit of results.');
INSERT INTO `command` VALUES ('lookup player email', '454', 'Syntax: .lookup player email $email ($limit) \r\n\r\n Searchs players, which account email is $email with optional parametr $limit of results.');
INSERT INTO `command` VALUES ('lookup player ip', '452', 'Syntax: .lookup player ip $ip ($limit) \r\n\r\n Searchs players, which account ast_ip is $ip with optional parametr $limit of results.');
INSERT INTO `command` VALUES ('lookup quest', '450', 'Syntax: .lookup quest $namepart\r\n\r\nLooks up a quest by $namepart, and returns all matches with their quest ID\'s.');
INSERT INTO `command` VALUES ('lookup skill', '455', 'Syntax: .lookup skill $$namepart\r\n\r\nLooks up a skill by $namepart, and returns all matches with their skill ID\'s.');
INSERT INTO `command` VALUES ('lookup spell', '456', 'Syntax: .lookup spell $namepart\r\n\r\nLooks up a spell by $namepart, and returns all matches with their spell ID\'s.');
INSERT INTO `command` VALUES ('lookup taxinode', '458', 'Syntax: .lookup taxinode $substring\r\n\r\nSearch and output all taxinodes with provide $substring in name.');
INSERT INTO `command` VALUES ('lookup tele', '459', 'Syntax: .lookup tele $substring\r\n\r\nSearch and output all .tele command locations with provide $substring in name.');
INSERT INTO `command` VALUES ('lookup', '442', 'Syntax: .lookup $subcommand\nType .lookup to see the list of possible subcommands or .help lookup $subcommand to see info on subcommands');
INSERT INTO `command` VALUES ('maxskill', '513', 'Syntax: .maxskill\r\nSets all skills of the targeted player to their maximum values for its current level.');
INSERT INTO `command` VALUES ('modify speed walk', '565', 'Syntax: .modify speed bwalk #rate\r\n\r\nModify the speed of the selected player while running to \"normal walk speed\"*rate. If no player is selected, modify your speed.\r\n\r\n #rate may range from 0.1 to 50.');
INSERT INTO `command` VALUES ('modify bit', '546', 'Syntax: .modify bit #field #bit\r\n\r\nToggle the #bit bit of the #field field for the selected player. If no player is selected, modify your character.');
INSERT INTO `command` VALUES ('modify speed swim', '566', 'Syntax: .modify speed swim #rate\r\n\r\nModify the swim speed of the selected player to \"normal swim speed\"*rate. If no player is selected, modify your speed.\r\n\r\n #rate may range from 0.1 to 50.');
INSERT INTO `command` VALUES ('modify drunk', '547', 'Syntax: .modify drunk #value\r\n Set drunk level to #value (0..100). Value 0 remove drunk state, 100 is max drunked state.');
INSERT INTO `command` VALUES ('modify energy', '548', 'Syntax: .modify energy #energy\r\n\r\nModify the energy of the selected player. If no player is selected, modify your energy.');
INSERT INTO `command` VALUES ('modify faction', '549', 'Syntax: .modify faction #factionid #flagid #npcflagid #dynamicflagid\r\n\r\nModify the faction and flags of the selected creature. Without arguments, display the faction and flags of the selected creature.');
INSERT INTO `command` VALUES ('modify speed fly', '564', '.modify speed fly #rate\nModify the flying speed of the selected player to \"normal flying speed\"*rate. If no player is selected, modify your speed.\n #rate may range from 0.1 to 50.');
INSERT INTO `command` VALUES ('modify gender', '550', 'Syntax: .modify gender male/female\r\n\r\nChange gender of selected player.');
INSERT INTO `command` VALUES ('modify honor', '551', 'Syntax: .modify honor $amount\r\n\r\nAdd $amount honor points to the selected player.');
INSERT INTO `command` VALUES ('modify hp', '552', 'Syntax: .modify hp #newhp\r\n\r\nModify the hp of the selected player. If no player is selected, modify your hp.');
INSERT INTO `command` VALUES ('modify mana', '553', 'Syntax: .modify mana #newmana\r\n\r\nModify the mana of the selected player. If no player is selected, modify your mana.');
INSERT INTO `command` VALUES ('modify money', '554', 'Syntax: .modify money #money\r\n.money #money\r\n\r\nAdd or remove money to the selected player. If no player is selected, modify your money.\r\n\r\n #gold can be negative to remove money.');
INSERT INTO `command` VALUES ('modify mount', '555', 'Syntax: .modify mount #id #speed\r\nDisplay selected player as mounted at #id creature and set speed to #speed value.');
INSERT INTO `command` VALUES ('modify phase', '556', 'Syntax: .modify phase #phasemask\r\n\r\nSelected character phasemask changed to #phasemask with related world vision update. Change active until in game phase changed, or GM-mode enable/disable, or re-login. Character pts pasemask update to same value.');
INSERT INTO `command` VALUES ('modify rage', '557', 'Syntax: .modify rage #newrage\r\n\r\nModify the rage of the selected player. If no player is selected, modify your rage.');
INSERT INTO `command` VALUES ('modify reputation', '558', 'Syntax: .modify reputation #repId (#repvalue | $rankname [#delta])\nSets the selected players reputation with faction #repId to #repvalue or to $reprank.\nIf the reputation rank name is provided, the resulting reputation will be the lowest reputation for that rank plus the delta amount, if specified.\nYou can use \'.pinfo rep\' to list all known reputation ids, or use \'.lookup faction $name\' to locate a specific faction id.');
INSERT INTO `command` VALUES ('modify runicpower', '559', 'Syntax: .modify runicpower #newrunicpower\r\n\r\nModify the runic power of the selected player. If no player is selected, modify your runic power.');
INSERT INTO `command` VALUES ('modify speed', '561', 'Syntax: .modify speed $speedtype #rate\r\n\r\nModify the running speed of the selected player to \"normal base run speed\"= 1. If no player is selected, modify your speed.\r\n\r\n$speedtypes may be fly, all, walk, backwalk, or swim.\r\n\r\n #rate may range from 0.1 to 50.');
INSERT INTO `command` VALUES ('modify spell', '567', 'TODO');
INSERT INTO `command` VALUES ('modify standstate', '568', 'Syntax: .modify standstate #emoteid\r\n\r\nChange the emote of your character while standing to #emoteid.');
INSERT INTO `command` VALUES ('modify speed backwalk', '563', 'Syntax: .modify speed backwalk #rate\r\n\r\nModify the speed of the selected player while running backwards to \"normal walk back speed\"*rate. If no player is selected, modify your speed.\r\n\r\n #rate may range from 0.1 to 50.');
INSERT INTO `command` VALUES ('character titles', '286', 'Syntax: .character titles [$player_name]\r\n\r\nShow known titles list for selected player or player find by $player_name.');
INSERT INTO `command` VALUES ('modify speed all', '562', 'Syntax: .modify aspeed #rate\r\n\r\nModify all speeds -run,swim,run back,swim back- of the selected player to \"normalbase speed for this move type\"*rate. If no player is selected, modify your speed.\r\n\r\n #rate may range from 0.1 to 50.');
INSERT INTO `command` VALUES ('modify', '544', 'Syntax: .modify $subcommand\nType .modify to see the list of possible subcommands or .help modify $subcommand to see info on subcommands');
INSERT INTO `command` VALUES ('movegens', '514', 'Syntax: .movegens\r\n  Show movement generators stack for selected creature or player.');
INSERT INTO `command` VALUES ('mute', '515', 'Syntax: .mute [$playerName] $timeInMinutes [$reason]\r\n\r\nDisible chat messaging for any character from account of character $playerName (or currently selected) at $timeInMinutes minutes. Player can be offline.');
INSERT INTO `command` VALUES ('nameannounce', '469', 'Syntax: .nameannounce $announcement.\nSend an announcement to all online players, displaying the name of the sender.');
INSERT INTO `command` VALUES ('appear', '490', 'Syntax: .appear [$charactername]\r\n\r\nTeleport to the given character. Either specify the character name or click on the character\'s portrait,e.g. when you are in a group. Character can be offline.');
INSERT INTO `command` VALUES ('neargrave', '516', 'Syntax: .neargrave [alliance|horde]\r\n\r\nFind nearest graveyard linked to zone (or only nearest from accepts alliance or horde faction ghosts).');
INSERT INTO `command` VALUES ('notify', '470', 'Syntax: .notify $MessageToBroadcast\r\n\r\nSend a global message to all players online in screen.');
INSERT INTO `command` VALUES ('npc set phase', '589', 'Syntax: .npc set phase #phasemask\r\n\r\nSelected unit or pet phasemask changed to #phasemask with related world vision update for players. In creature case state saved to DB and persistent. In pet case change active until in game phase changed for owner, owner re-login, or GM-mode enable/disable..');
INSERT INTO `command` VALUES ('npc set movetype', '588', 'Syntax: .npc set movetype [#creature_guid] stay/random/way [NODEL]\r\n\r\nSet for creature pointed by #creature_guid (or selected if #creature_guid not provided) movement type and move it to respawn position (if creature alive). Any existing waypoints for creature will be removed from the database if you do not use NODEL. If the creature is dead then movement type will applied at creature respawn.\r\nMake sure you use NODEL, if you want to keep the waypoints.');
INSERT INTO `command` VALUES ('npc set model', '587', 'Syntax: .npc set model #displayid\r\n\r\nChange the model id of the selected creature to #displayid.');
INSERT INTO `command` VALUES ('npc set link', '586', 'Syntax: .npc set link $creatureGUID\r\n\r\nLinks respawn of selected creature to the condition that $creatureGUID defined is alive.');
INSERT INTO `command` VALUES ('wpgps', '340', 'Syntax: .wpgps\n\nOutput current position to sql developer log as partial SQL query to be used in pathing');
INSERT INTO `command` VALUES ('npc say', '597', 'Syntax: .npc say $message\nMake selected creature say specified message.');
INSERT INTO `command` VALUES ('npc move', '595', 'Syntax: .npc move [#creature_guid]\r\n\r\nMove the targeted creature spawn point to your coordinates.');
INSERT INTO `command` VALUES ('npc playemote', '596', 'Syntax: .npc playemote #emoteid\r\n\r\nMake the selected creature emote with an emote of id #emoteid.');
INSERT INTO `command` VALUES ('npc follow stop', '579', 'Syntax: .npc follow stop\r\n\r\nSelected creature (non pet) stop follow you.');
INSERT INTO `command` VALUES ('npc info', '593', 'Syntax: .npc info\r\n\r\nDisplay a list of details for the selected creature.\r\n\r\nThe list includes:\r\n- GUID, Faction, NPC flags, Entry ID, Model ID,\r\n- Level,\r\n- Health (current/maximum),\r\n\r\n- Field flags, dynamic flags, faction template, \r\n- Position information,\r\n- and the creature type, e.g. if the creature is a vendor.');
INSERT INTO `command` VALUES ('npc follow', '578', 'Syntax: .npc follow start\r\n\r\nSelected creature start follow you until death/fight/etc.');
INSERT INTO `command` VALUES ('npc set flag', '584', 'Syntax: .npc set flag #npcflag\r\n\r\nSet the NPC flags of creature template of the selected creature and selected creature to #npcflag. NPC flags will applied to all creatures of selected creature template after server restart or grid unload/load.');
INSERT INTO `command` VALUES ('npc set factionid', '583', 'Syntax: .npc set factionid #factionid\r\n\r\nSet the faction of the selected creature to #factionid.');
INSERT INTO `command` VALUES ('npc set level', '585', 'Syntax: .npc set level #level\r\n\r\nChange the level of the selected creature to #level.\r\n\r\n#level may range from 1 to (CONFIG_MAX_PLAYER_LEVEL) + 3.');
INSERT INTO `command` VALUES ('npc delete', '576', 'Syntax: .npc delete [#guid]\r\n\r\nDelete creature with guid #guid (or the selected if no guid is provided)');
INSERT INTO `command` VALUES ('npc delete item', '577', 'Syntax: .npc delete item #itemId\r\n\r\nRemove item #itemid from item list of selected vendor.');
INSERT INTO `command` VALUES ('npc set allowmove', '581', 'Syntax: .npc set allowmove\r\n\r\nEnable or disable movement creatures in world. Not implemented.');
INSERT INTO `command` VALUES ('npc set entry', '582', 'Syntax: .npc set entry $entry\nSwitch selected creature with another entry from creature_template. - New creature.id value not saved to DB.');
INSERT INTO `command` VALUES ('npc add move', '574', 'Syntax: .npc add move #creature_guid [#waittime]\r\n\r\nAdd your current location as a waypoint for creature with guid #creature_guid. And optional add wait time.');
INSERT INTO `command` VALUES ('npc add item', '573', 'Syntax: .npc add item #itemId <#maxcount><#incrtime><#extendedcost>r\r\n\r\nAdd item #itemid to item list of selected vendor. Also optionally set max count item in vendor item list and time to item count restoring and items ExtendedCost.');
INSERT INTO `command` VALUES ('npc add formation', '572', 'Syntax: .npc add formation $leader\nAdd selected creature to a leader\'s formation.');
INSERT INTO `command` VALUES ('npc', '570', 'Syntax: .npc $subcommand\nType .npc to see the list of possible subcommands or .help npc $subcommand to see info on subcommands');
INSERT INTO `command` VALUES ('npc add', '571', 'Syntax: .npc add #creatureid\r\n\r\nSpawn a creature by the given template id of #creatureid.');
INSERT INTO `command` VALUES ('pdump load', '289', 'Syntax: .pdump load $filename $account [$newname] [$newguid]\r\nLoad character dump from dump file into character list of $account with saved or $newname, with saved (or first free) or $newguid guid.');
INSERT INTO `command` VALUES ('pdump write', '290', 'Syntax: .pdump write $filename $playerNameOrGUID\r\nWrite character dump with name/guid $playerNameOrGUID to file $filename.');
INSERT INTO `command` VALUES ('pdump', '288', 'Syntax: .pdump $subcommand\nType .pdump to see the list of possible subcommands or .help pdump $subcommand to see info on subcommands');
INSERT INTO `command` VALUES ('pet create', '480', 'Syntax: .pet create\r\n\r\nCreates a pet of the selected creature.');
INSERT INTO `command` VALUES ('pet learn', '481', 'Syntax: .pet learn\r\n\r\nLearn #spellid to pet.');
INSERT INTO `command` VALUES ('reload spell_proc', '699', 'Syntax: .reload spell_proc\nReload spell_proc table.');
INSERT INTO `command` VALUES ('pet unlearn', '482', 'Syntax: .pet unlean\r\n\r\nunLearn #spellid to pet.');
INSERT INTO `command` VALUES ('pet', '479', 'Syntax: .pet $subcommand\nType .pet to see the list of possible subcommands or .help pet $subcommand to see info on subcommands');
INSERT INTO `command` VALUES ('pinfo', '517', 'Syntax: .pinfo [$player_name/#GUID]\r\n\r\nOutput account information and guild information for selected player or player find by $player_name or #GUID.');
INSERT INTO `command` VALUES ('playall', '518', 'Syntax: .playall #soundid\r\n\r\nPlayer a sound to whole server.');
INSERT INTO `command` VALUES ('possess', '519', 'Syntax: .possess\r\n\r\nPossesses indefinitely the selected creature.');
INSERT INTO `command` VALUES ('quest add', '603', 'Syntax: .quest add #quest_id\r\n\r\nAdd to character quest log quest #quest_id. Quest started from item can\'t be added by this command but correct .additem call provided in command output.');
INSERT INTO `command` VALUES ('quest complete', '604', 'Syntax: .quest complete #questid\r\nMark all quest objectives as completed for target character active quest. After this target character can go and get quest reward.');
INSERT INTO `command` VALUES ('quest remove', '605', 'Syntax: .quest remove #quest_id\r\n\r\nSet quest #quest_id state to not completed and not active (and remove from active quest list) for selected player.');
INSERT INTO `command` VALUES ('quest', '602', 'Syntax: .quest $subcommand\nType .quest to see the list of possible subcommands or .help quest $subcommand to see info on subcommands');
INSERT INTO `command` VALUES ('recall', '520', 'Syntax: .recall [$playername]\r\n\r\nTeleport $playername or selected player to the place where he has been before last use of a teleportation command. If no $playername is entered and no player is selected, it will teleport you.');
INSERT INTO `command` VALUES ('reload all quest', '620', 'Syntax: .reload all quest\r\n\r\nReload all quest related tables if reload support added for this table and this table can be _safe_ reloaded.');
INSERT INTO `command` VALUES ('reload all npc', '619', 'Syntax: .reload all npc\nReload npc_option, npc_trainer, npc vendor, points of interest tables.');
INSERT INTO `command` VALUES ('reload all loot', '618', 'Syntax: .reload all loot\r\n\r\nReload all `*_loot_template` tables. This can be slow operation with lags for server run.');
INSERT INTO `command` VALUES ('reload all item', '616', 'Syntax: .reload all item\nReload page_text, item_enchantment_table tables.');
INSERT INTO `command` VALUES ('reload all locales', '617', 'Syntax: .reload all locales\r\n\r\nReload all `locales_*` tables with reload support added and that can be _safe_ reloaded.');
INSERT INTO `command` VALUES ('reload all gossips', '615', 'Syntax: .reload all gossips\nReload gossip_menu, gossip_menu_option, gossip_scripts, points_of_interest tables.');
INSERT INTO `command` VALUES ('reload all', '611', 'Syntax: .reload all\r\n\r\nReload all tables with reload support added and that can be _safe_ reloaded.');
INSERT INTO `command` VALUES ('reload areatrigger_involvedrelation', '623', 'Syntax: .reload areatrigger_involvedrelation\nReload areatrigger_involvedrelation table.');
INSERT INTO `command` VALUES ('reload areatrigger_tavern', '624', 'Syntax: .reload areatrigger_tavern\nReload areatrigger_tavern table.');
INSERT INTO `command` VALUES ('reload areatrigger_teleport', '625', 'Syntax: .reload areatrigger_teleport\nReload areatrigger_teleport table.');
INSERT INTO `command` VALUES ('reload autobroadcast', '627', 'Syntax: .reload autobroadcast\nReload autobroadcast table.');
INSERT INTO `command` VALUES ('reload command', '628', 'Syntax: .reload command\nReload command table.');
INSERT INTO `command` VALUES ('reload config', '630', 'Syntax: .reload config\r\n\r\nReload config settings (by default stored in trinityd.conf). Not all settings can be change at reload: some new setting values will be ignored until restart, some values will applied with delay or only to new objects/maps, some values will explicitly rejected to change at reload.');
INSERT INTO `command` VALUES ('reload creature_questender', '634', 'Syntax: .reload creature_questender\nReload creature_questender table.');
INSERT INTO `command` VALUES ('reload creature_linked_respawn', '635', 'Syntax: .reload creature_linked_respawn\r\nReload creature_linked_respawn table.');
INSERT INTO `command` VALUES ('reload creature_loot_template', '636', 'Syntax: .reload creature_loot_template\nReload creature_loot_template table.');
INSERT INTO `command` VALUES ('reload creature_queststarter', '638', 'Syntax: .reload creature_queststarter\nReload creature_queststarter table.');
INSERT INTO `command` VALUES ('reload disenchant_loot_template', '642', 'Syntax: .reload disenchant_loot_template\nReload disenchant_loot_template table.');
INSERT INTO `command` VALUES ('reload event_scripts', '643', 'Syntax: .reload event_scripts\nReload event_scripts table.');
INSERT INTO `command` VALUES ('reload fishing_loot_template', '644', 'Syntax: .reload fishing_loot_template\nReload fishing_loot_template table.');
INSERT INTO `command` VALUES ('reload game_graveyard_zone', '645', 'Syntax: .reload game_graveyard_zone\nReload game_graveyard_zone table.');
INSERT INTO `command` VALUES ('reload game_tele', '646', 'Syntax: .reload game_tele\nReload game_tele table.');
INSERT INTO `command` VALUES ('reload gameobject_loot_template', '648', 'Syntax: .reload gameobject_loot_template\nReload gameobject_loot_template table.');
INSERT INTO `command` VALUES ('reload gameobject_queststarter', '649', 'Syntax: .reload gameobject_queststarter\nReload gameobject_queststarter table.');
INSERT INTO `command` VALUES ('reload gm_tickets', '650', 'Syntax: .reload gm_tickets\nReload gm_tickets table.');
INSERT INTO `command` VALUES ('reload item_enchantment_template', '653', 'Syntax: .reload item_enchantment_template\nReload item_enchantment_template table.');
INSERT INTO `command` VALUES ('reload item_loot_template', '654', 'Syntax: .reload item_loot_template\nReload item_loot_template table.');
INSERT INTO `command` VALUES ('reload locales_creature', '658', 'Syntax: .reload locales_creature\nReload locales_creature table.');
INSERT INTO `command` VALUES ('reload locales_gameobject', '660', 'Syntax: .reload locales_gameobject\nReload locales_gameobject table.');
INSERT INTO `command` VALUES ('reload locales_item', '662', 'Syntax: .reload locales_item\nReload locales_item table.');
INSERT INTO `command` VALUES ('reload locales_npc_text', '664', 'Syntax: .reload locales_npc_text\nReload locales_npc_text table.');
INSERT INTO `command` VALUES ('reload locales_page_text', '665', 'Syntax: .reload locales_page_text\nReload locales_page_text table.');
INSERT INTO `command` VALUES ('reload locales_points_of_interest', '666', 'Syntax: .reload locales_points_of_interest\nReload locales_point_of_interest table.');
INSERT INTO `command` VALUES ('reload locales_quest', '667', 'Syntax: .reload locales_quest\nReload locales_quest table.');
INSERT INTO `command` VALUES ('reload milling_loot_template', '670', 'Syntax: .reload milling_loot_template\nReload milling_loot_template table.');
INSERT INTO `command` VALUES ('reload npc_trainer', '672', 'Syntax: .reload npc_trainer\nReload npc_trainer table.');
INSERT INTO `command` VALUES ('reload npc_vendor', '673', 'Syntax: .reload npc_vendor\nReload npc_vendor table.');
INSERT INTO `command` VALUES ('reload page_text', '674', 'Syntax: .reload page_text\nReload page_text table.');
INSERT INTO `command` VALUES ('reload pickpocketing_loot_template', '675', 'Syntax: .reload pickpocketing_loot_template\nReload pickpocketing_loot_template table.');
INSERT INTO `command` VALUES ('reload points_of_interest', '676', 'Syntax: .reload points_of_interest\nReload points_of_interest table.');
INSERT INTO `command` VALUES ('reload prospecting_loot_template', '677', 'Syntax: .reload prospecting_loot_template\nReload prospecting_loot_template table.');
INSERT INTO `command` VALUES ('lookup spell id', '457', 'Syntax: .lookup spell id #spellid\n\nLooks up a spell by #spellid, and returns the match with its spell name.');
INSERT INTO `command` VALUES ('reload mail_loot_template', '669', 'Syntax: .reload quest_mail_loot_template\nReload quest_mail_loot_template table.');
INSERT INTO `command` VALUES ('reload quest_template', '679', 'Syntax: .reload quest_template\nReload quest_template table.');
INSERT INTO `command` VALUES ('reload reference_loot_template', '681', 'Syntax: .reload reference_loot_template\nReload reference_loot_template table.');
INSERT INTO `command` VALUES ('reload reserved_name', '682', 'Syntax: .reload reserved_name\nReload reserved_name table.');
INSERT INTO `command` VALUES ('reload skill_discovery_template', '685', 'Syntax: .reload skill_discovery_template\nReload skill_discovery_template table.');
INSERT INTO `command` VALUES ('reload skill_extra_item_template', '686', 'Syntax: .reload skill_extra_item_template\nReload skill_extra_item_template table.');
INSERT INTO `command` VALUES ('reload skill_fishing_base_level', '687', 'Syntax: .reload skill_fishing_base_level\nReload skill_fishing_base_level table.');
INSERT INTO `command` VALUES ('reload skinning_loot_template', '688', 'Syntax: .reload skinning_loot_template\nReload skinning_loot_template table.');
INSERT INTO `command` VALUES ('reload spell_area', '691', 'Syntax: .reload spell_area\nReload spell_area table.');
INSERT INTO `command` VALUES ('reload spell_bonus_data', '692', 'Syntax: .reload spell_bonus_data\nReload spell_bonus_data table.');
INSERT INTO `command` VALUES ('reload disables', '641', 'Syntax: .reload disables\r\nReload disables table.');
INSERT INTO `command` VALUES ('reload spell_group_stack_rules', '703', 'Syntax: .reload spell_group\nReload spell_group_stack_rules table.');
INSERT INTO `command` VALUES ('reload spell_learn_spell', '694', 'Syntax: .reload spell_learn_spell\nReload spell_learn_spell table.');
INSERT INTO `command` VALUES ('reload spell_linked_spell', '696', 'Usage: .reload spell_linked_spell\r\nReloads the spell_linked_spell DB table.');
INSERT INTO `command` VALUES ('reload spell_loot_template', '695', 'Syntax: .reload spell_loot_template\nReload spell_loot_template table.');
INSERT INTO `command` VALUES ('reload spell_pet_auras', '697', 'Syntax: .reload spell_pet_auras\nReload spell_pet_auras table.');
INSERT INTO `command` VALUES ('reload spell_proc_event', '698', 'Syntax: .reload spell_proc_event\nReload spell_proc_event table.');
INSERT INTO `command` VALUES ('reload spell_required', '690', 'Syntax: .reload spell_required\nReload spell_required table.');
INSERT INTO `command` VALUES ('reload spell_scripts', '700', 'Syntax: .reload spell_scripts\nReload spell_scripts table.');
INSERT INTO `command` VALUES ('reload spell_target_position', '701', 'Syntax: .reload spell_target_position\nReload spell_target_position table.');
INSERT INTO `command` VALUES ('reload spell_threats', '702', 'Syntax: .reload spell_threats\nReload spell_threats table.');
INSERT INTO `command` VALUES ('reload trinity_string', '704', 'Syntax: .reload trinity_string\nReload trinity_string table.');
INSERT INTO `command` VALUES ('reload waypoint_scripts', '706', 'Syntax: .reload waypoint_scripts\nReload waypoint_scripts table.');
INSERT INTO `command` VALUES ('reload', '607', 'Syntax: .reload $subcommand\nType .reload to see the list of possible subcommands or .help reload $subcommand to see info on subcommands');
INSERT INTO `command` VALUES ('repairitems', '521', 'Syntax: .repairitems\r\n\r\nRepair all selected player\'s items.');
INSERT INTO `command` VALUES ('reset achievements', '711', 'Syntax: .reset achievements [$playername]\r\n\r\nReset achievements data for selected or named (online or offline) character. Achievements for persistance progress data like completed quests/etc re-filled at reset. Achievements for events like kills/casts/etc will lost.');
INSERT INTO `command` VALUES ('reset all', '717', 'Syntax: .reset all spells\r\n\r\nSyntax: .reset all talents\r\n\r\nRequest reset spells or talents (including talents for all character\'s pets if any) at next login each existed character.');
INSERT INTO `command` VALUES ('reset honor', '712', 'Syntax: .reset honor [Playername]\r\n  Reset all honor data for targeted character.');
INSERT INTO `command` VALUES ('reset level', '713', 'Syntax: .reset level [Playername]\r\n  Reset level to 1 including reset stats and talents.  Equipped items with greater level requirement can be lost.');
INSERT INTO `command` VALUES ('reset spells', '714', 'Syntax: .reset spells [Playername]\r\n  Removes all non-original spells from spellbook.\r\n. Playername can be name of offline character.');
INSERT INTO `command` VALUES ('reset stats', '715', 'Syntax: .reset stats [Playername]\r\n  Resets(recalculate) all stats of the targeted player to their original VALUESat current level.');
INSERT INTO `command` VALUES ('reset talents', '716', 'Syntax: .reset talents [Playername]\r\n  Removes all talents of the targeted player or pet or named player. Playername can be name of offline character. With player talents also will be reset talents for all character\'s pets if any.');
INSERT INTO `command` VALUES ('reset', '710', 'Syntax: .reset $subcommand\nType .reset to see the list of possible subcommands or .help reset $subcommand to see info on subcommands');
INSERT INTO `command` VALUES ('respawn', '522', 'Syntax: .respawn\r\n\r\nRespawn all nearest creatures and GO without waiting respawn time expiration.');
INSERT INTO `command` VALUES ('revive', '523', 'Syntax: .revive\r\n\r\nRevive the selected player. If no player is selected, it will revive you.');
INSERT INTO `command` VALUES ('save', '525', 'Syntax: .save\r\n\r\nSaves your character.');
INSERT INTO `command` VALUES ('saveall', '524', 'Syntax: .saveall\r\n\r\nSave all characters in game.');
INSERT INTO `command` VALUES ('send items', '484', 'Syntax: .send items #playername \"#subject\" \"#text\" itemid1[:count1] itemid2[:count2] ... itemidN[:countN]\r\n\r\nSend a mail to a player. Subject and mail text must be in \"\". If for itemid not provided related count values then expected 1, if count > max items in stack then items will be send in required amount stacks. All stacks amount in mail limited to 12.');
INSERT INTO `command` VALUES ('send mail', '485', 'Syntax: .send mail #playername \"#subject\" \"#text\"\r\n\r\nSend a mail to a player. Subject and mail text must be in \"\".');
INSERT INTO `command` VALUES ('send message', '486', 'Syntax: .send message $playername $message\r\n\r\nSend screen message to player from ADMINISTRATOR.');
INSERT INTO `command` VALUES ('send money', '487', 'Syntax: .send money #playername \"#subject\" \"#text\" #money\r\n\r\nSend mail with money to a player. Subject and mail text must be in \"\".');
INSERT INTO `command` VALUES ('server corpses', '719', 'Syntax: .server corpses\r\n\r\nTriggering corpses expire check in world.');
INSERT INTO `command` VALUES ('server exit', '720', 'Syntax: .server exit\r\n\r\nTerminate trinity-core NOW. Exit code 0.');
INSERT INTO `command` VALUES ('server idlerestart cancel', '722', 'Syntax: .server idlerestart cancel\r\n\r\nCancel the restart/shutdown timer if any.');
INSERT INTO `command` VALUES ('server idlerestart', '721', 'Syntax: .server idlerestart #delay\r\n\r\nRestart the server after #delay seconds if no active connections are present (no players). Use #exist_code or 2 as program exist code.');
INSERT INTO `command` VALUES ('server idleshutdown cancel', '724', 'Syntax: .server idleshutdown cancel\r\n\r\nCancel the restart/shutdown timer if any.');
INSERT INTO `command` VALUES ('server idleshutdown', '723', 'Syntax: .server idleshutdown #delay [#exist_code]\r\n\r\nShut the server down after #delay seconds if no active connections are present (no players). Use #exist_code or 0 as program exist code.');
INSERT INTO `command` VALUES ('server info', '725', 'Syntax: .server info\r\n\r\nDisplay server version and the number of connected players.');
INSERT INTO `command` VALUES ('server motd', '736', 'Syntax: .server motd\r\n\r\nShow server Message of the day.');
INSERT INTO `command` VALUES ('server plimit', '726', 'Syntax: .server plimit [#num|-1|-2|-3|reset|player|moderator|gamemaster|administrator]\r\n\r\nWithout arg show current player amount and security level limitations for login to server, with arg set player linit ($num > 0) or securiti limitation ($num < 0 or security leme name. With `reset` sets player limit to the one in the config file');
INSERT INTO `command` VALUES ('server restart cancel', '728', 'Syntax: .server restart cancel\r\n\r\nCancel the restart/shutdown timer if any.');
INSERT INTO `command` VALUES ('server restart', '727', 'Syntax: .server restart #delay\r\n\r\nRestart the server after #delay seconds. Use #exist_code or 2 as program exist code.');
INSERT INTO `command` VALUES ('server set closed', '730', 'Syntax: server set closed on/off\r\n\r\nSets whether the world accepts new client connectsions.');
INSERT INTO `command` VALUES ('server set motd', '733', 'Syntax: .server set motd $MOTD\r\n\r\nSet server Message of the day.');
INSERT INTO `command` VALUES ('server shutdown cancel', '735', 'Syntax: .server shutdown cancel\r\n\r\nCancel the restart/shutdown timer if any.');
INSERT INTO `command` VALUES ('server shutdown', '734', 'Syntax: .server shutdown #delay [#exit_code]\r\n\r\nShut the server down after #delay seconds. Use #exit_code or 0 as program exit code.');
INSERT INTO `command` VALUES ('server', '718', 'Syntax: .server $subcommand\nType .server to see the list of possible subcommands or .help server $subcommand to see info on subcommands');
INSERT INTO `command` VALUES ('setskill', '526', 'Syntax: .setskill #skill #level [#max]\r\n\r\nSet a skill of id #skill with a current skill value of #level and a maximum value of #max (or equal current maximum if not provide) for the selected character. If no character is selected, you learn the skill.');
INSERT INTO `command` VALUES ('showarea', '527', 'Syntax: .showarea #areaid\r\n\r\nReveal the area of #areaid to the selected character. If no character is selected, reveal this area to you.');
INSERT INTO `command` VALUES ('unstuck', '534', 'Syntax: .unstuck $playername [inn/graveyard/startzone]\n\nTeleports specified player to specified location. Default location is player\'s current hearth location.');
INSERT INTO `command` VALUES ('cheat god', '295', 'Syntax: .cheat god [on/off]\r\nEnables or disables your character\'s ability to take damage.');
INSERT INTO `command` VALUES ('cheat casttime', '292', 'Syntax: .cheat casttime [on/off]\r\nEnables or disables your character\'s spell cast times.');
INSERT INTO `command` VALUES ('tele add', '738', 'Syntax: .tele add $name\r\n\r\nAdd current your position to .tele command target locations list with name $name.');
INSERT INTO `command` VALUES ('tele del', '739', 'Syntax: .tele del $name\r\n\r\nRemove location with name $name for .tele command locations list.');
INSERT INTO `command` VALUES ('tele group', '741', 'Syntax: .tele group#location\r\n\r\nTeleport a selected player and his group members to a given location.');
INSERT INTO `command` VALUES ('tele name', '740', 'Syntax: .tele name [#playername] #location\n\nTeleport the given character to a given location. Character can be offline.\n\nTo teleport to homebind, set #location to \"$home\" (without quotes).');
INSERT INTO `command` VALUES ('tele', '737', 'Syntax: .tele #location\r\n\r\nTeleport player to a given location.');
INSERT INTO `command` VALUES ('ticket assign', '743', 'Usage: .ticket assign $ticketid $gmname.\r\nAssigns the specified ticket to the specified Game Master.');
INSERT INTO `command` VALUES ('ticket close', '744', 'Usage: .ticket close $ticketid.\r\nCloses the specified ticket. Does not delete permanently.');
INSERT INTO `command` VALUES ('ticket closedlist', '745', 'Displays a list of closed GM tickets.');
INSERT INTO `command` VALUES ('ticket comment', '746', 'Usage: .ticket comment $ticketid $comment.\r\nAllows the adding or modifying of a comment to the specified ticket.');
INSERT INTO `command` VALUES ('ticket delete', '748', 'Usage: .ticket delete $ticketid.\r\nDeletes the specified ticket permanently. Ticket must be closed first.');
INSERT INTO `command` VALUES ('ticket list', '751', 'Displays a list of open GM tickets.');
INSERT INTO `command` VALUES ('ticket onlinelist', '752', 'Displays a list of open GM tickets whose owner is online.');
INSERT INTO `command` VALUES ('ticket unassign', '758', 'Usage: .ticket unassign $ticketid.\r\nUnassigns the specified ticket from the current assigned Game Master.');
INSERT INTO `command` VALUES ('ticket viewid', '759', 'Usage: .ticket viewid $ticketid.\r\nReturns details about specified ticket. Ticket must be open and not deleted.');
INSERT INTO `command` VALUES ('ticket viewname', '760', 'Usage: .ticket viewname $creatorname. \r\nReturns details about specified ticket. Ticket must be open and not deleted.');
INSERT INTO `command` VALUES ('ticket', '742', 'Syntax: .ticket $subcommand\nType .ticket to see the list of possible subcommands or .help ticket $subcommand to see info on subcommands');
INSERT INTO `command` VALUES ('unaura', '529', 'Syntax: .unaura #spellid\r\n\r\nRemove aura due to spell #spellid from the selected Unit.');
INSERT INTO `command` VALUES ('unban account', '253', 'Syntax: .unban account $Name\r\nUnban accounts for account name pattern.');
INSERT INTO `command` VALUES ('unban character', '254', 'Syntax: .unban character $Name\r\nUnban accounts for character name pattern.');
INSERT INTO `command` VALUES ('unban ip', '255', 'Syntax : .unban ip $Ip\r\nUnban accounts for IP pattern.');
INSERT INTO `command` VALUES ('unban', '252', 'Syntax: .unban $subcommand\nType .unban to see the list of possible subcommands or .help unban $subcommand to see info on subcommands');
INSERT INTO `command` VALUES ('unbindsight', '530', 'Syntax: .unbindsight\r\n\r\nRemoves bound vision. Cannot be used while currently possessing a target.');
INSERT INTO `command` VALUES ('unfreeze', '531', 'Syntax: .unfreeze (#player)\r\n\"Unfreezes\" #player and enables his chat again. When using this without #name it will unfreeze your target.');
INSERT INTO `command` VALUES ('unlearn', '429', 'Syntax: .unlearn #spell [all]\r\n\r\nUnlearn for selected player a spell #spell.  If \'all\' provided then all ranks unlearned.');
INSERT INTO `command` VALUES ('unmute', '532', 'Syntax: .unmute [$playerName]\r\n\r\nRestore chat messaging for any character from account of character $playerName (or selected). Character can be ofline.');
INSERT INTO `command` VALUES ('unpossess', '533', 'Syntax: .unpossess\r\n\r\nIf you are possessed, unpossesses yourself; otherwise unpossesses current possessed target.');
INSERT INTO `command` VALUES ('cheat', '291', 'Syntax: .cheat $subcommand\r\nType .cheat to see the list of possible subcommands or .help cheat $subcommand to see info on subcommands');
INSERT INTO `command` VALUES ('wchange', '535', 'Syntax: .wchange #weathertype #status\r\n\r\nSet current weather to #weathertype with an intensity of #status.\r\n\r\n#weathertype can be 1 for rain, 2 for snow, and 3 for sand. #status can be 0 for disabled, and 1 for enabled.');
INSERT INTO `command` VALUES ('whispers', '471', 'Syntax: .whispers on|off\r\nEnable/disable accepting whispers by GM from players. By default use trinityd.conf setting.');
INSERT INTO `command` VALUES ('wp event', '769', 'Syntax: .wp event $subcommand\nType .path event to see the list of possible subcommands or .help path event $subcommand to see info on subcommands.');
INSERT INTO `command` VALUES ('wp load', '770', 'Syntax: .wp load $pathid\nLoad pathid number for selected creature. Creature must have no waypoint data.');
INSERT INTO `command` VALUES ('wp show', '774', 'Syntax: .wp show $option\nOptions:\non $pathid (or selected creature with loaded path) - Show path\noff - Hide path\ninfo $slected_waypoint - Show info for selected waypoint.');
INSERT INTO `command` VALUES ('wp unload', '772', 'Syntax: .wp unload\nUnload path for selected creature.');
INSERT INTO `command` VALUES ('account addon', '218', 'Syntax: .account addon #addon\nSet expansion addon level allowed. Addon values: 0 - normal, 1 - tbc, 2 - wotlk, 3 - cata.');
INSERT INTO `command` VALUES ('titles remove', '764', 'Syntax: .titles remove #title\r\nRemove title #title (id or shift-link) from known titles list for selected player.');
INSERT INTO `command` VALUES ('titles current', '763', 'Syntax: .titles current #title\r\nSet title #title (id or shift-link) as current selected titl for selected player. If title not in known title list for player then it will be added to list.');
INSERT INTO `command` VALUES ('titles add', '762', 'Syntax: .titles add #title\r\nAdd title #title (id or shift-link) to known titles list for selected player.');
INSERT INTO `command` VALUES ('titles set mask', '766', 'Syntax: .titles set mask #mask\r\n\r\nAllows user to use all titles from #mask.\r\n\r\n #mask=0 disables the title-choose-field');
INSERT INTO `command` VALUES ('lookup title', '460', 'Syntax: .lookup title $$namepart\r\n\r\nLooks up a title by $namepart, and returns all matches with their title ID\'s and index\'s.');
INSERT INTO `command` VALUES ('channel set ownership', '465', 'Syntax: .channel set ownership $channel [on/off]\n\nGrant ownership to the first person that joins the channel.');
INSERT INTO `command` VALUES ('gobject info', '392', 'Syntax: .gobject info [$object_entry]\r \r Query Gameobject information for selected gameobject or given entry.');
INSERT INTO `command` VALUES ('reload creature_template', '640', 'Syntax: .reload creature_template $entry\r\nReload the specified creature\'s template.');
INSERT INTO `command` VALUES ('character deleted delete', '278', 'Syntax: .character deleted delete #guid|$name\r\n\r\nCompletely deletes the selected characters.\r\nIf $name is supplied, only characters with that string in their name will be deleted, if #guid is supplied, only the character with that GUID will be deleted.');
INSERT INTO `command` VALUES ('reload creature_onkill_reputation', '637', 'Syntax: .reload creature_onkill_reputation\r\nReload creature_onkill_reputation table.');
INSERT INTO `command` VALUES ('reload conditions', '629', 'Reload conditions table.');
INSERT INTO `command` VALUES ('character deleted list', '279', 'Syntax: .character deleted list [#guid|$name]\r\n\r\nShows a list with all deleted characters.\r\nIf $name is supplied, only characters with that string in their name will be selected, if #guid is supplied, only the character with that GUID will be selected.');
INSERT INTO `command` VALUES ('character deleted old', '281', 'Syntax: .character deleted old [#keepDays]\r\n\r\nCompletely deletes all characters with deleted time longer #keepDays. If #keepDays not provided the  used value from mangosd.conf option \'CharDelete.KeepDays\'. If referenced config option disabled (use 0 value) then command can\'t be used without #keepDays.');
INSERT INTO `command` VALUES ('character deleted restore', '280', 'Syntax: .character deleted restore #guid|$name [$newname] [#new account]\r\n\r\nRestores deleted characters.\r\nIf $name is supplied, only characters with that string in their name will be restored, if $guid is supplied, only the character with that GUID will be restored.\r\nIf $newname is set, the character will be restored with that name instead of the original one. If #newaccount is set, the character will be restored to specific account character list. This works only with one character!');
INSERT INTO `command` VALUES ('reload gossip_menu', '651', 'Syntax: .reload gossip_menu\nReload gossip_menu table.');
INSERT INTO `command` VALUES ('reload gossip_menu_option', '652', 'Syntax: .reload gossip_menu_option\nReload gossip_menu_option table.');
INSERT INTO `command` VALUES ('cast dest', '272', 'Syntax: .cast dest #spellid #x #y #z [triggered]\r\n  Selected target will cast #spellid at provided destination. If \'trigered\' or part provided then spell casted with triggered flag.');
INSERT INTO `command` VALUES ('reload all scripts', '621', 'Syntax: .reload all scripts\nReload gameobject_scripts, event_scripts, quest_end_scripts, quest_start_scripts, spell_scripts, db_script_string, waypoint_scripts tables.');
INSERT INTO `command` VALUES ('reload locales_gossip_menu_option', '661', 'Syntax: .reload locales_gossip_menu_option\nReload locales_gossip_menu_option table.');
INSERT INTO `command` VALUES ('reload quest_poi', '678', 'Syntax: .reload quest_poi\nReload quest_poi table.');
INSERT INTO `command` VALUES ('reload lfg_dungeon_rewards', '656', 'Syntax: .reload lfg_dungeon_rewards\nReload lfg_dungeon_rewards table.');
INSERT INTO `command` VALUES ('character changefaction', '275', 'Syntax: .character changefaction $name\r\n\r\nChange character faction.');
INSERT INTO `command` VALUES ('character changerace', '276', 'Syntax: .character changerace $name\r\n\r\nChange character race.');
INSERT INTO `command` VALUES ('ban playeraccount', '243', 'Syntax: .ban playeraccount $Name $bantime $reason\nBan account and kick player.\n$bantime: negative value leads to permban, otherwise use a timestring like \"4d20h3s\".');
INSERT INTO `command` VALUES ('achievement add', '231', 'Syntax: .achievement add $achievement\nAdd an achievement to the targeted player.\n$achievement: can be either achievement id or achievement link');
INSERT INTO `command` VALUES ('achievement', '230', 'Syntax: .achievement $subcommand\nType .achievement to see the list of possible subcommands or .help achievement $subcommand to see info on subcommands');
INSERT INTO `command` VALUES ('reload creature_text', '631', 'Syntax: .reload creature_text\r\nReload creature_text table.');
INSERT INTO `command` VALUES ('debug areatriggers', '302', 'Syntax: .debug areatriggers\nToggle debug mode for areatriggers. In debug mode GM will be notified if reaching an areatrigger');
INSERT INTO `command` VALUES ('learn all recipes', '428', 'Syntax: .learn all recipes [$profession]\r\rLearns all recipes of specified profession and sets skill level to max.\rExample: .learn all recipes enchanting');
INSERT INTO `command` VALUES ('npc set spawndist', '590', 'Syntax: .npc set spawndist #dist\r\n\r\nAdjust spawndistance of selected creature to dist.');
INSERT INTO `command` VALUES ('npc set spawntime', '591', 'Syntax: .npc set spawntime #time \r\n\r\nAdjust spawntime of selected creature to time.');
INSERT INTO `command` VALUES ('npc add temp', '575', 'Syntax: .npc add temp\r\n\r\nAdds temporary NPC, not saved to database.');
INSERT INTO `command` VALUES ('npc textemote', '598', 'Syntax: .npc textemote #emoteid\r\n\r\nMake the selected creature to do textemote with an emote of id #emoteid.');
INSERT INTO `command` VALUES ('npc whisper', '599', 'Syntax: .npc whisper #playerguid #text\r\nMake the selected npc whisper #text to  #playerguid.');
INSERT INTO `command` VALUES ('npc yell', '600', 'Syntax: .npc yell $message\nMake selected creature yell specified message.');
INSERT INTO `command` VALUES ('wp add', '768', 'Syntax: .wp add\r\n\r\nAdd a waypoint for the selected creature at your current position.');
INSERT INTO `command` VALUES ('reload all spell', '622', 'Syntax: .reload all spell\r\n\r\nReload all `spell_*` tables with reload support added and that can be _safe_ reloaded.');
INSERT INTO `command` VALUES ('server set loglevel', '732', 'Syntax: .server set loglevel $facility $name $loglevel. $facility can take the values: appender (a) or logger (l). $loglevel can take the values: disabled (0), trace (1), debug (2), info (3), warn (4), error (5) or fatal (6)');
INSERT INTO `command` VALUES ('reload access_requirement', '608', 'Syntax: .reload access_requirement\nReload access_requirement table.');
INSERT INTO `command` VALUES ('reload achievement_criteria_data', '609', 'Syntax: .reload achievement_criteria_data\nReload achievement_criteria_data table.');
INSERT INTO `command` VALUES ('reload achievement_reward', '610', 'Syntax: .reload achievement_reward\nReload achievement_reward table.');
INSERT INTO `command` VALUES ('reload all achievement', '612', 'Syntax: .reload all achievement\r\n\r\nReload achievement_reward, achievement_criteria_data tables.');
INSERT INTO `command` VALUES ('reload all area', '613', 'Syntax: .reload all area\r\n\r\nReload areatrigger_teleport, areatrigger_tavern, game_graveyard_zone tables.');
INSERT INTO `command` VALUES ('reload auctions', '626', 'Syntax: .reload auctions\nReload dynamic data tables from the database.');
INSERT INTO `command` VALUES ('reload mail_level_reward', '668', 'Syntax: .reload mail_level_reward\nReload mail_level_reward table.');
INSERT INTO `command` VALUES ('reload smart_scripts', '689', 'Syntax: .reload smart_scripts\nReload smart_scripts table.');
INSERT INTO `command` VALUES ('reload vehicle_accessory', '708', 'Syntax: .reload vehicle_accessory\n\nReloads GUID-based vehicle accessory definitions from the database.');
INSERT INTO `command` VALUES ('reload vehicle_template_accessory', '709', 'Syntax: .reload vehicle_template_accessory\n\nReloads entry-based vehicle accessory definitions from the database.');
INSERT INTO `command` VALUES ('dev', '499', 'Syntax: .dev [on/off]\r\n\r\nEnable or Disable in game Dev tag or show current state if on/off not provided.');
INSERT INTO `command` VALUES ('ticket reset', '753', 'Syntax: .ticket reset\nRemoves all closed tickets and resets the counter, if no pending open tickets are existing.');
INSERT INTO `command` VALUES ('reload waypoint_data', '707', 'Syntax: .reload waypoint_data will reload waypoint_data table.');
INSERT INTO `command` VALUES ('group', '472', 'Syntax: .group $subcommand\nType .group to see the list of possible subcommands or .help group $subcommand to see info on subcommands');
INSERT INTO `command` VALUES ('group leader', '473', 'Syntax: .group leader [$characterName]\n\nSets the given character as his group\'s leader.');
INSERT INTO `command` VALUES ('group disband', '474', 'Syntax: .group disband [$characterName]\n\nDisbands the given character\'s group.');
INSERT INTO `command` VALUES ('group remove', '475', 'Syntax: .group remove [$characterName]\n\nRemoves the given character from his group.');
INSERT INTO `command` VALUES ('debug moveflags', '314', 'Syntax: .debug moveflags [$newMoveFlags [$newMoveFlags2]]\r\nNo params given will output the current moveflags of the target');
INSERT INTO `command` VALUES ('reload locales_creature_text', '659', 'Syntax: .reload locales_creature_text\nReload locales_creature_text Table.');
INSERT INTO `command` VALUES ('morph', '542', 'Syntax: .morph #displayid\r\n\r\nChange your current model id to #displayid.');
INSERT INTO `command` VALUES ('npc set data', '592', 'Syntax: .npc set data $field $data\nSets data for the selected creature. Used for testing Scripting');
INSERT INTO `command` VALUES ('disable add quest', '355', 'Syntax: .disable add quest $entry $flag $comment');
INSERT INTO `command` VALUES ('disable add map', '352', 'Syntax: .disable add map $entry $flag $comment');
INSERT INTO `command` VALUES ('disable add battleground', '351', 'Syntax: .disable add battleground $entry $flag $comment');
INSERT INTO `command` VALUES ('disable add achievement_criteria', '350', 'Syntax: .disable add achievement_criteria $entry $flag $comment');
INSERT INTO `command` VALUES ('disable add spell', '356', 'Syntax: .disable add spell $entry $flag $comment');
INSERT INTO `command` VALUES ('disable add outdoorpvp', '354', 'Syntax: .disable add outdoorpvp $entry $flag $comment');
INSERT INTO `command` VALUES ('disable add vmap', '357', 'Syntax: .disable add vmap $entry $flag $comment');
INSERT INTO `command` VALUES ('disable remove quest', '364', 'Syntax: .disable remove quest $entry');
INSERT INTO `command` VALUES ('disable remove map', '361', 'Syntax: .disable remove map $entry');
INSERT INTO `command` VALUES ('disable remove battleground', '360', 'Syntax: .disable remove battleground $entry');
INSERT INTO `command` VALUES ('disable remove achievement_criteria', '359', 'Syntax: .disable remove achievement_criteria $entry');
INSERT INTO `command` VALUES ('disable remove spell', '365', 'Syntax: .disable remove spell $entry');
INSERT INTO `command` VALUES ('disable remove outdoorpvp', '363', 'Syntax: .disable remove outdoorpvp $entry');
INSERT INTO `command` VALUES ('disable remove vmap', '366', 'Syntax: .disable remove vmap $entry');
INSERT INTO `command` VALUES ('bf start', '258', 'Syntax: .bf start #battleid');
INSERT INTO `command` VALUES ('bf stop', '259', 'Syntax: .bf stop #battleid');
INSERT INTO `command` VALUES ('bf enable', '262', 'Syntax: .bf enable #battleid');
INSERT INTO `command` VALUES ('bf switch', '260', 'Syntax: .bf switch #battleid');
INSERT INTO `command` VALUES ('bf timer', '261', 'Syntax: .bf timer #battleid #timer');
INSERT INTO `command` VALUES ('quest reward', '606', 'Syntax: .quest reward #questId\n\nGrants quest reward to selected player and removes quest from his log (quest must be in completed state).');
INSERT INTO `command` VALUES ('cheat waterwalk', '299', 'Syntax: .cheat waterwalk on/off\r\nSet on/off waterwalk state for selected player or self if no player selected.');
INSERT INTO `command` VALUES ('cheat explore', '294', 'Syntax: .cheat explore #flag\r\nReveal or hide all maps for the selected player. If no player is selected, hide or reveal maps to you.\r\nUse a #flag of value 1 to reveal, use a #flag value of 0 to hide all maps.');
INSERT INTO `command` VALUES ('cheat taxi', '298', 'Syntax: .cheat taxi on/off\r\nTemporary grant access or remove to all taxi routes for the selected character.\r\n If no character is selected, hide or reveal all routes to you.Visited taxi nodes sill accessible after removing access.');
INSERT INTO `command` VALUES ('cheat status', '297', 'Syntax: .cheat status \n\nShows the cheats you currently have enabled.');
INSERT INTO `command` VALUES ('debug phase', '776', 'Syntax: .debug phase\r\n\r\nSends a phase debug report of a player to you.');
INSERT INTO `command` VALUES ('lfg player', '431', 'Syntax: .lfg player\n Shows information about player (state, roles, comment, dungeons selected).');
INSERT INTO `command` VALUES ('lfg group', '432', 'Syntax: .lfg group\n Shows information about all players in the group  (state, roles, comment, dungeons selected).');
INSERT INTO `command` VALUES ('lfg queue', '433', 'Syntax: .lfg queue\n Shows info about current lfg queues.');
INSERT INTO `command` VALUES ('lfg clean', '434', 'Syntax: .flg clean\n Cleans current queue, only for debugging purposes.');
INSERT INTO `command` VALUES ('lfg options', '435', 'Syntax: .lfg options [new value]\n Shows current lfg options. New value is set if extra param is present.');
INSERT INTO `command` VALUES ('mmap', '536', 'Syntax: Syntax: .mmaps $subcommand Type .mmaps to see the list of possible subcommands or .help mmaps $subcommand to see info on subcommands');
INSERT INTO `command` VALUES ('mmap path', '539', 'Syntax: .mmap path to calculate and show a path to current select unit');
INSERT INTO `command` VALUES ('mmap loc', '538', 'Syntax: .mmap loc to print on which tile one is');
INSERT INTO `command` VALUES ('mmap loadedtiles', '537', 'Syntax: .mmap loadedtiles to show which tiles are currently loaded');
INSERT INTO `command` VALUES ('mmap stats', '540', 'Syntax: .mmap stats to show information about current state of mmaps');
INSERT INTO `command` VALUES ('mmap testarea', '541', 'Syntax: .mmap testarea to calculate paths for all nearby npcs to player');
INSERT INTO `command` VALUES ('disable add mmap', '353', 'Syntax: .disable add mmap $entry $flag $comment');
INSERT INTO `command` VALUES ('disable remove mmap', '362', 'Syntax: .disable remove mmap $entry');
INSERT INTO `command` VALUES ('group join', '476', 'Syntax: .group join $AnyCharacterNameFromGroup [$CharacterName] \r\nAdds to group of player $AnyCharacterNameFromGroup player $CharacterName (or selected).');
INSERT INTO `command` VALUES ('group list', '477', 'Syntax: .group list [$CharacterName] \r\nLists all the members of the group/party the player is in.');
INSERT INTO `command` VALUES ('rbac account', '201', 'Syntax: .rbac account [$account]\n\nView permissions of selected player or given account\nNote: Only those that affect current realm\n\nNote: Shows real permissions after checking group and roles');
INSERT INTO `command` VALUES ('reload creature_summon_groups', '639', 'Syntax: .reload creature_summon_groups\nReload creature_summon_groups table.');
INSERT INTO `command` VALUES ('reload rbac', '680', 'Syntax: .reload rbac\nReload rbac system.');
INSERT INTO `command` VALUES ('deserter instance add', '346', 'Syntax: .deserter instance add $time \n\n Adds the instance deserter debuff to your target with $time duration.');
INSERT INTO `command` VALUES ('deserter instance remove', '347', 'Syntax: .deserter instance remove \n\n Removes the instance deserter debuff from your target.');
INSERT INTO `command` VALUES ('deserter bg add', '343', 'Syntax: .deserter bg add $time \n\n Adds the bg deserter debuff to your target with $time duration.');
INSERT INTO `command` VALUES ('deserter bg remove', '344', 'Syntax: .deserter bg remove \n\n Removes the bg deserter debuff from your target.');
INSERT INTO `command` VALUES ('list mail', '441', 'Syntax: .list mail $character\nList of mails the character received.');
INSERT INTO `command` VALUES ('account lock country', '222', 'Syntax: .account lock country [on|off]\nAllow login from account only from current used Country or remove this requirement.');
INSERT INTO `command` VALUES ('guild rename', '407', 'Syntax: .guild rename \"$GuildName\" \"$NewGuildName\" \n\n Rename a guild named $GuildName with $NewGuildName. Guild name and new guild name must in quotes.');
INSERT INTO `command` VALUES ('arena create', '234', 'Syntax: .arena create $name \"arena name\" #type\n\nA command to create a new Arena-team in game. #type  = [2/3/5]');
INSERT INTO `command` VALUES ('arena disband', '235', 'Syntax: .arena disband #TeamID\n\nA command to disband Arena-team in game.');
INSERT INTO `command` VALUES ('arena rename', '238', 'Syntax: .arena rename \"oldname\" \"newname\"\n\nA command to rename Arena-team name.');
INSERT INTO `command` VALUES ('arena captain', '233', 'Syntax: .arena captain #TeamID $name\n\nA command to set new captain to the team $name must be in the team');
INSERT INTO `command` VALUES ('arena info', '236', 'Syntax: .arena info #TeamID\n\nA command that show info about arena team');
INSERT INTO `command` VALUES ('arena lookup', '237', 'Syntax: .arena lookup $name\n\nA command that give a list of arenateam with the given $name');
INSERT INTO `command` VALUES ('reload gameobject_questender', '647', 'Syntax: .reload gameobject_questender\\nReload gameobject_questender table.');
INSERT INTO `command` VALUES ('account set sec regmail', '266', 'Syntax: .account set sec regmail $account $regmail $regmailconfirmation\r\n\r\nSets the regmail for entered player account.');
INSERT INTO `command` VALUES ('account set sec email', '265', 'Syntax: .account set sec email $accountname $email $emailconfirmation\r\n\r\nSet the email for entered player account.');
INSERT INTO `command` VALUES ('account email', '263', 'Syntax: .account email $oldemail $currentpassword $newemail $newemailconfirmation\r\n\r\n Change your account email. You may need to check the actual security mode to see if email input is necessary for password change');
INSERT INTO `command` VALUES ('ticket bug assign', '778', 'Usage: .ticket bug assign $ticketid $gmname.\r\nAssigns the specified ticket to the specified Game Master.');
INSERT INTO `command` VALUES ('ticket bug close', '779', 'Usage: .ticket bug close $ticketid.\r\nCloses the specified ticket. Does not delete permanently.');
INSERT INTO `command` VALUES ('ticket bug closedlist', '780', 'Usage: Displays a list of closed bug tickets.');
INSERT INTO `command` VALUES ('ticket bug comment', '781', 'Usage: .ticket bug comment $ticketid $comment.\r\nAllows the adding or modifying of a comment to the specified ticket.');
INSERT INTO `command` VALUES ('ticket bug delete', '782', 'Usage: .ticket bug delete $ticketid.\r\nDeletes the specified ticket permanently. Ticket must be closed first.');
INSERT INTO `command` VALUES ('ticket bug list', '783', 'Usage: Displays a list of open bug tickets.');
INSERT INTO `command` VALUES ('ticket bug unassign', '784', 'Usage: .ticket bug unassign $ticketid.\r\nUnassigns the specified ticket from the current assigned Game Master.');
INSERT INTO `command` VALUES ('ticket bug view', '785', 'Usage: .ticket bug view $ticketid.\r\nReturns details about specified ticket. Ticket must be open and not deleted.');
INSERT INTO `command` VALUES ('ticket bug reset', '786', 'Usage: Removes all closed bug tickets and resets the counter, if no pending open tickets exist.');
