DELETE FROM `creature_model_info` WHERE `modelid`=30658;
INSERT INTO `creature_model_info` (`modelid`, `bounding_radius`, `combat_reach`, `gender`, `modelid_other_gender`) VALUES (30658, 0.5, 6, 0, 0);
DELETE FROM `creature_model_info` WHERE `modelid`=46724;
INSERT INTO `creature_model_info` (`modelid`, `bounding_radius`, `combat_reach`, `gender`, `modelid_other_gender`) VALUES (46724, 0.383, 1.5, 0, 0);
DELETE FROM `creature_model_info` WHERE `modelid`=47953;
INSERT INTO `creature_model_info` (`modelid`, `bounding_radius`, `combat_reach`, `gender`, `modelid_other_gender`) VALUES (47953, 0.383, 1.5, 0, 0);
DELETE FROM `creature_model_info` WHERE `modelid`=47954;
INSERT INTO `creature_model_info` (`modelid`, `bounding_radius`, `combat_reach`, `gender`, `modelid_other_gender`) VALUES (47954, 0.383, 1.5, 0, 0);
DELETE FROM `creature_model_info` WHERE `modelid`=48130;
INSERT INTO `creature_model_info` (`modelid`, `bounding_radius`, `combat_reach`, `gender`, `modelid_other_gender`) VALUES (48130, 0.12, 4, 0, 0);
DELETE FROM `creature_model_info` WHERE `modelid`=48526;
INSERT INTO `creature_model_info` (`modelid`, `bounding_radius`, `combat_reach`, `gender`, `modelid_other_gender`) VALUES (48526, 0.306, 1.5, 0, 0);
DELETE FROM `creature_model_info` WHERE `modelid`=48528;
INSERT INTO `creature_model_info` (`modelid`, `bounding_radius`, `combat_reach`, `gender`, `modelid_other_gender`) VALUES (48528, 0.306, 1.5, 0, 0);
DELETE FROM `creature_model_info` WHERE `modelid`=49000;
INSERT INTO `creature_model_info` (`modelid`, `bounding_radius`, `combat_reach`, `gender`, `modelid_other_gender`) VALUES (49000, 0.6696, 2.7, 0, 0);
DELETE FROM `creature_model_info` WHERE `modelid`=49001;
INSERT INTO `creature_model_info` (`modelid`, `bounding_radius`, `combat_reach`, `gender`, `modelid_other_gender`) VALUES (49001, 0.6696, 2.7, 0, 0);
DELETE FROM `creature_model_info` WHERE `modelid`=49002;
INSERT INTO `creature_model_info` (`modelid`, `bounding_radius`, `combat_reach`, `gender`, `modelid_other_gender`) VALUES (49002, 0.6696, 2.7, 0, 0);
DELETE FROM `creature_model_info` WHERE `modelid`=49003;
INSERT INTO `creature_model_info` (`modelid`, `bounding_radius`, `combat_reach`, `gender`, `modelid_other_gender`) VALUES (49003, 0.6696, 2.7, 0, 0);
DELETE FROM `creature_model_info` WHERE `modelid`=49013;
INSERT INTO `creature_model_info` (`modelid`, `bounding_radius`, `combat_reach`, `gender`, `modelid_other_gender`) VALUES (49013, 0.4248, 2.7, 0, 0);
DELETE FROM `creature_model_info` WHERE `modelid`=49014;
INSERT INTO `creature_model_info` (`modelid`, `bounding_radius`, `combat_reach`, `gender`, `modelid_other_gender`) VALUES (49014, 0.4248, 2.7, 0, 0);
DELETE FROM `creature_model_info` WHERE `modelid`=49015;
INSERT INTO `creature_model_info` (`modelid`, `bounding_radius`, `combat_reach`, `gender`, `modelid_other_gender`) VALUES (49015, 0.4248, 2.7, 0, 0);
DELETE FROM `creature_model_info` WHERE `modelid`=49016;
INSERT INTO `creature_model_info` (`modelid`, `bounding_radius`, `combat_reach`, `gender`, `modelid_other_gender`) VALUES (49016, 0.4248, 2.7, 0, 0);
DELETE FROM `creature_model_info` WHERE `modelid`=49050;
INSERT INTO `creature_model_info` (`modelid`, `bounding_radius`, `combat_reach`, `gender`, `modelid_other_gender`) VALUES (49050, 0.4092, 1.65, 0, 0);
DELETE FROM `creature_model_info` WHERE `modelid`=49091;
INSERT INTO `creature_model_info` (`modelid`, `bounding_radius`, `combat_reach`, `gender`, `modelid_other_gender`) VALUES (49091, 0.558, 2.25, 0, 0);
DELETE FROM `creature_model_info` WHERE `modelid`=49092;
INSERT INTO `creature_model_info` (`modelid`, `bounding_radius`, `combat_reach`, `gender`, `modelid_other_gender`) VALUES (49092, 0.354, 2.25, 0, 0);
DELETE FROM `creature_model_info` WHERE `modelid`=49093;
INSERT INTO `creature_model_info` (`modelid`, `bounding_radius`, `combat_reach`, `gender`, `modelid_other_gender`) VALUES (49093, 0.354, 2.25, 0, 0);
DELETE FROM `creature_model_info` WHERE `modelid`=49267;
INSERT INTO `creature_model_info` (`modelid`, `bounding_radius`, `combat_reach`, `gender`, `modelid_other_gender`) VALUES (49267, 0.7068, 2.85, 0, 0);
DELETE FROM `creature_model_info` WHERE `modelid`=49268;
INSERT INTO `creature_model_info` (`modelid`, `bounding_radius`, `combat_reach`, `gender`, `modelid_other_gender`) VALUES (49268, 0.4602, 2.925, 0, 0);
DELETE FROM `creature_model_info` WHERE `modelid`=49269;
INSERT INTO `creature_model_info` (`modelid`, `bounding_radius`, `combat_reach`, `gender`, `modelid_other_gender`) VALUES (49269, 0.472, 3, 0, 0);
DELETE FROM `creature_model_info` WHERE `modelid`=49277;
INSERT INTO `creature_model_info` (`modelid`, `bounding_radius`, `combat_reach`, `gender`, `modelid_other_gender`) VALUES (49277, 0, 0, 2, 0);
DELETE FROM `creature_model_info` WHERE `modelid`=49283;
INSERT INTO `creature_model_info` (`modelid`, `bounding_radius`, `combat_reach`, `gender`, `modelid_other_gender`) VALUES (49283, 0, 0, 2, 0);
DELETE FROM `creature_model_info` WHERE `modelid`=49344;
INSERT INTO `creature_model_info` (`modelid`, `bounding_radius`, `combat_reach`, `gender`, `modelid_other_gender`) VALUES (49344, 0.3, 1.5, 2, 0);
DELETE FROM `creature_model_info` WHERE `modelid`=49773;
INSERT INTO `creature_model_info` (`modelid`, `bounding_radius`, `combat_reach`, `gender`, `modelid_other_gender`) VALUES (49773, 0.558, 2.25, 0, 0);
DELETE FROM `creature_model_info` WHERE `modelid`=49778;
INSERT INTO `creature_model_info` (`modelid`, `bounding_radius`, `combat_reach`, `gender`, `modelid_other_gender`) VALUES (49778, 0.558, 2.25, 0, 0);
DELETE FROM `creature_model_info` WHERE `modelid`=49781;
INSERT INTO `creature_model_info` (`modelid`, `bounding_radius`, `combat_reach`, `gender`, `modelid_other_gender`) VALUES (49781, 0.8725, 3.75, 0, 0);
DELETE FROM `creature_model_info` WHERE `modelid`=50158;
INSERT INTO `creature_model_info` (`modelid`, `bounding_radius`, `combat_reach`, `gender`, `modelid_other_gender`) VALUES (50158, 0.4248, 2.7, 0, 0);
DELETE FROM `creature_model_info` WHERE `modelid`=50159;
INSERT INTO `creature_model_info` (`modelid`, `bounding_radius`, `combat_reach`, `gender`, `modelid_other_gender`) VALUES (50159, 0.6696, 2.7, 0, 0);
DELETE FROM `creature_model_info` WHERE `modelid`=50160;
INSERT INTO `creature_model_info` (`modelid`, `bounding_radius`, `combat_reach`, `gender`, `modelid_other_gender`) VALUES (50160, 0.4248, 2.7, 0, 0);
DELETE FROM `creature_model_info` WHERE `modelid`=50162;
INSERT INTO `creature_model_info` (`modelid`, `bounding_radius`, `combat_reach`, `gender`, `modelid_other_gender`) VALUES (50162, 0.6324, 2.55, 0, 0);
DELETE FROM `creature_model_info` WHERE `modelid`=50163;
INSERT INTO `creature_model_info` (`modelid`, `bounding_radius`, `combat_reach`, `gender`, `modelid_other_gender`) VALUES (50163, 0.4012, 2.55, 0, 0);
DELETE FROM `creature_model_info` WHERE `modelid`=50164;
INSERT INTO `creature_model_info` (`modelid`, `bounding_radius`, `combat_reach`, `gender`, `modelid_other_gender`) VALUES (50164, 0.4012, 2.55, 0, 0);
DELETE FROM `creature_model_info` WHERE `modelid`=50167;
INSERT INTO `creature_model_info` (`modelid`, `bounding_radius`, `combat_reach`, `gender`, `modelid_other_gender`) VALUES (50167, 0.6696, 2.7, 0, 0);
DELETE FROM `creature_model_info` WHERE `modelid`=50168;
INSERT INTO `creature_model_info` (`modelid`, `bounding_radius`, `combat_reach`, `gender`, `modelid_other_gender`) VALUES (50168, 0.4248, 2.7, 0, 0);
DELETE FROM `creature_model_info` WHERE `modelid`=50169;
INSERT INTO `creature_model_info` (`modelid`, `bounding_radius`, `combat_reach`, `gender`, `modelid_other_gender`) VALUES (50169, 0.4248, 2.7, 0, 0);
DELETE FROM `creature_model_info` WHERE `modelid`=50174;
INSERT INTO `creature_model_info` (`modelid`, `bounding_radius`, `combat_reach`, `gender`, `modelid_other_gender`) VALUES (50174, 0.651, 2.625, 0, 0);
DELETE FROM `creature_model_info` WHERE `modelid`=50175;
INSERT INTO `creature_model_info` (`modelid`, `bounding_radius`, `combat_reach`, `gender`, `modelid_other_gender`) VALUES (50175, 0.4012, 2.55, 0, 0);
DELETE FROM `creature_model_info` WHERE `modelid`=50176;
INSERT INTO `creature_model_info` (`modelid`, `bounding_radius`, `combat_reach`, `gender`, `modelid_other_gender`) VALUES (50176, 0.413, 2.625, 0, 0);
DELETE FROM `creature_model_info` WHERE `modelid`=50192;
INSERT INTO `creature_model_info` (`modelid`, `bounding_radius`, `combat_reach`, `gender`, `modelid_other_gender`) VALUES (50192, 0.383, 1.5, 0, 0);
DELETE FROM `creature_model_info` WHERE `modelid`=50745;
INSERT INTO `creature_model_info` (`modelid`, `bounding_radius`, `combat_reach`, `gender`, `modelid_other_gender`) VALUES (50745, 0.558, 2.25, 0, 0);
DELETE FROM `creature_model_info` WHERE `modelid`=50746;
INSERT INTO `creature_model_info` (`modelid`, `bounding_radius`, `combat_reach`, `gender`, `modelid_other_gender`) VALUES (50746, 0.354, 2.25, 0, 0);
DELETE FROM `creature_model_info` WHERE `modelid`=50747;
INSERT INTO `creature_model_info` (`modelid`, `bounding_radius`, `combat_reach`, `gender`, `modelid_other_gender`) VALUES (50747, 0.354, 2.25, 0, 0);
DELETE FROM `creature_model_info` WHERE `modelid`=50774;
INSERT INTO `creature_model_info` (`modelid`, `bounding_radius`, `combat_reach`, `gender`, `modelid_other_gender`) VALUES (50774, 0.354, 2.25, 0, 0);
DELETE FROM `creature_model_info` WHERE `modelid`=50804;
INSERT INTO `creature_model_info` (`modelid`, `bounding_radius`, `combat_reach`, `gender`, `modelid_other_gender`) VALUES (50804, 2.385, 4.5, 0, 0);
DELETE FROM `creature_model_info` WHERE `modelid`=50974;
INSERT INTO `creature_model_info` (`modelid`, `bounding_radius`, `combat_reach`, `gender`, `modelid_other_gender`) VALUES (50974, 0, 0, 2, 0);
DELETE FROM `creature_model_info` WHERE `modelid`=50985;
INSERT INTO `creature_model_info` (`modelid`, `bounding_radius`, `combat_reach`, `gender`, `modelid_other_gender`) VALUES (50985, 0.3068, 1.95, 0, 0);
DELETE FROM `creature_model_info` WHERE `modelid`=50986;
INSERT INTO `creature_model_info` (`modelid`, `bounding_radius`, `combat_reach`, `gender`, `modelid_other_gender`) VALUES (50986, 0.4836, 1.95, 0, 0);
DELETE FROM `creature_model_info` WHERE `modelid`=50987;
INSERT INTO `creature_model_info` (`modelid`, `bounding_radius`, `combat_reach`, `gender`, `modelid_other_gender`) VALUES (50987, 0.4836, 1.95, 0, 0);
DELETE FROM `creature_model_info` WHERE `modelid`=50989;
INSERT INTO `creature_model_info` (`modelid`, `bounding_radius`, `combat_reach`, `gender`, `modelid_other_gender`) VALUES (50989, 0, 0, 2, 0);
DELETE FROM `creature_model_info` WHERE `modelid`=51013;
INSERT INTO `creature_model_info` (`modelid`, `bounding_radius`, `combat_reach`, `gender`, `modelid_other_gender`) VALUES (51013, 1.2, 8, 2, 0);
DELETE FROM `creature_model_info` WHERE `modelid`=51015;
INSERT INTO `creature_model_info` (`modelid`, `bounding_radius`, `combat_reach`, `gender`, `modelid_other_gender`) VALUES (51015, 0.775, 3.75, 0, 0);
DELETE FROM `creature_model_info` WHERE `modelid`=51075;
INSERT INTO `creature_model_info` (`modelid`, `bounding_radius`, `combat_reach`, `gender`, `modelid_other_gender`) VALUES (51075, 0.6885, 3.375, 0, 0);
DELETE FROM `creature_model_info` WHERE `modelid`=51077;
INSERT INTO `creature_model_info` (`modelid`, `bounding_radius`, `combat_reach`, `gender`, `modelid_other_gender`) VALUES (51077, 0.5508, 2.7, 0, 0);
DELETE FROM `creature_model_info` WHERE `modelid`=51079;
INSERT INTO `creature_model_info` (`modelid`, `bounding_radius`, `combat_reach`, `gender`, `modelid_other_gender`) VALUES (51079, 0, 0, 2, 0);
DELETE FROM `creature_model_info` WHERE `modelid`=51127;
INSERT INTO `creature_model_info` (`modelid`, `bounding_radius`, `combat_reach`, `gender`, `modelid_other_gender`) VALUES (51127, 3, 4.5, 0, 0);
DELETE FROM `creature_model_info` WHERE `modelid`=51135;
INSERT INTO `creature_model_info` (`modelid`, `bounding_radius`, `combat_reach`, `gender`, `modelid_other_gender`) VALUES (51135, 3.85, 16.5, 0, 0);
DELETE FROM `creature_model_info` WHERE `modelid`=51146;
INSERT INTO `creature_model_info` (`modelid`, `bounding_radius`, `combat_reach`, `gender`, `modelid_other_gender`) VALUES (51146, 5, 6.25, 0, 0);
DELETE FROM `creature_model_info` WHERE `modelid`=51183;
INSERT INTO `creature_model_info` (`modelid`, `bounding_radius`, `combat_reach`, `gender`, `modelid_other_gender`) VALUES (51183, 0.12, 4, 0, 0);
DELETE FROM `creature_model_info` WHERE `modelid`=51194;
INSERT INTO `creature_model_info` (`modelid`, `bounding_radius`, `combat_reach`, `gender`, `modelid_other_gender`) VALUES (51194, 0.7639, 2.5, 0, 0);
DELETE FROM `creature_model_info` WHERE `modelid`=51213;
INSERT INTO `creature_model_info` (`modelid`, `bounding_radius`, `combat_reach`, `gender`, `modelid_other_gender`) VALUES (51213, 0.1, 25, 0, 0);
DELETE FROM `creature_model_info` WHERE `modelid`=51214;
INSERT INTO `creature_model_info` (`modelid`, `bounding_radius`, `combat_reach`, `gender`, `modelid_other_gender`) VALUES (51214, 0.31, 1.5, 2, 0);
DELETE FROM `creature_model_info` WHERE `modelid`=51228;
INSERT INTO `creature_model_info` (`modelid`, `bounding_radius`, `combat_reach`, `gender`, `modelid_other_gender`) VALUES (51228, 2.2596, 6.16, 0, 0);
DELETE FROM `creature_model_info` WHERE `modelid`=51229;
INSERT INTO `creature_model_info` (`modelid`, `bounding_radius`, `combat_reach`, `gender`, `modelid_other_gender`) VALUES (51229, 2.2596, 6.16, 0, 0);
DELETE FROM `creature_model_info` WHERE `modelid`=51230;
INSERT INTO `creature_model_info` (`modelid`, `bounding_radius`, `combat_reach`, `gender`, `modelid_other_gender`) VALUES (51230, 2.2596, 6.16, 0, 0);
DELETE FROM `creature_model_info` WHERE `modelid`=51232;
INSERT INTO `creature_model_info` (`modelid`, `bounding_radius`, `combat_reach`, `gender`, `modelid_other_gender`) VALUES (51232, 0.7639, 2.5, 0, 0);
DELETE FROM `creature_model_info` WHERE `modelid`=51235;
INSERT INTO `creature_model_info` (`modelid`, `bounding_radius`, `combat_reach`, `gender`, `modelid_other_gender`) VALUES (51235, 2, 3, 0, 0);
DELETE FROM `creature_model_info` WHERE `modelid`=51237;
INSERT INTO `creature_model_info` (`modelid`, `bounding_radius`, `combat_reach`, `gender`, `modelid_other_gender`) VALUES (51237, 2, 3, 0, 0);
DELETE FROM `creature_model_info` WHERE `modelid`=51284;
INSERT INTO `creature_model_info` (`modelid`, `bounding_radius`, `combat_reach`, `gender`, `modelid_other_gender`) VALUES (51284, 2.5, 3.75, 2, 0);
DELETE FROM `creature_model_info` WHERE `modelid`=51344;
INSERT INTO `creature_model_info` (`modelid`, `bounding_radius`, `combat_reach`, `gender`, `modelid_other_gender`) VALUES (51344, 0.472, 3, 0, 0);
DELETE FROM `creature_model_info` WHERE `modelid`=51470;
INSERT INTO `creature_model_info` (`modelid`, `bounding_radius`, `combat_reach`, `gender`, `modelid_other_gender`) VALUES (51470, 10.5, 17.5, 0, 0);
DELETE FROM `creature_model_info` WHERE `modelid`=51471;
INSERT INTO `creature_model_info` (`modelid`, `bounding_radius`, `combat_reach`, `gender`, `modelid_other_gender`) VALUES (51471, 0, 0, 2, 0);
DELETE FROM `creature_model_info` WHERE `modelid`=51472;
INSERT INTO `creature_model_info` (`modelid`, `bounding_radius`, `combat_reach`, `gender`, `modelid_other_gender`) VALUES (51472, 0, 0, 2, 0);
DELETE FROM `creature_model_info` WHERE `modelid`=51500;
INSERT INTO `creature_model_info` (`modelid`, `bounding_radius`, `combat_reach`, `gender`, `modelid_other_gender`) VALUES (51500, 0.306, 1.5, 0, 0);
DELETE FROM `creature_model_info` WHERE `modelid`=51573;
INSERT INTO `creature_model_info` (`modelid`, `bounding_radius`, `combat_reach`, `gender`, `modelid_other_gender`) VALUES (51573, 0.306, 1.5, 0, 0);
DELETE FROM `creature_model_info` WHERE `modelid`=51574;
INSERT INTO `creature_model_info` (`modelid`, `bounding_radius`, `combat_reach`, `gender`, `modelid_other_gender`) VALUES (51574, 0.306, 1.5, 0, 0);
DELETE FROM `creature_model_info` WHERE `modelid`=51575;
INSERT INTO `creature_model_info` (`modelid`, `bounding_radius`, `combat_reach`, `gender`, `modelid_other_gender`) VALUES (51575, 0.306, 1.5, 0, 0);
DELETE FROM `creature_model_info` WHERE `modelid`=51585;
INSERT INTO `creature_model_info` (`modelid`, `bounding_radius`, `combat_reach`, `gender`, `modelid_other_gender`) VALUES (51585, 0.306, 1.5, 0, 0);
DELETE FROM `creature_model_info` WHERE `modelid`=51587;
INSERT INTO `creature_model_info` (`modelid`, `bounding_radius`, `combat_reach`, `gender`, `modelid_other_gender`) VALUES (51587, 0.306, 1.5, 0, 0);
DELETE FROM `creature_model_info` WHERE `modelid`=51593;
INSERT INTO `creature_model_info` (`modelid`, `bounding_radius`, `combat_reach`, `gender`, `modelid_other_gender`) VALUES (51593, 0.306, 1.5, 0, 0);
DELETE FROM `creature_model_info` WHERE `modelid`=51594;
INSERT INTO `creature_model_info` (`modelid`, `bounding_radius`, `combat_reach`, `gender`, `modelid_other_gender`) VALUES (51594, 0.306, 1.5, 0, 0);
DELETE FROM `creature_model_info` WHERE `modelid`=51595;
INSERT INTO `creature_model_info` (`modelid`, `bounding_radius`, `combat_reach`, `gender`, `modelid_other_gender`) VALUES (51595, 0.306, 1.5, 0, 0);
DELETE FROM `creature_model_info` WHERE `modelid`=51631;
INSERT INTO `creature_model_info` (`modelid`, `bounding_radius`, `combat_reach`, `gender`, `modelid_other_gender`) VALUES (51631, 0.306, 1.5, 0, 0);
DELETE FROM `creature_model_info` WHERE `modelid`=51632;
INSERT INTO `creature_model_info` (`modelid`, `bounding_radius`, `combat_reach`, `gender`, `modelid_other_gender`) VALUES (51632, 0.306, 1.5, 0, 0);
DELETE FROM `creature_model_info` WHERE `modelid`=51633;
INSERT INTO `creature_model_info` (`modelid`, `bounding_radius`, `combat_reach`, `gender`, `modelid_other_gender`) VALUES (51633, 0.306, 1.5, 0, 0);
DELETE FROM `creature_model_info` WHERE `modelid`=51648;
INSERT INTO `creature_model_info` (`modelid`, `bounding_radius`, `combat_reach`, `gender`, `modelid_other_gender`) VALUES (51648, 0.3978, 1.95, 0, 0);
DELETE FROM `creature_model_info` WHERE `modelid`=51649;
INSERT INTO `creature_model_info` (`modelid`, `bounding_radius`, `combat_reach`, `gender`, `modelid_other_gender`) VALUES (51649, 0.3978, 1.95, 0, 0);
DELETE FROM `creature_model_info` WHERE `modelid`=51795;
INSERT INTO `creature_model_info` (`modelid`, `bounding_radius`, `combat_reach`, `gender`, `modelid_other_gender`) VALUES (51795, 0.3, 1.5, 2, 0);
DELETE FROM `creature_model_info` WHERE `modelid`=51810;
INSERT INTO `creature_model_info` (`modelid`, `bounding_radius`, `combat_reach`, `gender`, `modelid_other_gender`) VALUES (51810, 0.3978, 1.95, 0, 0);
DELETE FROM `creature_model_info` WHERE `modelid`=51811;
INSERT INTO `creature_model_info` (`modelid`, `bounding_radius`, `combat_reach`, `gender`, `modelid_other_gender`) VALUES (51811, 0.3978, 1.95, 0, 0);
DELETE FROM `creature_model_info` WHERE `modelid`=51813;
INSERT INTO `creature_model_info` (`modelid`, `bounding_radius`, `combat_reach`, `gender`, `modelid_other_gender`) VALUES (51813, 1.5, 2.25, 0, 0);
