/*
* This file is part of Project SkyFire https://www.projectskyfire.org. 
* See LICENSE.md file for Copyright information
*/

#ifndef DEF_PINNACLE_H
#define DEF_PINNACLE_H

enum Data
{
    DATA_SVALA_SORROWGRAVE_EVENT,
    DATA_GORTOK_PALEHOOF_EVENT,
    DATA_SKADI_THE_RUTHLESS_EVENT,
    DATA_KING_YMIRON_EVENT
};

enum Data64
{
    DATA_SVALA,
    DATA_SVALA_SORROWGRAVE,
    DATA_GORTOK_PALEHOOF,
    DATA_SKADI_THE_RUTHLESS,
    DATA_NPC_GRAUF,
    DATA_KING_YMIRON,
    DATA_NPC_FRENZIED_WORGEN,
    DATA_NPC_RAVENOUS_FURBOLG,
    DATA_NPC_MASSIVE_JORMUNGAR,
    DATA_NPC_FEROCIOUS_RHINO,
    DATA_NPC_ORB,
    DATA_GORTOK_PALEHOOF_SPHERE,
    DATA_SACRIFICED_PLAYER
};

enum CreatureID
{
    BOSS_SVALA_SORROWGRAVE   = 26668,
    BOSS_GORTOK_PALEHOOF     = 26687,
    BOSS_SKADI_RUTHLESS      = 26693,
    BOSS_KING_YMIRON         = 26861,
    NPC_FRENZIED_WORGEN      = 26683,
    NPC_RAVENOUS_FURBOLG     = 26684,
    NPC_MASSIVE_JORMUNGAR    = 26685,
    NPC_FEROCIOUS_RHINO      = 26686,
    NPC_SVALA                = 29281,
    NPC_PALEHOOF_ORB         = 26688
};

#endif
