-- Darkmoon Faire Shooting Gallery visible target stands.

SET @DARKMOON_EVENT_ENTRY := 75;
SET @DARKMOON_SHOOTING_GALLERY_TARGET_GUID_START := 8200296;
SET @DARKMOON_SHOOTING_GALLERY_TARGET_GUID_COUNT := 3;

START TRANSACTION;

DELETE FROM `creature_addon`
WHERE `guid` BETWEEN @DARKMOON_SHOOTING_GALLERY_TARGET_GUID_START
    AND (@DARKMOON_SHOOTING_GALLERY_TARGET_GUID_START + @DARKMOON_SHOOTING_GALLERY_TARGET_GUID_COUNT - 1);

DELETE FROM `game_event_creature`
WHERE `guid` BETWEEN @DARKMOON_SHOOTING_GALLERY_TARGET_GUID_START
    AND (@DARKMOON_SHOOTING_GALLERY_TARGET_GUID_START + @DARKMOON_SHOOTING_GALLERY_TARGET_GUID_COUNT - 1);

DELETE FROM `creature`
WHERE `guid` BETWEEN @DARKMOON_SHOOTING_GALLERY_TARGET_GUID_START
    AND (@DARKMOON_SHOOTING_GALLERY_TARGET_GUID_START + @DARKMOON_SHOOTING_GALLERY_TARGET_GUID_COUNT - 1);

INSERT INTO `creature` (`guid`, `id`, `map`, `spawnMask`, `phaseId`, `phaseGroup`, `modelid`, `equipment_id`, `position_x`, `position_y`, `position_z`, `orientation`, `spawntimesecs`, `spawndist`, `currentwaypoint`, `curhealth`, `curmana`, `MovementType`, `npcflag`, `unit_flags`, `dynamicflags`) VALUES
(@DARKMOON_SHOOTING_GALLERY_TARGET_GUID_START + 0, 54231, 974, 1, 0, 0, 28442, 0, -4068.08, 6353.26, 13.4977, 4.04916, 300, 0, 0, 1, 0, 0, 0, 0, 0),
(@DARKMOON_SHOOTING_GALLERY_TARGET_GUID_START + 1, 54231, 974, 1, 0, 0, 28442, 0, -4069.91, 6355.00, 13.4849, 4.13643, 300, 0, 0, 1, 0, 0, 0, 0, 0),
(@DARKMOON_SHOOTING_GALLERY_TARGET_GUID_START + 2, 54231, 974, 1, 0, 0, 28442, 0, -4072.09, 6356.73, 13.4903, 4.31096, 300, 0, 0, 1, 0, 0, 0, 0, 0);

INSERT IGNORE INTO `game_event_creature` (`eventEntry`, `guid`) VALUES
(@DARKMOON_EVENT_ENTRY, @DARKMOON_SHOOTING_GALLERY_TARGET_GUID_START + 0),
(@DARKMOON_EVENT_ENTRY, @DARKMOON_SHOOTING_GALLERY_TARGET_GUID_START + 1),
(@DARKMOON_EVENT_ENTRY, @DARKMOON_SHOOTING_GALLERY_TARGET_GUID_START + 2);

COMMIT;
