name: windows-build

on:
  push:
    branches: [ main, trunk ]
    paths-ignore:
      - 'sql/**'
      
concurrency:
  group: ${{ github.head_ref }} || concat(${{ github.ref }}, ${{ github.workflow }})
  cancel-in-progress: true


env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  REPO_DIR : ${{github.workspace}}
  BUILD_DIR: ${{github.workspace}}/bin/builddir
    
jobs:
  build:
    runs-on: windows-latest
    
    steps:
    #git checkout
    - uses: actions/checkout@v2

    - uses: FranzDiebold/github-env-vars-action@v2
    - name: Create Build Environment
      run: |
        
        echo "ARCHIVE_FILENAME=$env:CI_REPOSITORY_NAME-${{matrix.TYPE}}-$env:CI_SHA_SHORT.zip" >> $env:GITHUB_ENV
        cmake -E make_directory ${{ env.BUILD_DIR }}
    # install dependencies
            
    - name: windows dependencies
      #Sets versions for ACE
      #env:
      #  ACE_VERSION: 6.5.11
      #  ACE_VERSION2: 6_5_11

      run: |
        #make
        choco install -y make
        #cmake
        choco install -y cmake --pre 
        #openssl
        choco install -y openssl --version=1.1.1.3
      #git bash shell
      shell: bash

    #build and install
    - name: windows build & install
      run: |
        cd $GITHUB_WORKSPACE
        
        mkdir -p build && cd build
        cmake .. -DTOOLS=ON-A x64
        cmake --build . --config RelWithDebInfo --parallel 4
      #git bash shell
      shell: bash
    - name: Create Upload File Name
      run: |
          echo "ARCHIVE_FILENAME=${{ github.event.repository.name }}-$(git rev-parse --short HEAD).zip" >> $env:GITHUB_ENV
      
